import type { TransitionDefinition } from '../types';

// Deterministic burn-edge overlays plus a warm exposure wash.
export const filmBurn: TransitionDefinition = {
  id: 'film-burn',
  name: 'Film Burn',
  category: 'light',
  defaultDuration: 1.2,
  minDuration: 0.1,
  maxDuration: 5,
  description: 'Warm burn edge and exposure wash reveal the incoming clip',
  params: {
    color: {
      type: 'color',
      label: 'Color',
      defaultValue: '#ff6a2e',
    },
  },
  recipe: [
    {
      kind: 'opacity',
      target: 'outgoing',
      from: 1,
      to: 0,
      startProgress: 0.18,
      endProgress: 0.82,
      curve: 'ease-in',
    },
    {
      kind: 'opacity',
      target: 'incoming',
      from: 0,
      to: 1,
      startProgress: 0.28,
      endProgress: 0.9,
      curve: 'ease-out',
    },
    {
      kind: 'overlay',
      overlay: 'film-burn',
      color: '#ff6a2e',
      colorParam: 'color',
      blendMode: 'normal',
      opacity: { from: 0, to: 0.62 },
      centerX: { from: -0.15, to: 0.56 },
      width: 0.34,
      softness: 0.24,
      angle: 0.06,
      startProgress: 0,
      endProgress: 0.56,
      curve: 'ease-out',
    },
    {
      kind: 'overlay',
      overlay: 'film-burn',
      color: '#ff6a2e',
      colorParam: 'color',
      blendMode: 'normal',
      opacity: { from: 0.52, to: 0 },
      centerX: { from: 0.44, to: 1.12 },
      width: 0.48,
      softness: 0.34,
      angle: -0.1,
      startProgress: 0.44,
      endProgress: 1,
      curve: 'ease-in',
    },
  ],
};
