import { describe, expect, it } from 'vitest';
import { MOTION_MODIFIER_MAX_MODIFIERS, parseMotionModifierStackContract } from '../../src/services/motionDesign/modifiers/contracts';
import { planMotionModifierSemanticOperation } from '../../src/services/motionDesign/modifiers/semanticOperations';

const target = { path: 'replicator.offset.position.x', operation: 'add', amount: 10 };
const add = (current?: any) => planMotionModifierSemanticOperation(current, { type: 'add', kind: 'random', target });

describe('MD4 Motion Modifier semantic authoring', () => {
  it('adds a parseable stack and advances 0 to 1', () => { const plan = add(); expect(plan.ok).toBe(true); if (plan.ok) { expect(plan.contract.revision).toBe(1); expect(parseMotionModifierStackContract(plan.contract).modifiers[0].id).toBeTruthy(); } });
  it('rejects the modifier budget', () => { let stack: any; for (let i = 0; i < MOTION_MODIFIER_MAX_MODIFIERS; i++) { const plan = add(stack); expect(plan.ok).toBe(true); if (plan.ok) stack = plan.contract; } const plan = add(stack); expect(plan.ok).toBe(false); if (!plan.ok) expect(plan.diagnostics[0].code).toBe('MOTION_MODIFIER_MODIFIER_BUDGET_EXCEEDED'); });
  it('updates only its named modifier and fails unknown ids', () => { const first = add(); if (!first.ok) throw new Error(); const second = planMotionModifierSemanticOperation(first.contract, { type: 'add', kind: 'oscillator', target }); if (!second.ok) throw new Error(); const plan = planMotionModifierSemanticOperation(second.contract, { type: 'update', modifierId: second.contract.modifiers[0].id, enabled: false }); expect(plan.ok).toBe(true); if (plan.ok) expect(plan.contract.modifiers.map((m) => m.enabled)).toEqual([false, true]); expect(planMotionModifierSemanticOperation(second.contract, { type: 'remove', modifierId: 'missing' }).ok).toBe(false); });
  it('removes and reorders with canonical orders', () => { const a = add(); if (!a.ok) throw new Error(); const b = add(a.contract); if (!b.ok) throw new Error(); const reordered = planMotionModifierSemanticOperation(b.contract, { type: 'reorder', modifierId: b.contract.modifiers[1].id, newIndex: 0 }); expect(reordered.ok).toBe(true); if (reordered.ok) { expect(reordered.contract.modifiers.map((m) => m.order)).toEqual([0, 1]); const removed = planMotionModifierSemanticOperation(reordered.contract, { type: 'remove', modifierId: reordered.contract.modifiers[0].id }); expect(removed.ok).toBe(true); if (removed.ok) expect(removed.contract.modifiers[0].order).toBe(0); } expect(planMotionModifierSemanticOperation(b.contract, { type: 'reorder', modifierId: b.contract.modifiers[0].id, newIndex: 9 }).ok).toBe(false); });
  it('sets and clears falloff', () => { const base = add(); if (!base.ok) throw new Error(); const set = planMotionModifierSemanticOperation(base.contract, { type: 'set-falloff', falloff: { shapeClipId: 'shape-1', shapeRevision: 0, feather: 0, invert: false, clip: false }, referencedShapeRevision: 7 }); expect(set.ok).toBe(true); if (set.ok) { expect(set.contract.falloff?.shapeClipId).toBe('shape-1'); expect(set.contract.falloff?.shapeRevision).toBe(7); const cleared = planMotionModifierSemanticOperation(set.contract, { type: 'clear-falloff' }); expect(cleared.ok).toBe(true); if (cleared.ok) expect(cleared.contract.falloff).toBeUndefined(); } });
  it('rejects invalid kind field combinations', () => { const plan = planMotionModifierSemanticOperation(undefined, { type: 'add', kind: 'random', target, fields: { waveform: 'sine' } }); expect(plan.ok).toBe(false); });
});
