import type { TransitionDefinition } from '../types';

export const projectorFlicker: TransitionDefinition = {
  id: 'projector-flicker',
  name: 'Projector Flicker',
  category: 'light',
  defaultDuration: 0.9,
  minDuration: 0.1,
  maxDuration: 4,
  description: 'Deterministic projector-style exposure flicker over the cut',
  recipe: [
    {
      kind: 'solid',
      color: '#fff3c4',
    },
    {
      kind: 'opacity',
      target: 'solid',
      from: 0,
      to: 0.34,
      startProgress: 0,
      endProgress: 0.18,
      curve: 'ease-out',
    },
    {
      kind: 'opacity',
      target: 'solid',
      from: 0.34,
      to: 0.08,
      startProgress: 0.18,
      endProgress: 0.36,
      curve: 'ease-in',
    },
    {
      kind: 'opacity',
      target: 'solid',
      from: 0.08,
      to: 0.46,
      startProgress: 0.36,
      endProgress: 0.5,
      curve: 'ease-out',
    },
    {
      kind: 'opacity',
      target: 'solid',
      from: 0.46,
      to: 0.12,
      startProgress: 0.5,
      endProgress: 0.68,
      curve: 'ease-in',
    },
    {
      kind: 'opacity',
      target: 'solid',
      from: 0.12,
      to: 0,
      startProgress: 0.68,
      endProgress: 1,
      curve: 'ease-in-out',
    },
    {
      kind: 'opacity',
      target: 'outgoing',
      from: 1,
      to: 0,
      startProgress: 0.22,
      endProgress: 0.72,
      curve: 'ease-in-out',
    },
    {
      kind: 'opacity',
      target: 'incoming',
      from: 0,
      to: 1,
      startProgress: 0.28,
      endProgress: 0.82,
      curve: 'ease-in-out',
    },
  ],
};
