import {
  TIMELINE_RUNTIME_POLICY_IDS,
  type RenderResourceKind,
  type TimelineRuntimePolicyDescriptor,
  type TimelineRuntimePolicyId,
} from './runtimeCoordinatorTypes';

export const RENDER_RESOURCE_KINDS = [
  'video-frame-provider',
  'html-media',
  'image-canvas',
  'native-decoder',
  'nested-composition-texture',
  'gpu-texture',
  'model',
  'gaussian-splat',
  'motion-data',
  'audio-buffer',
  'audio-source-clock',
  'runtime-binding',
  'job',
] as const satisfies readonly RenderResourceKind[];

const INTERACTIVE_RESOURCE_KINDS = [
  'video-frame-provider',
  'html-media',
  'image-canvas',
  'native-decoder',
  'nested-composition-texture',
  'gpu-texture',
  'model',
  'gaussian-splat',
  'motion-data',
  'audio-buffer',
  'audio-source-clock',
  'runtime-binding',
  'job',
] as const satisfies readonly RenderResourceKind[];

const NON_INTERACTIVE_RESOURCE_KINDS = [
  'video-frame-provider',
  'html-media',
  'image-canvas',
  'native-decoder',
  'nested-composition-texture',
  'gpu-texture',
  'model',
  'gaussian-splat',
  'motion-data',
  'audio-buffer',
  'audio-source-clock',
  'runtime-binding',
  'job',
] as const satisfies readonly RenderResourceKind[];

export const TIMELINE_RUNTIME_POLICY_DESCRIPTORS = [
  {
    id: 'interactive',
    label: 'Interactive Playback',
    mode: 'interactive',
    description: 'Active and near-active timeline resources for preview playback and scrubbing.',
    priority: 100,
    interactive: true,
    ownsPlaybackClock: true,
    allowedResourceKinds: INTERACTIVE_RESOURCE_KINDS,
    defaultBudget: {
      maxResources: 72,
      maxSessions: 16,
      maxFrameProviders: 8,
      maxHtmlMediaElements: 24,
      maxNativeDecoders: 4,
      maxGpuTextures: 16,
      maxImageBitmaps: 64,
      maxAudioSources: 32,
      maxHeapBytes: 1536 * 1024 * 1024,
      maxGpuBytes: 768 * 1024 * 1024,
      warmWindowSeconds: 12,
    },
  },
  {
    id: 'background',
    label: 'Background Layers',
    mode: 'background',
    description: 'Persistent background layer resources that can render outside active clip focus.',
    priority: 70,
    interactive: false,
    ownsPlaybackClock: false,
    allowedResourceKinds: INTERACTIVE_RESOURCE_KINDS,
    defaultBudget: {
      maxResources: 32,
      maxSessions: 8,
      maxFrameProviders: 4,
      maxHtmlMediaElements: 6,
      maxNativeDecoders: 2,
      maxGpuTextures: 12,
      maxImageBitmaps: 32,
      maxAudioSources: 4,
      maxHeapBytes: 256 * 1024 * 1024,
      maxGpuBytes: 512 * 1024 * 1024,
      warmWindowSeconds: 8,
    },
  },
  {
    id: 'slot-deck',
    label: 'Slot Deck',
    mode: 'interactive',
    description: 'Program output and layer slot resources outside the editor timeline track stack.',
    priority: 80,
    interactive: true,
    ownsPlaybackClock: true,
    allowedResourceKinds: INTERACTIVE_RESOURCE_KINDS,
    defaultBudget: {
      maxResources: 48,
      maxSessions: 12,
      maxFrameProviders: 6,
      maxHtmlMediaElements: 8,
      maxNativeDecoders: 3,
      maxGpuTextures: 16,
      maxImageBitmaps: 48,
      maxAudioSources: 8,
      maxHeapBytes: 384 * 1024 * 1024,
      maxGpuBytes: 768 * 1024 * 1024,
      warmWindowSeconds: 10,
    },
  },
  {
    id: 'composition-render',
    label: 'Composition Render',
    mode: 'background',
    description: 'Nested composition evaluation and composition renderer prepared sources.',
    priority: 60,
    interactive: false,
    ownsPlaybackClock: false,
    allowedResourceKinds: NON_INTERACTIVE_RESOURCE_KINDS,
    defaultBudget: {
      maxResources: 64,
      maxSessions: 24,
      maxFrameProviders: 12,
      maxHtmlMediaElements: 12,
      maxNativeDecoders: 4,
      maxGpuTextures: 24,
      maxImageBitmaps: 96,
      maxAudioSources: 8,
      maxHeapBytes: 512 * 1024 * 1024,
      maxGpuBytes: 1024 * 1024 * 1024,
      warmWindowSeconds: 6,
    },
  },
  {
    id: 'thumbnail',
    label: 'Thumbnail',
    mode: 'background',
    description: 'Visible thumbnail DB loads, missing-thumbnail generation, and bitmap decode work.',
    priority: 40,
    interactive: false,
    ownsPlaybackClock: false,
    allowedResourceKinds: [
      'video-frame-provider',
      'html-media',
      'image-canvas',
      'native-decoder',
      'runtime-binding',
      'job',
    ],
    defaultBudget: {
      maxResources: 288,
      maxSessions: 8,
      maxFrameProviders: 4,
      maxHtmlMediaElements: 4,
      maxNativeDecoders: 2,
      maxImageBitmaps: 256,
      maxJobs: 4,
      maxHeapBytes: 256 * 1024 * 1024,
      maxGpuBytes: 128 * 1024 * 1024,
    },
  },
  {
    id: 'render-target',
    label: 'Render Target',
    mode: 'background',
    description: 'Render-target generation and dependency refresh work outside live playback.',
    priority: 45,
    interactive: false,
    ownsPlaybackClock: false,
    allowedResourceKinds: NON_INTERACTIVE_RESOURCE_KINDS,
    defaultBudget: {
      maxResources: 48,
      maxSessions: 12,
      maxFrameProviders: 6,
      maxHtmlMediaElements: 6,
      maxNativeDecoders: 3,
      maxGpuTextures: 24,
      maxImageBitmaps: 96,
      maxJobs: 3,
      maxHeapBytes: 384 * 1024 * 1024,
      maxGpuBytes: 1024 * 1024 * 1024,
    },
  },
  {
    id: 'ram-preview',
    label: 'RAM Preview',
    mode: 'offline',
    description: 'RAM preview pre-render and playback resources with explicit non-interactive policy.',
    priority: 55,
    interactive: false,
    ownsPlaybackClock: true,
    allowedResourceKinds: NON_INTERACTIVE_RESOURCE_KINDS,
    defaultBudget: {
      maxResources: 96,
      maxSessions: 24,
      maxFrameProviders: 16,
      maxHtmlMediaElements: 16,
      maxNativeDecoders: 6,
      maxGpuTextures: 48,
      maxImageBitmaps: 512,
      maxAudioSources: 12,
      maxJobs: 2,
      maxHeapBytes: 1024 * 1024 * 1024,
      maxGpuBytes: 1536 * 1024 * 1024,
    },
  },
  {
    id: 'export',
    label: 'Export',
    mode: 'offline',
    description: 'Export clip preparation, seeking, layer building, audio, and cleanup resources.',
    priority: 50,
    interactive: false,
    ownsPlaybackClock: true,
    allowedResourceKinds: NON_INTERACTIVE_RESOURCE_KINDS,
    defaultBudget: {
      maxResources: 128,
      maxSessions: 48,
      maxFrameProviders: 24,
      maxHtmlMediaElements: 24,
      maxNativeDecoders: 8,
      maxGpuTextures: 64,
      maxImageBitmaps: 512,
      maxAudioSources: 24,
      maxJobs: 1,
      maxHeapBytes: 1536 * 1024 * 1024,
      maxGpuBytes: 2048 * 1024 * 1024,
    },
  },
] as const satisfies readonly TimelineRuntimePolicyDescriptor[];

export function isTimelineRuntimePolicyId(value: string): value is TimelineRuntimePolicyId {
  return (TIMELINE_RUNTIME_POLICY_IDS as readonly string[]).includes(value);
}

export function isRenderResourceKind(value: string): value is RenderResourceKind {
  return (RENDER_RESOURCE_KINDS as readonly string[]).includes(value);
}
