// Pixel Particle Disintegration render effect

import type { EffectDefinition } from '../../types';

export const pixelParticleDisintegrate: EffectDefinition = {
  id: 'pixel-particle-disintegrate',
  name: 'Pixel Particle Disintegrate',
  category: 'stylize',
  pipelineKind: 'particle-render',

  params: {
    progress: {
      type: 'number',
      label: 'Progress',
      default: 0,
      min: 0,
      max: 1,
      step: 0.01,
      animatable: true,
    },
    cellSize: {
      type: 'number',
      label: 'Cell Size',
      default: 8,
      min: 2,
      max: 64,
      step: 1,
      animatable: false,
    },
    particleSize: {
      type: 'number',
      label: 'Particle Size',
      default: 1.2,
      min: 0.25,
      max: 4,
      step: 0.05,
      animatable: true,
    },
    spread: {
      type: 'number',
      label: 'Spread',
      default: 0.55,
      min: 0,
      max: 2,
      step: 0.01,
      animatable: true,
    },
    depth: {
      type: 'number',
      label: 'Depth',
      default: 0.45,
      min: 0,
      max: 2,
      step: 0.01,
      animatable: true,
    },
    curlStrength: {
      type: 'number',
      label: 'Curl',
      default: 0.35,
      min: 0,
      max: 2,
      step: 0.01,
      animatable: true,
    },
    turbulence: {
      type: 'number',
      label: 'Turbulence',
      default: 0.2,
      min: 0,
      max: 1.5,
      step: 0.01,
      animatable: true,
    },
    directionX: {
      type: 'number',
      label: 'Direction X',
      default: 0,
      min: -2,
      max: 2,
      step: 0.01,
      animatable: true,
    },
    directionY: {
      type: 'number',
      label: 'Direction Y',
      default: -0.25,
      min: -2,
      max: 2,
      step: 0.01,
      animatable: true,
    },
    gravity: {
      type: 'number',
      label: 'Gravity',
      default: 0.35,
      min: -2,
      max: 2,
      step: 0.01,
      animatable: true,
    },
    spin: {
      type: 'number',
      label: 'Spin',
      default: 0.7,
      min: -4,
      max: 4,
      step: 0.01,
      animatable: true,
    },
    stagger: {
      type: 'number',
      label: 'Stagger',
      default: 0.35,
      min: 0,
      max: 0.95,
      step: 0.01,
      animatable: true,
    },
    gustStrength: {
      type: 'number',
      label: 'Gust Strength',
      default: 0.75,
      min: 0,
      max: 1.5,
      step: 0.01,
      animatable: true,
    },
    gustScale: {
      type: 'number',
      label: 'Gust Scale',
      default: 5.5,
      min: 1,
      max: 18,
      step: 0.1,
      animatable: false,
    },
    windSweep: {
      type: 'number',
      label: 'Wind Sweep',
      default: 0.35,
      min: 0,
      max: 1,
      step: 0.01,
      animatable: true,
    },
    releaseContrast: {
      type: 'number',
      label: 'Release Contrast',
      default: 0.65,
      min: 0,
      max: 1.5,
      step: 0.01,
      animatable: true,
    },
    tail: {
      type: 'number',
      label: 'Tail',
      default: 0.45,
      min: 0.05,
      max: 1,
      step: 0.01,
      animatable: true,
    },
    seed: {
      type: 'number',
      label: 'Seed',
      default: 1,
      min: 0,
      max: 100000,
      step: 1,
      animatable: false,
    },
    maxPreviewParticles: {
      type: 'number',
      label: 'Preview Particle Budget',
      default: 60000,
      min: 4000,
      max: 160000,
      step: 1000,
      animatable: false,
      quality: true,
    },
    maxExportParticles: {
      type: 'number',
      label: 'Export Particle Budget',
      default: 180000,
      min: 8000,
      max: 500000,
      step: 1000,
      animatable: false,
      quality: true,
    },
    maxInstances: {
      type: 'number',
      label: 'Hard Particle Limit',
      default: 220000,
      min: 8000,
      max: 500000,
      step: 1000,
      animatable: false,
      quality: true,
    },
    softness: {
      type: 'number',
      label: 'Softness',
      default: 0.55,
      min: 0,
      max: 1,
      step: 0.01,
      animatable: true,
    },
    shape: {
      type: 'select',
      label: 'Shape',
      default: 'soft-circle',
      options: [
        { value: 'square', label: 'Square' },
        { value: 'soft-circle', label: 'Soft Circle' },
        { value: 'shard', label: 'Shard' },
      ],
      animatable: false,
    },
  },
};
