import type { TransitionDefinition } from '../types';

export const zoomBlur: TransitionDefinition = {
  id: 'zoom-blur',
  name: 'Zoom Blur',
  category: 'zoom',
  defaultDuration: 1.15,
  minDuration: 0.1,
  maxDuration: 5,
  description: 'Push through the cut with zoom blur on both clips',
  recipe: [
    {
      kind: 'opacity',
      target: 'outgoing',
      from: 1,
      to: 0,
      startProgress: 0.24,
      endProgress: 0.72,
      curve: 'ease-in',
    },
    {
      kind: 'opacity',
      target: 'incoming',
      from: 0,
      to: 1,
      startProgress: 0.28,
      endProgress: 0.9,
      curve: 'ease-out',
    },
    {
      kind: 'transform',
      target: 'outgoing',
      scaleX: { from: 1, to: 1.1 },
      scaleY: { from: 1, to: 1.1 },
      curve: 'ease-in',
    },
    {
      kind: 'transform',
      target: 'incoming',
      scaleX: { from: 1.16, to: 1 },
      scaleY: { from: 1.16, to: 1 },
      curve: 'ease-out',
    },
    {
      kind: 'effect',
      target: 'outgoing',
      effectType: 'zoom-blur',
      effectName: 'Zoom Blur',
      params: {
        amount: { from: 0, to: 0.46 },
        centerX: 0.5,
        centerY: 0.5,
        samples: 32,
      },
      startProgress: 0,
      endProgress: 0.62,
      curve: 'ease-in',
    },
    {
      kind: 'effect',
      target: 'incoming',
      effectType: 'zoom-blur',
      effectName: 'Zoom Blur',
      params: {
        amount: { from: 0.46, to: 0 },
        centerX: 0.5,
        centerY: 0.5,
        samples: 32,
      },
      startProgress: 0.38,
      endProgress: 1,
      curve: 'ease-out',
    },
  ],
};
