import type { TimelineExitCriteriaCoverage } from './types';
export const timelineExitCriteriaCoverage = [
  {
    gateId: 'P1_ARCHITECTURE_REGISTRY_COHERENT',
    criteria: ['gate ids, lane ownership, debt, retired paths, and test migrations resolve consistently'],
    evidence: [{ kind: 'test', path: 'tests/unit/timelineArchitectureRegistry.test.ts', note: 'registry coherence assertions' }],
  },
  {
    gateId: 'P1_KERNEL_IMPORT_BOUNDARY',
    criteria: ['src/timeline imports only kernel or runtime-free schema/type modules'],
    evidence: [{ kind: 'test', path: 'tests/unit/timelineArchitectureRegistry.test.ts', note: 'filesystem import scan' }],
  },
  {
    gateId: 'P1_LOC_BUDGET_ENFORCED',
    criteria: ['kernel files obey LOC budgets and forbidden god-object names are rejected'],
    evidence: [{ kind: 'test', path: 'tests/unit/timelineArchitectureRegistry.test.ts', note: 'line budget and name scan' }],
  },
  {
    gateId: 'P1_SCHEMA_RUNTIME_FREE_BOUNDARY',
    criteria: ['schema contracts contain no DOM, file, GPU, WebCodecs, URL, callback, or runtime-id handles'],
    evidence: [{ kind: 'test', path: 'tests/unit/timelineArchitectureRegistry.test.ts', note: 'schema contract token scan' }],
  },
  {
    gateId: 'P1_VISUAL_DEMAND_NAME_ISOLATED',
    criteria: ['kernel resource demand uses TimelineVisualResourceDemand, not service timelineVisualDemand'],
    evidence: [{ kind: 'test', path: 'tests/unit/timelineArchitectureRegistry.test.ts', note: 'visual demand isolation assertion' }],
  },
  {
    gateId: 'P1_HIGH_CONFLICT_OWNERSHIP_COMPLETE',
    criteria: ['every high-conflict file or glob has one active owning lane'],
    evidence: [{ kind: 'test', path: 'tests/unit/timelineArchitectureRegistry.test.ts', note: 'manifest ownership assertion' }],
  },
  {
    gateId: 'P1_TEST_AND_RETIRED_PATH_CLASSIFICATION',
    criteria: ['known affected tests and retired paths are classified before code movement'],
    evidence: [{ kind: 'test', path: 'tests/unit/timelineArchitectureRegistry.test.ts', note: 'ledger classification assertion' }],
  },
  {
    gateId: 'P2_TIMELINE_PROJECTION_ADOPTED',
    criteria: ['TimelineProjection owns semantic timeline data'],
    evidence: [{ kind: 'test', path: 'tests/unit/timelineRenderModel.test.ts', note: 'projection contract coverage imports from the kernel' }],
  },
  {
    gateId: 'P2_GEOMETRY_SNAPSHOT_ADOPTED',
    criteria: ['TimelineGeometrySnapshot owns spatial state and host geometry reads'],
    evidence: [
      { kind: 'test', path: 'tests/unit/timelineRenderModel.test.ts', note: 'geometry snapshot and rect helper coverage imports from the kernel' },
      { kind: 'test', path: 'tests/unit/TimelineTrack.test.tsx', note: 'TimelineTrack shell geometry consumes TimelineGeometrySnapshot clip bodies' },
      { kind: 'test', path: 'tests/unit/timelineArchitectureRegistry.test.ts; tests/unit/useMarqueeSelection.test.tsx', note: 'pointer and marquee clip/keyframe hit tests consume kernel geometry instead of local clip time-to-pixel fallbacks' },
    ],
  },
  {
    gateId: 'P2_VISIBLE_SET_SINGLE_SOURCE',
    criteria: ['demand, shell, and paint keys derive from one VisibleSet'],
    evidence: [{ kind: 'test', path: 'tests/unit/timelineProjectionGeometryBuilders.test.ts', note: 'single VisibleSet query returns clip, row, facet, and tile-band keys' }],
  },
  {
    gateId: 'P2_SCROLL_DOES_NOT_REBUILD_GEOMETRY',
    criteria: ['scroll affects visible-window queries and paint translation only'],
    evidence: [{ kind: 'test', path: 'tests/unit/timelineProjectionGeometryBuilders.test.ts', note: 'scroll changes visible membership while geometry epoch stays stable' }],
  },
  {
    gateId: 'P3_PAINT_PACKET_ADOPTED',
    criteria: ['canvas host consumes TimelinePaintPacket and resource tables directly'],
    evidence: [
      { kind: 'source', path: 'src/timeline/paint/TimelinePaintPacket.ts', note: 'runtime-free paint-packet contract' },
      { kind: 'test', path: 'tests/unit/timelinePaintPacketCoverage.test.ts', note: 'paint contract has no runtime value handles' },
      { kind: 'test', path: 'tests/unit/timelineClipCanvasWorkerModel.test.ts', note: 'worker draw messages carry paint packets, resource tables, and payload tables' },
      { kind: 'test', path: 'tests/unit/TimelineClipCanvasWorkerRuntime.test.tsx', note: 'runtime worker posts paint packets and payload tables without worker clip payload fields' },
      { kind: 'test', path: 'tests/unit/timelinePaintPacketCoverage.test.ts', note: 'worker draw model reads normalized paint clips instead of raw host clip source fields' },
      { kind: 'source', path: 'src/components/timeline/utils/timelineClipCanvasFadeResource.ts', note: 'fade worker resource contributor is separated from the canvas host adapter' },
      { kind: 'source', path: 'src/components/timeline/utils/timelineClipCanvasTrimResource.ts', note: 'trim worker resource contributor is separated from the canvas host adapter geometry resolver' },
      { kind: 'test', path: 'tests/unit/timelinePaintPacketCoverage.test.ts', note: 'passive decoration worker resource builder is kept outside the canvas host adapter' },
      { kind: 'source', path: 'src/components/timeline/utils/timelineClipCanvasCompositionResource.ts', note: 'composition visuals worker resource contributor is separated from the canvas host adapter' },
      { kind: 'test', path: 'tests/unit/timelinePaintPacketCoverage.test.ts', note: 'composition visuals worker resource builder is kept outside the canvas host adapter' },
      { kind: 'source', path: 'src/components/timeline/utils/timelineClipCanvasThumbnailResource.ts', note: 'thumbnail-strip worker resource contributor is separated from the canvas host adapter' },
      { kind: 'test', path: 'tests/unit/timelinePaintPacketCoverage.test.ts', note: 'thumbnail-strip worker resource builder is kept outside the canvas host adapter' },
      { kind: 'source', path: 'src/components/timeline/utils/timelineClipCanvasWaveformResource.ts', note: 'waveform worker resource contributor is separated from the canvas host adapter' },
      { kind: 'source', path: 'src/components/timeline/utils/timelineClipCanvasSpectrogramResource.ts', note: 'spectrogram worker resource contributor is separated from the canvas host adapter' },
      { kind: 'source', path: 'src/components/timeline/utils/timelineClipCanvasMidiResource.ts', note: 'MIDI preview worker resource contributor is separated from the canvas host adapter' },
      { kind: 'test', path: 'tests/unit/timelinePaintPacketCoverage.test.ts', note: 'audio and MIDI worker resource builders are kept outside the canvas host adapter' },
      { kind: 'source', path: 'src/components/timeline/utils/timelineClipCanvasPaintVisualContributors.ts', note: 'source-kind visual activation is registered as paint visual contributors' },
      { kind: 'test', path: 'tests/unit/timelinePaintPacketCoverage.test.ts', note: 'worker paint normalizer delegates source-kind visual activation to registered contributors' },
      { kind: 'source', path: 'src/components/timeline/utils/timelineClipCanvasPreparedResources.ts', note: 'prepared worker resource composer is separated from the canvas host adapter' },
      { kind: 'test', path: 'tests/unit/timelinePaintPacketCoverage.test.ts', note: 'prepared worker resource composition is kept outside the canvas host adapter' },
    ],
  },
  {
    gateId: 'P3_CANVAS_CLIP_FIELD_COVERAGE_GREEN',
    criteria: ['every former CanvasClip field maps to a paint-packet replacement or deletion'],
    evidence: [
      { kind: 'test', path: 'tests/unit/timelinePaintPacketCoverage.test.ts', note: 'TimelinePaintSourceClip field coverage matrix parses the live kernel paint source contract' },
      { kind: 'test', path: 'tests/unit/timelinePaintPacketCoverage.test.ts', note: 'runtime-only File handles are absent from the paint source contract' },
    ],
  },
  {
    gateId: 'P3_CANVAS_CLIP_DELETED',
    criteria: ['former CanvasClip host input adapters and tests are gone'],
    evidence: [{ kind: 'test', path: 'tests/unit/timelinePaintPacketCoverage.test.ts', note: 'TimelineClipCanvasInputClip host bridge is absent from TimelineClipCanvas' }],
  },
  {
    gateId: 'P3_INTERACTION_SHELL_CALLBACKS_NARROW',
    criteria: ['interaction shell receives command descriptors instead of store-shaped callback bags'],
    evidence: [
      { kind: 'source', path: 'src/components/timeline/interactionShell/types.ts', note: 'module command descriptor contract' },
      { kind: 'source', path: 'src/components/timeline/interactionShell/ClipVideoBakeControls.tsx', note: 'video-bake module dispatches command descriptors instead of importing the timeline store' },
      { kind: 'source', path: 'src/components/timeline/interactionShell/ClipStemControls.tsx', note: 'stem module dispatches command descriptors instead of importing timeline or media stores' },
      { kind: 'source', path: 'src/components/timeline/interactionShell/ClipSpectralRegionControls.tsx', note: 'spectral-region module dispatches command descriptors instead of importing timeline or media stores' },
      { kind: 'source', path: 'src/components/timeline/interactionShell/ClipAudioRegionControls.tsx', note: 'audio-region module dispatches command descriptors instead of importing the timeline store' },
      { kind: 'test', path: 'tests/unit/ClipInteractionShell.contract.test.tsx', note: 'video-bake shell controls route through module command descriptors' },
      { kind: 'test', path: 'tests/unit/ClipInteractionShell.contract.test.tsx', note: 'stem shell controls route through module command descriptors' },
      { kind: 'test', path: 'tests/unit/ClipInteractionShell.contract.test.tsx', note: 'spectral-region shell controls route through module command descriptors' },
      { kind: 'test', path: 'tests/unit/ClipInteractionShell.contract.test.tsx', note: 'audio-region shell controls route through module command descriptors' },
    ],
  },
  {
    gateId: 'P4_RUNTIME_PROVIDER_DEMAND_ADOPTED',
    criteria: ['runtime leases originate from RuntimeProviderDemand'],
    evidence: [
      { kind: 'source', path: 'src/timeline/resources/TimelineVisualResourceDemand.ts', note: 'kernel RuntimeProviderDemand carries policy, lease, owner, source, and dimensions as plain data' },
      { kind: 'source', path: 'src/services/timeline/runtimeProviderDemandBridge.ts', note: 'service bridge converts RuntimeProviderDemand records into coordinator render resource leases' },
      { kind: 'source', path: 'src/services/timeline/lazyMediaElements.ts', note: 'primary lazy media admission and retain descriptors originate from RuntimeProviderDemand records' },
      { kind: 'source', path: 'src/services/timeline/lazyImageElements.ts', note: 'primary lazy image admission and retain descriptors originate from RuntimeProviderDemand records' },
      { kind: 'source', path: 'src/services/timeline/thumbnailRuntimeReporting.ts', note: 'thumbnail jobs, detached generation media, canvas, and bitmap resources originate from RuntimeProviderDemand records' },
      { kind: 'source', path: 'src/services/timeline/runtimeResourceReporting.ts', note: 'clip reservation records and live clip runtime reports originate from RuntimeProviderDemand records before coordinator admission' },
      { kind: 'source', path: 'src/services/timeline/renderTargetRuntimeReporting.ts', note: 'render-target canvas runtime resources originate from RuntimeProviderDemand records' },
      { kind: 'source', path: 'src/services/timeline/compositionRenderRuntimeReporting.ts', note: 'composition render runtime-binding, media, image, and text resources originate from RuntimeProviderDemand records' },
      { kind: 'source', path: 'src/services/timeline/ramPreviewRuntimeReporting.ts', note: 'RAM preview jobs, source resources, image admission, CPU composite cache, and GPU frame cache resources originate from RuntimeProviderDemand records' },
      { kind: 'source', path: 'src/services/timeline/exportRuntimeReporting.ts', note: 'export jobs, surfaces, clip resources, parallel decode resources, audio buffers, and preview frames originate from RuntimeProviderDemand records' },
      { kind: 'source', path: 'src/services/videoBakeProxyCache.ts', note: 'video bake proxy HTML media resources originate from RuntimeProviderDemand records' },
      { kind: 'source', path: 'src/services/timeline/compositionAudioMixdownCache.ts', note: 'composition audio mixdown cache runtime bindings and playback audio elements originate from RuntimeProviderDemand records' },
      { kind: 'source', path: 'src/services/vectorAnimation/vectorRuntimeReporting.ts', note: 'vector animation runtime canvas resources originate from RuntimeProviderDemand records' },
      { kind: 'source', path: 'src/engine/texture/ScrubbingCache.ts', note: 'background scrub preload video resources originate from RuntimeProviderDemand records' },
      { kind: 'source', path: 'src/services/nodeGraph/aiNodeRuntime.ts', note: 'AI node runtime source/output canvas resources originate from RuntimeProviderDemand records' },
      { kind: 'source', path: 'src/services/mediaRuntime/runtimePlayback.ts', note: 'runtime playback provider admission resources originate from RuntimeProviderDemand records' },
      { kind: 'source', path: 'src/services/layerBuilder/AudioTrackSyncManager.ts', note: 'audio proxy, stem preview, and stem buffer runtime resources originate from RuntimeProviderDemand records' },
      { kind: 'source', path: 'src/services/timeline/imageRuntimeHydrator.ts', note: 'image hydration can reserve image-canvas resources from RuntimeProviderDemand records' },
      { kind: 'source', path: 'src/services/slotDeckManager.ts', note: 'slot deck media and image hydration resources originate from RuntimeProviderDemand records' },
      { kind: 'source', path: 'src/services/layerPlaybackManager.ts', note: 'background layer media and image hydration resources originate from RuntimeProviderDemand records' },
      { kind: 'source', path: 'src/services/compositionRenderer.ts', note: 'composition render media and image hydration resources originate from RuntimeProviderDemand records' },
      { kind: 'source', path: 'src/services/proxyFrameCache.ts', note: 'proxy frame, audio buffer, audio element, and WebCodecs frame cache resources originate from RuntimeProviderDemand records' },
      { kind: 'source', path: 'src/stores/timeline/helpers/webCodecsHelpers.ts', note: 'timeline helper WebCodecs provider admission resources originate from RuntimeProviderDemand records' },
      { kind: 'test', path: 'tests/unit/timelineRuntimeCoordinatorContracts.test.ts', note: 'kernel RuntimeProviderDemand categories align with service runtime policies and resource kinds' },
      { kind: 'test', path: 'tests/unit/timelineRuntimeCoordinatorContracts.test.ts', note: 'demand-derived render resources can be reserved and released through the runtime coordinator' },
      { kind: 'test', path: 'tests/unit/timelineRuntimeCoordinatorContracts.test.ts', note: 'clip reservation and live runtime resources carry demand tags and release through the coordinator' },
      { kind: 'test', path: 'tests/unit/lazyMediaElements.test.ts', note: 'lazy media coordinator resources carry demand lease tags and retain/release behavior remains stable' },
      { kind: 'test', path: 'tests/unit/lazyMediaElements.test.ts', note: 'lazy image coordinator resources carry demand lease tags and retain/release behavior remains stable' },
      { kind: 'test', path: 'tests/unit/thumbnailBitmapCache.test.ts', note: 'thumbnail decode jobs and bitmap resources carry demand lease tags' },
      { kind: 'test', path: 'tests/unit/thumbnailCacheService.test.ts', note: 'thumbnail generation job/video resources carry demand lease tags' },
      { kind: 'test', path: 'tests/unit/renderTargetStoreRuntimeReporting.test.ts', note: 'render-target canvas resources carry demand lease tags and release by owner' },
      { kind: 'test', path: 'tests/unit/compositionRendererRuntimeReporting.test.ts', note: 'composition render resources carry demand lease tags and release by composition owner' },
      { kind: 'test', path: 'tests/unit/ramPreviewRuntimeReporting.test.ts', note: 'RAM preview job/source/image/cache resources carry demand lease tags and retain/release behavior remains stable' },
      { kind: 'test', path: 'tests/unit/exportRuntimeReporting.test.ts', note: 'export coordinator resources carry demand lease tags and retain/release behavior remains stable' },
      { kind: 'test', path: 'tests/unit/audioExportPipeline.test.ts', note: 'export audio buffers carry demand lease tags while preserving active-run reporting behavior' },
      { kind: 'test', path: 'tests/unit/videoBakeProxyCache.test.ts', note: 'video bake proxy resources carry demand lease tags and release on removal' },
      { kind: 'test', path: 'tests/unit/compositionAudioMixdownCache.test.ts', note: 'composition audio mixdown cache and playback resources carry demand lease tags and retain/release behavior remains stable' },
      { kind: 'test', path: 'tests/unit/vectorRuntimeReporting.test.ts', note: 'vector runtime canvas resources carry demand lease tags and retain/release behavior remains stable' },
      { kind: 'test', path: 'tests/unit/scrubbingCache.test.ts', note: 'background scrub preload resources carry demand lease tags and release on source clear' },
      { kind: 'test', path: 'tests/unit/aiNodeRuntime.test.ts', note: 'AI node runtime canvas resources carry demand lease tags and retain/release behavior remains stable' },
      { kind: 'test', path: 'tests/unit/mediaRuntime.test.ts', note: 'runtime playback provider resources carry demand lease tags and release with runtime sessions' },
      { kind: 'test', path: 'tests/unit/audioScrubSync.test.ts', note: 'AudioTrackSyncManager runtime resources carry demand lease tags and retain/release behavior remains stable' },
      { kind: 'test', path: 'tests/unit/slotDeckManager.test.ts', note: 'slot deck warm media and image hydration resources carry demand lease tags and release on disposal' },
      { kind: 'test', path: 'tests/unit/layerPlaybackManagerWarmDeck.test.ts', note: 'background layer cold media and image hydration resources carry demand lease tags and release on deactivate' },
      { kind: 'test', path: 'tests/unit/compositionRendererRuntimeReporting.test.ts', note: 'composition render image hydration resources carry demand lease tags before live source reporting replaces them' },
      { kind: 'test', path: 'tests/unit/proxyFrameCache.test.ts', note: 'proxy cache JPEG, decoded audio, audio proxy, and VideoFrame resources carry demand lease tags and retain/release behavior remains stable' },
      { kind: 'test', path: 'tests/unit/webCodecsHelpers.test.ts', note: 'timeline helper WebCodecs provider resources carry demand lease tags and release when the player is destroyed' },
      { kind: 'test', path: 'tests/unit/timelineArchitectureRegistry.test.ts', note: 'kernel resource demand contracts remain runtime-handle-free' },
    ],
  },
  {
    gateId: 'P4_VIDEO_SYNC_SOURCE_HANDLES_REMOVED',
    criteria: ['VideoSyncManager does not read timeline source handles'],
    evidence: [
      { kind: 'source', path: 'src/services/timeline/nativeDecoderRuntimeRegistry.ts', note: 'native decoder handles are service-owned runtime resources registered through RuntimeProviderDemand leases' },
      { kind: 'source', path: 'src/services/layerBuilder/videoSyncMediaResolver.ts', note: 'Video sync media resolution centralizes runtime providers, runtime-owned native decoders, and service-owned lazy video leases' },
      { kind: 'source', path: 'src/services/layerBuilder/{videoSyncFullWebCodecsCoordinator.ts,videoSyncHtmlClipCoordinator.ts,videoSyncHtmlSeekCoordinator.ts,videoSyncNestedCompositionCoordinator.ts,videoSyncRecoveryCoordinator.ts,videoSyncWarmupCoordinator.ts}', note: 'Full WebCodecs, HTML clip/seek, nested composition, recovery, and warmup orchestration are isolated from VideoSyncManager behind resolver-fed runtime providers and focused state owners' },
      { kind: 'source', path: 'src/services/timeline/lazyMediaElements.ts', note: 'lazy video lookup API returns service-owned RuntimeProviderDemand-backed video elements for sync resolvers' },
      { kind: 'test', path: 'tests/unit/timelineArchitectureRegistry.test.ts', note: 'VideoSyncManager and videoSyncMediaResolver no longer read WebCodecs, HTML video, or native decoder source handles directly' },
      { kind: 'test', path: 'tests/unit/lazyMediaElements.test.ts', note: 'lazy media lookup APIs return and release the service-owned audio/video elements used by sync resolvers' },
    ],
  },
  {
    gateId: 'P4_AUDIO_SYNC_SOURCE_HANDLES_REMOVED',
    criteria: ['AudioTrackSyncManager does not read timeline source handles'],
    evidence: [
      { kind: 'source', path: 'src/services/layerBuilder/audioSyncMediaResolver.ts', note: 'Audio sync media resolution reads service-owned lazy media records instead of timeline source HTML handles' },
      { kind: 'source', path: 'src/services/timeline/lazyMediaElements.ts', note: 'primary lazy audio/video elements are service-owned RuntimeProviderDemand leases with explicit lookup APIs for sync resolvers' },
      { kind: 'test', path: 'tests/unit/timelineArchitectureRegistry.test.ts', note: 'AudioTrackSyncManager and audioSyncMediaResolver no longer read HTML audio/video source handles directly' },
      { kind: 'test', path: 'tests/unit/lazyMediaElements.test.ts', note: 'lazy media lookup APIs return and release the service-owned audio/video elements used by audio sync' },
    ],
  },
  {
    gateId: 'P4_TIMELINE_STATE_RUNTIME_HANDLES_REMOVED',
    criteria: ['timeline store state persists data-only descriptors'],
    evidence: [
      { kind: 'source', path: 'src/stores/timeline/sourceRuntimeSanitizer.ts', note: 'store/importer boundary sanitizer strips timeline source runtime handles for persistence and copy/clone paths' },
      { kind: 'source', path: 'src/stores/timeline/editOperations/splitBatchOperations.ts', note: 'split media source cloning strips DOM, WebCodecs, native decoder, runtime binding, and source File handles' },
      { kind: 'source', path: 'src/stores/timeline/clip/addVideoClip.ts', note: 'native decoder import path stores only data descriptors in clip source and registers decoder handles in a runtime registry' },
      { kind: 'source', path: 'src/stores/timeline/clip/upgradeToNativeDecoder.ts', note: 'native decoder auto-upgrade path registers decoder handles outside timeline state and strips legacy source handles on downgrade' },
      { kind: 'source', path: 'src/types/timeline.ts', note: 'TimelineClipDataSource is separated from explicit TimelineClipSourceRuntimeHandles for the remaining legacy runtime extension surface (moved out of the types barrel by packet 159)' },
      { kind: 'source', path: 'src/services/timeline/timelineClipSourceRuntimeCleanup.ts', note: 'legacy source handle release is owned by a timeline runtime service instead of store serialization/delete modules' },
      { kind: 'source', path: 'src/services/timeline/timelineGeneratedCanvasRuntime.ts', note: 'text, solid, and math-scene canvas runtime creation and update rendering are owned by a timeline runtime service instead of store restore/clipboard/update modules' },
      { kind: 'source', path: 'src/services/timeline/timelineMediaSourceRuntimeRestore.ts', note: 'clipboard media reload source patches, load-state media file/object-url references, and load-state image/deferred-media/native-video/vector/spatial source patch orchestration are owned by a timeline runtime restore service' },
      { kind: 'source', path: 'src/services/timeline/timelineProxyCacheRuntime.ts', note: 'proxy cache warmup and scrub-cache store paths resolve legacy HTML video handles through a timeline runtime service' },
      { kind: 'source', path: 'src/services/timeline/timelineStemSourceRuntime.ts', note: 'stem source replacement resolves and disposes legacy audio elements through a timeline runtime service' },
      { kind: 'source', path: 'src/services/timeline/timelinePlaybackWarmupRuntime.ts', note: 'playback start warmup resolves legacy HTML video readiness through a timeline runtime service' },
      { kind: 'source', path: 'src/services/timeline/timelineNestedCompositionThumbnailRuntime.ts', note: 'nested composition segment and fallback thumbnail paths resolve legacy video image and canvas handles through a timeline runtime service' },
      { kind: 'source', path: 'src/services/audio/audioClipResolution.ts', note: 'stem source identity owns legacy source File fallback instead of timeline store helpers reading runtime source fields' },
      { kind: 'test', path: 'tests/unit/timelineSourceRuntimeSanitizer.test.ts', note: 'serializable state and clipboard data are built from data-only source metadata without runtime source keys' },
      { kind: 'test', path: 'tests/unit/timelineArchitectureRegistry.test.ts', note: 'TimelineClipDataSource has no runtime handle properties, sanitizer output is typed as data-only source metadata, and the timeline store has no direct source runtime-handle reads' },
      { kind: 'test', path: 'tests/unit/timelineSourceRuntimeCleanup.test.ts', note: 'legacy media elements, WebCodecs players, and vector runtimes release through the runtime cleanup service' },
      { kind: 'test', path: 'tests/unit/timelineGeneratedCanvasRuntime.test.ts', note: 'generated text, solid, and math-scene canvases are created, resolved, and updated through a timeline runtime service' },
      { kind: 'test', path: 'tests/unit/timelineMediaSourceRuntimeRestore.test.ts', note: 'media runtime restore service keeps video/audio/vector data-only and owns image/model plus load-state object URL/reference, vector starter, spatial patch, and source patch policy' },
      { kind: 'test', path: 'tests/unit/timelineProxyCacheRuntime.test.ts', note: 'proxy cache runtime service covers scrub-cache source resolution and recursive warmup video collection' },
      { kind: 'test', path: 'tests/unit/timelineStemSourceRuntime.test.ts', note: 'stem source runtime service covers legacy audio element lookup, route disposal, and master-audio cleanup' },
      { kind: 'test', path: 'tests/unit/timelinePlaybackWarmupRuntime.test.ts', note: 'playback warmup runtime service covers HTML fallback, runtime provider full-mode, legacy WebCodecs full-mode, and non-video sources' },
      { kind: 'test', path: 'tests/unit/timelineNestedCompositionThumbnailRuntime.test.ts', note: 'nested composition thumbnail runtime service covers segment video image canvas vector and fallback video thumbnail paths' },
      { kind: 'test', path: 'tests/stores/timeline/clipSlice.test.ts', note: 'split linked media clips do not carry runtime source handles into split parts' },
      { kind: 'test', path: 'tests/unit/timelineEditOperations.test.ts', note: 'bulk split edit operation does not carry runtime source handles into split parts' },
      { kind: 'test', path: 'tests/stores/timeline/stemSharingHelpers.test.ts', note: 'stem sharing covers media id matching, top-level file key matching, and legacy source file key matching through the audio source identity service' },
    ],
  },
  {
    gateId: 'P4_STORE_SLICE_GOD_FILES_SPLIT',
    criteria: ['clip, keyframe, track, and edit-operation files meet split targets or carry no unresolved overage debt'],
    evidence: [
      { kind: 'source', path: 'src/stores/timeline/{clipSlice,keyframeSlice,trackSlice,stemSeparationSlice,clipboardSlice,nestedCompositionLoader,serializationUtils,types,audioEditSlice}.ts; src/stores/timeline/editOperations/{moveResolution,applyTimelineEditOperation}.ts', note: 'clip keyframe track stem clipboard nested-composition serialization type-facade audio-edit move-resolver and edit-applier modules compose focused helpers and stay under 700 LOC targets' },
      { kind: 'source', path: 'src/stores/timeline/{clip,keyframes,tracks,stems,clipboard,nestedComposition,serialization,storeTypes,audioEdit}/**; src/stores/timeline/editOperations/{moveLeadResolution,moveTrackCompatibility,editOperationResults,fadeKeyframePlan,fadeTransactionOperations,keyframeTransactionHelpers,keyframeTransactionOperations,keyboardEditCommandOperations,resolvedMoveApplyOperation}.ts', note: 'store helper and edit transaction handler modules stay under focused module budgets' },
      { kind: 'source', path: 'src/stores/timeline/editOperations/{moveLeadResolution,moveTrackCompatibility}.ts', note: 'lead move snap resistance fallback and track-compatibility helpers stay under focused module budgets' },
      { kind: 'test', path: 'tests/unit/timelineArchitectureRegistry.test.ts', note: 'architecture guard keeps store helpers and edit transaction handlers split out and enforces line budgets' },
      { kind: 'test', path: 'tests/stores/timeline/**; tests/unit/timelineEditOperations.test.ts', note: 'store and edit-operation behavior remains covered after helper extraction' },
    ],
  },
  {
    gateId: 'P4_EDIT_OPERATION_APPLIER_NARROW',
    criteria: ['edit applier delegates through narrow planners'],
    evidence: [{ kind: 'test', path: 'tests/unit/timelineArchitectureRegistry.test.ts; tests/unit/timelineEditOperations.test.ts', note: 'architecture and behavior coverage keep edit result, fade, keyframe, keyboard, and resolved-move handlers split out of the applier under LOC budgets' }],
  },
  {
    gateId: 'P4_IMPORTER_LEGACY_QUARANTINE',
    criteria: ['old project compatibility is isolated at import boundaries'],
    evidence: [{ kind: 'test', path: 'src/stores/timeline/serialization/{loadStateMediaClipRestore,loadStateCompositionClipRestore,loadStateGeneratedClipRestore,loadStateStoryboardClipRestore}.ts; src/services/timeline/timelineMediaSourceRuntimeRestore.ts; tests/unit/timelineArchitectureRegistry.test.ts; tests/unit/timelineMediaSourceRuntimeRestore.test.ts', note: 'old-project load-state media, composition, generated, storyboard, vector, spatial, and object-url compatibility is quarantined in importer helpers and timeline runtime services' }],
  },
  {
    gateId: 'P4_SERIALIZATION_RUNTIME_FREE_EDITOR_PATH',
    criteria: ['editor save/load paths do not recreate runtime-bearing source shapes'],
    evidence: [
      { kind: 'source', path: 'src/stores/timeline/sourceRuntimeSanitizer.ts', note: 'serialization path reads sanitized timeline source metadata before creating SerializableClip data' },
      { kind: 'source', path: 'src/services/timeline/timelineClipSourceRuntimeCleanup.ts', note: 'clearTimeline delegates legacy source runtime release instead of reading runtime-bearing source fields inline' },
      { kind: 'source', path: 'src/services/timeline/timelineGeneratedCanvasRuntime.ts', note: 'restore, clipboard paste, and store update paths delegate generated canvas runtime work for text, solid, and math-scene clips' },
      { kind: 'source', path: 'src/services/timeline/timelineMediaSourceRuntimeRestore.ts', note: 'clipboard paste and load-state restore delegate media source rehydration, object URL policy, NativeHelper file references, vector/spatial orchestration, and source patch construction to a service' },
      { kind: 'test', path: 'tests/unit/timelineSourceRuntimeSanitizer.test.ts', note: 'getSerializableState excludes timeline source runtime keys from serialized output' },
      { kind: 'test', path: 'tests/unit/timelineSourceRuntimeCleanup.test.ts', note: 'clear/delete cleanup service coverage for runtime source media, WebCodecs, and vector handles' },
      { kind: 'test', path: 'tests/unit/timelineGeneratedCanvasRuntime.test.ts', note: 'generated canvas service coverage for text, solid, and math-scene runtime canvas creation, resolution, and updates' },
      { kind: 'test', path: 'tests/unit/timelineMediaSourceRuntimeRestore.test.ts', note: 'media restore service coverage for clipboard reload patches, load-state object URL/reference resolution, vector starter, spatial patch, and load-state source patch builders' },
      { kind: 'test', path: 'tests/unit/timelineArchitectureRegistry.test.ts; tests/unit/timelineMediaSourceRuntimeRestore.test.ts; tests/unit/timelineSourceRuntimeSanitizer.test.ts; tests/unit/serializationNestedRestore.test.ts', note: 'serializationUtils remains orchestration-only while importer and service tests cover data-only save output and load-state restore compatibility' },
    ],
  },
  {
    gateId: 'P4_DROP_IMPORT_COMMANDS_ROUTED',
    criteria: ['external drop uses command planning and importer services'],
    evidence: [
      { kind: 'source', path: 'src/timeline/commands/TimelineExternalDropCommand.ts', note: 'external drop MIME payloads are classified into data-only command descriptors with track compatibility checks' },
      { kind: 'source', path: 'src/services/timeline/timelineExternalDropCommandExecutor.ts', note: 'panel item and media-file drop command execution is isolated outside the React drop hook behind injected timeline actions' },
      { kind: 'source', path: 'src/services/timeline/timelineExternalDropFilePlacement.ts', note: 'external file drop sequencing, import resolution, media type policy, and clip creation are isolated outside the React drop hook behind injected timeline actions' },
      { kind: 'source', path: 'src/services/timeline/timelineExternalDropMediaResolver.ts', note: 'timeline drop media import, lazy 3D placeholders, and NativeHelper file resolution are isolated outside the React drop hook' },
      { kind: 'source', path: 'src/components/timeline/hooks/useExternalDrop.ts', note: 'track and new-track drop commit paths route through the external drop command planner, executor, and file placement service' },
      { kind: 'test', path: 'tests/unit/timelineExternalDropCommand.test.ts', note: 'drop command planner covers panel item, media file, external file, and track compatibility routing' },
      { kind: 'test', path: 'tests/unit/timelineExternalDropCommandExecutor.test.ts', note: 'drop command executor covers visual panel actions, media-file execution, and strict track-type rejection' },
      { kind: 'test', path: 'tests/unit/timelineExternalDropFilePlacement.test.ts', note: 'external file placement covers sequential placement, track-kind rejection, and media override propagation' },
      { kind: 'test', path: 'tests/unit/timelineExternalDropMediaResolver.test.ts', note: 'drop media resolver covers media type overrides, path tagging, lazy 3D placeholders, and resolved files' },
      { kind: 'test', path: 'tests/unit/timelineArchitectureRegistry.test.ts', note: 'architecture guard requires external drop command planning to stay wired into the hook' },
    ],
  },
  {
    gateId: 'P4_RUNTIME_RESOURCE_TESTS_KEPT_OUT_OF_KERNEL',
    criteria: ['runtime resources are tested in services/stores, not kernel contracts'],
    evidence: [{ kind: 'test', path: 'tests/unit/mediaObjectUrlManager.test.ts; tests/unit/timelineRuntimeCoordinatorContracts.test.ts; tests/unit/timelineArchitectureRegistry.test.ts', note: 'object-url, RuntimeProviderDemand coordinator, and registry guards keep runtime-resource behavior in service/store tests outside the kernel' }],
  },
  {
    gateId: 'P5_TEST_MIGRATION_COMPLETE',
    criteria: ['test migration ledger has no unresolved port, replace, split, or delete entries'],
    evidence: [{ kind: 'source', path: 'src/timeline/architecture/testMigrationLedger.ts', note: 'final ledger state' }],
  },
  {
    gateId: 'P5_RETIRED_PATHS_DELETED',
    criteria: ['retired path ledger has no unresolved delete-at-gate entries'],
    evidence: [{ kind: 'source', path: 'src/timeline/architecture/retiredPathLedger.ts', note: 'final retired-path state' }],
  },
  {
    gateId: 'P5_DOCS_HANDOFF_COMPLETE',
    criteria: ['handoff, feature docs, and plan reflect shipped architecture'],
    evidence: [{ kind: 'handoff', path: 'docs/completed/architecture/Timeline-System-Refactor-Handoff.md', note: 'final handoff entry' }],
  },
  { gateId: 'P5_FULL_CHECK_CHAIN_GREEN',
    criteria: ['npm run build, npm run lint, and npm run test pass on final HEAD'],
    evidence: [{ kind: 'manual-check', path: 'package.json', note: 'final full check chain' }],
  },
] as const satisfies readonly TimelineExitCriteriaCoverage[];
