import type { TimelineArchitectureGate } from './types';

export const timelineArchitectureGates = [
  {
    id: 'P1_ARCHITECTURE_REGISTRY_COHERENT',
    phase: 'P1',
    title: 'Architecture registry coherence is executable',
    status: 'active',
  },
  {
    id: 'P1_KERNEL_IMPORT_BOUNDARY',
    phase: 'P1',
    title: 'Kernel imports stay pure and runtime-free',
    status: 'satisfied',
    dependsOn: ['P1_ARCHITECTURE_REGISTRY_COHERENT'],
  },
  {
    id: 'P1_LOC_BUDGET_ENFORCED',
    phase: 'P1',
    title: 'No-god-object budgets and forbidden names are enforced',
    status: 'satisfied',
    dependsOn: ['P1_ARCHITECTURE_REGISTRY_COHERENT'],
  },
  {
    id: 'P1_SCHEMA_RUNTIME_FREE_BOUNDARY',
    phase: 'P1',
    title: 'Timeline schema inputs exclude runtime handles',
    status: 'satisfied',
    dependsOn: ['P1_KERNEL_IMPORT_BOUNDARY'],
  },
  {
    id: 'P1_VISUAL_DEMAND_NAME_ISOLATED',
    phase: 'P1',
    title: 'Kernel visual resource demand is isolated from service gating',
    status: 'satisfied',
    dependsOn: ['P1_KERNEL_IMPORT_BOUNDARY'],
  },
  {
    id: 'P1_HIGH_CONFLICT_OWNERSHIP_COMPLETE',
    phase: 'P1',
    title: 'High-conflict timeline files have one active owner',
    status: 'satisfied',
    dependsOn: ['P1_ARCHITECTURE_REGISTRY_COHERENT'],
  },
  {
    id: 'P1_TEST_AND_RETIRED_PATH_CLASSIFICATION',
    phase: 'P1',
    title: 'Affected tests and retired paths are classified',
    status: 'satisfied',
    dependsOn: ['P1_ARCHITECTURE_REGISTRY_COHERENT'],
  },
  {
    id: 'P2_TIMELINE_PROJECTION_ADOPTED',
    phase: 'P2',
    title: 'TimelineProjection becomes the semantic timeline model',
    status: 'satisfied',
    dependsOn: ['P1_SCHEMA_RUNTIME_FREE_BOUNDARY'],
  },
  {
    id: 'P2_GEOMETRY_SNAPSHOT_ADOPTED',
    phase: 'P2',
    title: 'TimelineGeometrySnapshot owns geometry and hit-test data',
    status: 'satisfied',
    dependsOn: ['P2_TIMELINE_PROJECTION_ADOPTED'],
  },
  {
    id: 'P2_VISIBLE_SET_SINGLE_SOURCE',
    phase: 'P2',
    title: 'VisibleSet is the only membership query for timeline hosts',
    status: 'satisfied',
    dependsOn: ['P2_GEOMETRY_SNAPSHOT_ADOPTED'],
  },
  {
    id: 'P2_SCROLL_DOES_NOT_REBUILD_GEOMETRY',
    phase: 'P2',
    title: 'Scroll changes only visible-window queries and paint translation',
    status: 'satisfied',
    dependsOn: ['P2_GEOMETRY_SNAPSHOT_ADOPTED'],
  },
  {
    id: 'P3_PAINT_PACKET_ADOPTED',
    phase: 'P3',
    title: 'Canvas host consumes TimelinePaintPacket directly',
    status: 'satisfied',
    dependsOn: ['P2_VISIBLE_SET_SINGLE_SOURCE'],
  },
  {
    id: 'P3_CANVAS_CLIP_FIELD_COVERAGE_GREEN',
    phase: 'P3',
    title: 'CanvasClip field coverage has paint-packet replacements',
    status: 'satisfied',
    dependsOn: ['P3_PAINT_PACKET_ADOPTED'],
  },
  {
    id: 'P3_CANVAS_CLIP_DELETED',
    phase: 'P3',
    title: 'Transitional CanvasClip bridge is removed',
    status: 'satisfied',
    dependsOn: ['P3_CANVAS_CLIP_FIELD_COVERAGE_GREEN'],
  },
  {
    id: 'P3_INTERACTION_SHELL_CALLBACKS_NARROW',
    phase: 'P3',
    title: 'Interaction shell uses narrow command descriptors',
    status: 'satisfied',
    dependsOn: ['P3_PAINT_PACKET_ADOPTED'],
  },
  {
    id: 'P4_RUNTIME_PROVIDER_DEMAND_ADOPTED',
    phase: 'P4',
    title: 'Runtime allocation flows through RuntimeProviderDemand',
    status: 'satisfied',
    dependsOn: ['P3_CANVAS_CLIP_DELETED'],
  },
  {
    id: 'P4_VIDEO_SYNC_SOURCE_HANDLES_REMOVED',
    phase: 'P4',
    title: 'VideoSyncManager no longer reads timeline source handles',
    status: 'satisfied',
    dependsOn: ['P4_RUNTIME_PROVIDER_DEMAND_ADOPTED'],
  },
  {
    id: 'P4_AUDIO_SYNC_SOURCE_HANDLES_REMOVED',
    phase: 'P4',
    title: 'AudioTrackSyncManager no longer reads timeline source handles',
    status: 'satisfied',
    dependsOn: ['P4_RUNTIME_PROVIDER_DEMAND_ADOPTED'],
  },
  {
    id: 'P4_TIMELINE_STATE_RUNTIME_HANDLES_REMOVED',
    phase: 'P4',
    title: 'Timeline store state is runtime-handle-free',
    status: 'satisfied',
    dependsOn: [
      'P4_VIDEO_SYNC_SOURCE_HANDLES_REMOVED',
      'P4_AUDIO_SYNC_SOURCE_HANDLES_REMOVED',
    ],
  },
  {
    id: 'P4_STORE_SLICE_GOD_FILES_SPLIT',
    phase: 'P4',
    title: 'Timeline store god files are split by owned behavior',
    status: 'satisfied',
    dependsOn: ['P4_TIMELINE_STATE_RUNTIME_HANDLES_REMOVED'],
  },
  {
    id: 'P4_EDIT_OPERATION_APPLIER_NARROW',
    phase: 'P4',
    title: 'Edit operation applier delegates through narrow planners',
    status: 'satisfied',
    dependsOn: ['P4_STORE_SLICE_GOD_FILES_SPLIT'],
  },
  {
    id: 'P4_IMPORTER_LEGACY_QUARANTINE',
    phase: 'P4',
    title: 'Old project compatibility is isolated at import boundaries',
    status: 'satisfied',
    dependsOn: ['P4_TIMELINE_STATE_RUNTIME_HANDLES_REMOVED'],
  },
  {
    id: 'P4_SERIALIZATION_RUNTIME_FREE_EDITOR_PATH',
    phase: 'P4',
    title: 'Editor serialization path persists data-only descriptors',
    status: 'satisfied',
    dependsOn: ['P4_IMPORTER_LEGACY_QUARANTINE'],
  },
  {
    id: 'P4_DROP_IMPORT_COMMANDS_ROUTED',
    phase: 'P4',
    title: 'External drop routes through command planning and import services',
    status: 'satisfied',
    dependsOn: ['P4_IMPORTER_LEGACY_QUARANTINE'],
  },
  {
    id: 'P4_RUNTIME_RESOURCE_TESTS_KEPT_OUT_OF_KERNEL',
    phase: 'P4',
    title: 'Runtime resource tests assert services, not kernel handles',
    status: 'satisfied',
    dependsOn: ['P4_RUNTIME_PROVIDER_DEMAND_ADOPTED'],
  },
  {
    id: 'P5_TEST_MIGRATION_COMPLETE',
    phase: 'P5',
    title: 'Timeline tests are ported, replaced, split, deleted, or kept',
    status: 'satisfied',
    dependsOn: ['P4_RUNTIME_RESOURCE_TESTS_KEPT_OUT_OF_KERNEL'],
  },
  {
    id: 'P5_RETIRED_PATHS_DELETED',
    phase: 'P5',
    title: 'Retired timeline paths are deleted or quarantined',
    status: 'satisfied',
    dependsOn: ['P5_TEST_MIGRATION_COMPLETE'],
  },
  {
    id: 'P5_DOCS_HANDOFF_COMPLETE',
    phase: 'P5',
    title: 'Plan, feature docs, and handoff match the final architecture',
    status: 'satisfied',
    dependsOn: ['P5_RETIRED_PATHS_DELETED'],
  },
  {
    id: 'P5_FULL_CHECK_CHAIN_GREEN',
    phase: 'P5',
    title: 'Final build, lint, and test checks are green',
    status: 'satisfied',
    dependsOn: ['P5_DOCS_HANDOFF_COMPLETE'],
  },
] as const satisfies readonly TimelineArchitectureGate[];

export const timelineArchitectureGateIds = timelineArchitectureGates.map(
  (gate) => gate.id,
);
