import type {
  TimelineHighConflictOwnership,
  TimelineRefactorLane,
} from './types';

export const timelineHighConflictTargets = [
  'src/components/timeline/Timeline.tsx',
  'src/components/timeline/TimelineTrack.tsx',
  'src/components/timeline/TimelineClipCanvas.tsx',
  'src/components/timeline/types.ts',
  'src/components/timeline/hooks/useExternalDrop.ts',
  'src/stores/timeline/clipSlice.ts',
  'src/stores/timeline/keyframeSlice.ts',
  'src/stores/timeline/editOperations/**',
  'src/stores/timeline/trackSlice.ts',
  'src/stores/timeline/helpers/blobUrlManager.ts',
  'src/services/layerBuilder/VideoSyncManager.ts',
  'src/services/layerBuilder/AudioTrackSyncManager.ts',
] as const;

export const timelineRefactorLanes = [
  {
    id: 'architecture',
    name: 'Architecture Registry',
    owner: 'Codex',
    status: 'done',
    writeSet: [
      'src/timeline/architecture/**',
      'src/timeline/contracts/schema/**',
      'tests/unit/timelineArchitectureRegistry.test.ts',
      'docs/completed/architecture/Timeline-System-Refactor-Handoff.md',
    ],
    forbiddenWriteSet: [
      'src/components/timeline/Timeline.tsx',
      'src/components/timeline/TimelineTrack.tsx',
      'src/components/timeline/TimelineClipCanvas.tsx',
    ],
    exitGates: [
      'P1_ARCHITECTURE_REGISTRY_COHERENT',
      'P1_KERNEL_IMPORT_BOUNDARY',
      'P1_LOC_BUDGET_ENFORCED',
      'P1_SCHEMA_RUNTIME_FREE_BOUNDARY',
      'P1_VISUAL_DEMAND_NAME_ISOLATED',
      'P1_HIGH_CONFLICT_OWNERSHIP_COMPLETE',
      'P1_TEST_AND_RETIRED_PATH_CLASSIFICATION',
    ],
    activeUntilGate: 'P1_TEST_AND_RETIRED_PATH_CLASSIFICATION',
  },
  {
    id: 'timeline-host',
    name: 'Timeline Host And Projection',
    owner: 'Codex',
    status: 'done',
    writeSet: [
      'src/timeline/contracts/**',
      'src/timeline/projection/**',
      'src/timeline/geometry/**',
      'src/components/timeline/Timeline.tsx',
      'src/components/timeline/types.ts',
      'tests/unit/timelineRenderModel.test.ts',
    ],
    forbiddenWriteSet: [
      'src/services/layerBuilder/VideoSyncManager.ts',
      'src/services/layerBuilder/AudioTrackSyncManager.ts',
    ],
    exitGates: [
      'P2_TIMELINE_PROJECTION_ADOPTED',
      'P2_GEOMETRY_SNAPSHOT_ADOPTED',
      'P2_VISIBLE_SET_SINGLE_SOURCE',
      'P2_SCROLL_DOES_NOT_REBUILD_GEOMETRY',
    ],
  },
  {
    id: 'paint-canvas',
    name: 'Paint Packet And Canvas Host',
    owner: 'Codex',
    status: 'done',
    writeSet: [
      'src/timeline/paint/**',
      'src/timeline/resources/**',
      'src/components/timeline/TimelineClipCanvas.tsx',
      'src/components/timeline/TimelineTrack.tsx',
      'src/components/timeline/workers/**',
      'src/components/timeline/utils/timelineClipCanvasPaintVisualContributors.ts',
      'src/components/timeline/utils/timelineClipCanvasWorkerContract.ts',
      'src/components/timeline/utils/timelineClipCanvasWorkerModel.ts',
      'src/components/timeline/interactionShell/**',
      'tests/unit/timelineClipCanvasWorkerModel.test.ts',
      'tests/unit/TimelineClipCanvasWorkerRuntime.test.tsx',
    ],
    forbiddenWriteSet: [
      'src/stores/timeline/clipSlice.ts',
      'src/stores/timeline/keyframeSlice.ts',
      'src/stores/timeline/editOperations/**',
    ],
    exitGates: [
      'P3_PAINT_PACKET_ADOPTED',
      'P3_CANVAS_CLIP_FIELD_COVERAGE_GREEN',
      'P3_CANVAS_CLIP_DELETED',
      'P3_INTERACTION_SHELL_CALLBACKS_NARROW',
    ],
  },
  {
    id: 'runtime-store-importer',
    name: 'Runtime, Store, And Importer Cleanup',
    owner: 'Codex',
    status: 'done',
    writeSet: [
      'src/timeline/resources/**',
      'src/services/timeline/**',
      'src/services/timeline/nativeDecoderRuntimeRegistry.ts',
      'src/services/layerBuilder/VideoSyncManager.ts',
      'src/services/layerBuilder/videoSyncFullWebCodecsCoordinator.ts',
      'src/services/layerBuilder/videoSyncHtmlClipCoordinator.ts',
      'src/services/layerBuilder/videoSyncHtmlSeekCoordinator.ts',
      'src/services/layerBuilder/videoSyncNestedCompositionCoordinator.ts',
      'src/services/layerBuilder/videoSyncRecoveryCoordinator.ts',
      'src/services/layerBuilder/videoSyncWarmupCoordinator.ts',
      'src/services/layerBuilder/videoSyncMediaResolver.ts',
      'src/services/layerBuilder/AudioTrackSyncManager.ts',
      'src/services/layerBuilder/audioSyncMediaResolver.ts',
      'src/services/layerBuilder/LayerBuilderService.ts',
      'src/components/timeline/hooks/useLayerSync.ts',
      'src/stores/timeline/**',
      'src/components/timeline/hooks/useExternalDrop.ts',
      'tests/stores/timeline/**',
      'tests/unit/mediaObjectUrlManager.test.ts',
      'tests/unit/timelineRuntimeCoordinatorContracts.test.ts',
    ],
    forbiddenWriteSet: [
      'src/components/timeline/TimelineClipCanvas.tsx',
    ],
    exitGates: [
      'P4_RUNTIME_PROVIDER_DEMAND_ADOPTED',
      'P4_VIDEO_SYNC_SOURCE_HANDLES_REMOVED',
      'P4_AUDIO_SYNC_SOURCE_HANDLES_REMOVED',
      'P4_TIMELINE_STATE_RUNTIME_HANDLES_REMOVED',
      'P4_STORE_SLICE_GOD_FILES_SPLIT',
      'P4_EDIT_OPERATION_APPLIER_NARROW',
      'P4_IMPORTER_LEGACY_QUARANTINE',
      'P4_SERIALIZATION_RUNTIME_FREE_EDITOR_PATH',
      'P4_DROP_IMPORT_COMMANDS_ROUTED',
      'P4_RUNTIME_RESOURCE_TESTS_KEPT_OUT_OF_KERNEL',
    ],
  },
  {
    id: 'test-cleanup',
    name: 'Test Migration And Dead-Code Cleanup',
    owner: 'Codex',
    status: 'done',
    writeSet: [
      'tests/**',
      'docs/completed/architecture/**',
      'docs/completed/**',
      'docs/Features/**',
    ],
    forbiddenWriteSet: [
      'src/components/timeline/TimelineClipCanvas.tsx',
      'src/stores/timeline/clipSlice.ts',
    ],
    exitGates: [
      'P5_TEST_MIGRATION_COMPLETE',
      'P5_RETIRED_PATHS_DELETED',
      'P5_DOCS_HANDOFF_COMPLETE',
      'P5_FULL_CHECK_CHAIN_GREEN',
    ],
  },
] as const satisfies readonly TimelineRefactorLane[];

export const timelineHighConflictOwnership = [
  { path: 'src/components/timeline/Timeline.tsx', laneId: 'timeline-host' },
  { path: 'src/components/timeline/TimelineTrack.tsx', laneId: 'paint-canvas' },
  { path: 'src/components/timeline/TimelineClipCanvas.tsx', laneId: 'paint-canvas' },
  { path: 'src/components/timeline/types.ts', laneId: 'timeline-host' },
  { path: 'src/components/timeline/hooks/useExternalDrop.ts', laneId: 'runtime-store-importer' },
  { path: 'src/stores/timeline/clipSlice.ts', laneId: 'runtime-store-importer' },
  { path: 'src/stores/timeline/keyframeSlice.ts', laneId: 'runtime-store-importer' },
  { path: 'src/stores/timeline/editOperations/**', laneId: 'runtime-store-importer' },
  { path: 'src/stores/timeline/trackSlice.ts', laneId: 'runtime-store-importer' },
  { path: 'src/stores/timeline/helpers/blobUrlManager.ts', laneId: 'runtime-store-importer' },
  { path: 'src/services/layerBuilder/VideoSyncManager.ts', laneId: 'runtime-store-importer' },
  { path: 'src/services/layerBuilder/AudioTrackSyncManager.ts', laneId: 'runtime-store-importer' },
] as const satisfies readonly TimelineHighConflictOwnership[];
