import type { TimelineRetiredPathEntry } from './types';

export const timelineRetiredPathLedger = [
  {
    id: 'PASSIVE_DOM_CLIP_RENDERER',
    path: 'src/components/timeline/TimelineClip.tsx',
    classification: 'delete now',
    ownerLane: 'paint-canvas',
    deleteBy: 'P1_TEST_AND_RETIRED_PATH_CLASSIFICATION',
    replacementGate: 'P3_PAINT_PACKET_ADOPTED',
    note: 'The passive DOM clip renderer is already removed and must not be restored.',
  },
  {
    id: 'CANVAS_CLIP_BRIDGE',
    path: 'src/components/timeline/TimelineClipCanvas.tsx#TimelineClipCanvasInputClip',
    classification: 'delete now',
    ownerLane: 'paint-canvas',
    deleteBy: 'P3_CANVAS_CLIP_DELETED',
    replacementGate: 'P3_PAINT_PACKET_ADOPTED',
    note: 'The former CanvasClip host bridge was deleted from TimelineClipCanvas and replaced by the kernel TimelinePaintSourceClip source contract.',
  },
  {
    id: 'CANVAS_WORKER_FALLBACK_MODEL',
    path: 'src/components/timeline/utils/timelineClipCanvasWorker{Model,PaintClip}.ts',
    classification: 'keep',
    ownerLane: 'paint-canvas',
    keepReason: 'The worker paint input normalizer and resource-missing eligibility fallback are target canvas worker behavior, not legacy CanvasClip compatibility.',
    replacementGate: 'P4_RUNTIME_PROVIDER_DEMAND_ADOPTED',
    note: 'Worker draw consumes normalized paint clips from TimelinePaintSourceClip, and source-kind activation lives in registered contributors.',
  },
  {
    id: 'COMPONENT_RENDER_MODEL_ADAPTER',
    path: 'src/components/timeline/renderModel/**',
    classification: 'delete now',
    ownerLane: 'timeline-host',
    deleteBy: 'P2_GEOMETRY_SNAPSHOT_ADOPTED',
    replacementGate: 'P2_TIMELINE_PROJECTION_ADOPTED',
    note: 'Component-owned render-model contracts were migrated to src/timeline projection and geometry contracts.',
  },
  {
    id: 'MANUAL_TIMELINE_GEOMETRY_MAPPING',
    path: 'src/components/timeline/{Timeline.tsx,TimelineTrack.tsx,TimelineClipCanvas.tsx}',
    classification: 'keep',
    ownerLane: 'timeline-host',
    keepReason: 'Remaining time/pixel conversions are host interaction and canvas translation adapters; clip hit geometry and shell placement use the kernel TimelineGeometrySnapshot boundary.',
    replacementGate: 'P2_GEOMETRY_SNAPSHOT_ADOPTED',
    note: 'The old component-owned clip geometry path is replaced by the timelineTrackGeometryAdapter and guarded Pointer/Marquee hit-test coverage.',
  },
  {
    id: 'INTERACTION_SHELL_CALLBACK_PLUMBING',
    path: 'src/components/timeline/interactionShell/**',
    classification: 'delete now',
    ownerLane: 'paint-canvas',
    deleteBy: 'P3_INTERACTION_SHELL_CALLBACKS_NARROW',
    replacementGate: 'P3_INTERACTION_SHELL_CALLBACKS_NARROW',
    note: 'The former callback-bag plumbing is replaced by command descriptors and local shell state.',
  },
  {
    id: 'EDITOR_RUNTIME_RESTORE_COMPATIBILITY',
    path: 'src/stores/timeline/serialization/loadStateMediaClipRestore.ts',
    classification: 'move to importer',
    ownerLane: 'runtime-store-importer',
    importerOwner: 'runtime-store-importer',
    replacementGate: 'P4_IMPORTER_LEGACY_QUARANTINE',
    note: 'Old project restore compatibility is isolated in load-state importer helpers and timeline runtime services, not the serialization root.',
  },
  {
    id: 'TIMELINE_SOURCE_HANDLE_FIELDS',
    path: 'src/types/index.ts#TimelineClip.source',
    classification: 'move to importer',
    ownerLane: 'runtime-store-importer',
    importerOwner: 'runtime-store-importer',
    replacementGate: 'P4_TIMELINE_STATE_RUNTIME_HANDLES_REMOVED',
    note: 'Runtime source handles are quarantined from the new timeline schema.',
  },
  {
    id: 'LAYER_BUILDER_DIRECT_SOURCE_HANDLES',
    path: 'src/services/layerBuilder/{VideoSyncManager.ts,AudioTrackSyncManager.ts}',
    classification: 'delete now',
    ownerLane: 'runtime-store-importer',
    deleteBy: 'P4_AUDIO_SYNC_SOURCE_HANDLES_REMOVED',
    replacementGate: 'P4_RUNTIME_PROVIDER_DEMAND_ADOPTED',
    note: 'Former direct timeline source-handle reads were removed; sync managers now read resolver-fed provider leases.',
  },
] as const satisfies readonly TimelineRetiredPathEntry[];
