import type { CompleteArchitectureGate } from './types';
import { motionDesignArchitectureGates } from './motionDesignGateRegistry';
import { storyboardArchitectureGates } from './storyboardGateRegistry';

const completeRefactorArchitectureGates = [
  {
    id: 'P0_BASELINE_CAPTURED',
    phase: 'P0',
    title: 'Baseline commands and smoke inventory are recorded',
    status: 'satisfied',
  },
  {
    id: 'P0_BASELINE_REFRESHED',
    phase: 'P0',
    title: 'Gate numbers are refreshed from current HEAD before enforcement',
    status: 'satisfied',
    dependsOn: ['P0_BASELINE_CAPTURED'],
  },
  {
    id: 'P0_COMPLETE_ARCHITECTURE_REGISTRY',
    phase: 'P0',
    title: 'Whole-codebase architecture registry is executable',
    status: 'satisfied',
    dependsOn: ['P0_BASELINE_CAPTURED'],
  },
  {
    id: 'P0_RENDER_PLAYBACK_BASELINE',
    phase: 'P0',
    title: 'Render and playback smoke thresholds are defined',
    status: 'active',
    dependsOn: ['P0_BASELINE_CAPTURED'],
  },
  {
    id: 'P0_EXPORT_BASELINE',
    phase: 'P0',
    title: 'Export smoke thresholds are defined',
    status: 'active',
    dependsOn: ['P0_BASELINE_CAPTURED'],
  },
  {
    id: 'P0_PROXY_CACHE_PRESSURE',
    phase: 'P0',
    title: 'Proxy cache pressure baseline is defined',
    status: 'active',
    dependsOn: ['P0_BASELINE_CAPTURED'],
  },
  {
    id: 'P0_AUDIO_CONTEXT_BASELINE',
    phase: 'P0',
    title: 'Audio context ownership baseline is defined',
    status: 'active',
    dependsOn: ['P0_BASELINE_CAPTURED'],
  },
  {
    id: 'P0_PREVIEW_TARGET_LIFECYCLE',
    phase: 'P0',
    title: 'Preview target lifecycle baseline is defined',
    status: 'active',
    dependsOn: ['P0_BASELINE_CAPTURED'],
  },
  {
    id: 'P0_CSS_GLOBAL_SELECTOR_GATE',
    phase: 'P0',
    title: 'CSS global selector and overlay scan is defined',
    status: 'active',
    dependsOn: ['P0_BASELINE_CAPTURED'],
  },
  {
    id: 'P1_TYPE_TIER_DEFINED',
    phase: 'P1',
    title: 'Type tiers are explicit',
    status: 'satisfied',
    dependsOn: ['P0_COMPLETE_ARCHITECTURE_REGISTRY'],
  },
  {
    id: 'P1_GLOBAL_TYPES_BARREL_THIN',
    phase: 'P1',
    title: 'Global type barrel has compatibility-only retirement plan',
    status: 'active',
    dependsOn: ['P1_TYPE_TIER_DEFINED'],
  },
  {
    id: 'P1_TYPE_TIER_NO_RUNTIME_IMPORTS',
    phase: 'P1',
    title: 'Pure type tiers exclude runtime imports and handles',
    status: 'active',
    dependsOn: ['P1_TYPE_TIER_DEFINED'],
  },
  {
    id: 'P1_PROJECT_SCHEMA_NO_STORE_IMPORTS',
    phase: 'P1',
    title: 'Project schema has no store, component, or engine imports',
    status: 'satisfied',
    dependsOn: ['P1_TYPE_TIER_DEFINED'],
  },
  {
    id: 'P1_STORE_PUBLIC_FACADES_DEFINED',
    phase: 'P1',
    title: 'Store public facades separate durable state, actions, selectors, planners, and runtime leases',
    status: 'active',
    dependsOn: ['P1_TYPE_TIER_DEFINED'],
  },
  {
    id: 'P1_PROJECT_SCHEMA_OWNS_PERSISTED_TYPES',
    phase: 'P1',
    title: 'Project schema owns persisted DTOs instead of live store internals',
    status: 'satisfied',
    dependsOn: ['P1_PROJECT_SCHEMA_NO_STORE_IMPORTS'],
  },
  {
    id: 'P1_RUNTIME_HANDLES_FORBIDDEN_IN_SHARED_SCHEMA',
    phase: 'P1',
    title: 'Shared schema and broad type surfaces reject runtime handles',
    status: 'active',
    dependsOn: ['P1_TYPE_TIER_NO_RUNTIME_IMPORTS'],
  },
  {
    id: 'P1A_CLIP_SOURCE_DURABLE_RUNTIME_SPLIT',
    phase: 'P1A',
    title: 'Clip and source references separate durable data from runtime leases',
    status: 'satisfied',
    dependsOn: ['P1_TYPE_TIER_DEFINED'],
  },
  {
    id: 'P1A_MEDIA_FILE_RUNTIME_SIDETABLE',
    phase: 'P1A',
    title: 'Media runtime handles have a side-table or lease owner',
    status: 'satisfied',
    dependsOn: ['P1A_CLIP_SOURCE_DURABLE_RUNTIME_SPLIT'],
  },
  {
    id: 'P1A_SINGLE_RUNTIME_LEASE_DOMAIN',
    phase: 'P1A',
    title: 'services/mediaRuntime is the canonical lease domain',
    status: 'satisfied',
    dependsOn: ['P1A_MEDIA_FILE_RUNTIME_SIDETABLE'],
  },
  {
    id: 'P1A_RUNTIME_HANDLE_ROUNDTRIP_GUARD',
    phase: 'P1A',
    title: 'Persisted state roundtrip rejects live handles',
    status: 'satisfied',
    dependsOn: ['P1A_MEDIA_FILE_RUNTIME_SIDETABLE'],
  },
  {
    id: 'P1A_HMR_SAFE_RUNTIME_OWNER',
    phase: 'P1A',
    title: 'Runtime owners follow the HMR singleton pattern',
    status: 'satisfied',
    dependsOn: ['P1A_SINGLE_RUNTIME_LEASE_DOMAIN'],
  },
  {
    id: 'P1B_SIGNAL_DTO_RUNTIME_FREE',
    phase: 'P1B',
    title: 'Signal DTOs are runtime-free and serializable',
    status: 'satisfied',
    dependsOn: ['P1_TYPE_TIER_NO_RUNTIME_IMPORTS'],
  },
  {
    id: 'P1B_UNIVERSAL_IMPORT_ROUTE_MATRIX',
    phase: 'P1B',
    title: 'Universal import route matrix covers all target file families',
    status: 'satisfied',
    dependsOn: ['P1B_SIGNAL_DTO_RUNTIME_FREE'],
  },
  {
    id: 'P1B_NO_UNSUPPORTED_FILE_FALLBACK',
    phase: 'P1B',
    title: 'Unknown files become SignalAsset fallback instead of unsupported errors',
    status: 'satisfied',
    dependsOn: ['P1B_UNIVERSAL_IMPORT_ROUTE_MATRIX'],
  },
  {
    id: 'P1B_SIGNAL_PROJECT_ROUNDTRIP',
    phase: 'P1B',
    title: 'Signal assets roundtrip through project persistence',
    status: 'satisfied',
    dependsOn: ['P1B_SIGNAL_DTO_RUNTIME_FREE'],
  },
  {
    id: 'P1B_SIGNAL_TIMELINE_MATERIALIZATION_CONTRACT',
    phase: 'P1B',
    title: 'Signal timeline materialization contract is explicit',
    status: 'satisfied',
    dependsOn: ['P1B_UNIVERSAL_IMPORT_ROUTE_MATRIX'],
  },
  {
    id: 'P1B_SIGNAL_PREVIEW_EXPORT_FALLBACK',
    phase: 'P1B',
    title: 'Signal preview and export fallback contract is explicit',
    status: 'satisfied',
    dependsOn: ['P1B_UNIVERSAL_IMPORT_ROUTE_MATRIX'],
  },
  {
    id: 'P2_STORE_PROJECT_CONTRACT_FREEZE',
    phase: 'P2',
    title: 'Store and project contracts are frozen together',
    status: 'active',
    dependsOn: ['P1_PROJECT_SCHEMA_OWNS_PERSISTED_TYPES'],
  },
  {
    id: 'P3_PROJECT_SCHEMA_BOUNDARY',
    phase: 'P3',
    title: 'Project schema boundary is serializable and runtime-free',
    status: 'satisfied',
    dependsOn: ['P2_STORE_PROJECT_CONTRACT_FREEZE'],
  },
  {
    id: 'P3_CURRENT_PROJECT_SCHEMA_ONLY',
    phase: 'P3',
    title: 'Current schema is the only required saved-project target',
    status: 'active',
    dependsOn: ['P3_PROJECT_SCHEMA_BOUNDARY'],
  },
  {
    id: 'P3_LEGACY_PROJECT_COMPAT_RETIRED',
    phase: 'P3',
    title: 'Old saved-project compatibility is retired by policy',
    status: 'active',
    dependsOn: ['P3_CURRENT_PROJECT_SCHEMA_ONLY'],
  },
  {
    id: 'P3_DEPRECATED_PAYLOADS_DELETED_OR_IGNORED',
    phase: 'P3',
    title: 'Deprecated project payloads are deleted or ignored',
    status: 'active',
    dependsOn: ['P3_LEGACY_PROJECT_COMPAT_RETIRED'],
  },
  { id: 'P3_DOCK_DEPRECATED_PANEL_PAYLOADS_RETIRED', phase: 'P3', title: 'Deprecated dock panel payloads are retired or ignored', status: 'satisfied', dependsOn: ['P3_DEPRECATED_PAYLOADS_DELETED_OR_IGNORED'] },
  {
    id: 'P4_MEDIA_PANEL_SHELL_SPLIT',
    phase: 'P4',
    title: 'Media Panel split waits for foundation gates',
    status: 'active',
    dependsOn: ['P2_STORE_PROJECT_CONTRACT_FREEZE'],
  },
  { id: 'P4_DOWNLOADS_ACTIVE_IN_MEDIA_PANEL', phase: 'P4', title: 'Download workflow is active in Media Panel, not a dock panel', status: 'satisfied', dependsOn: ['P4_MEDIA_PANEL_SHELL_SPLIT'] },
  { id: 'P4_MEDIA_BOARD_VS_FLASHBOARD_BOARD_CLASSIFIED', phase: 'P4', title: 'Active Media Board and retired FlashBoard board are classified separately', status: 'satisfied', dependsOn: ['P4_MEDIA_PANEL_SHELL_SPLIT'] },
  { id: 'P4_FLASHBOARD_RETIRED_BOARD_LEDGER', phase: 'P4', title: 'Retired FlashBoard board and canvas paths are ledgered before deletion', status: 'satisfied', dependsOn: ['P4_MEDIA_BOARD_VS_FLASHBOARD_BOARD_CLASSIFIED'] },
  {
    id: 'P5_EXPORT_RENDER_SESSION_CONTRACT',
    phase: 'P5',
    title: 'Export render session contract waits for render snapshot gates',
    status: 'active',
    dependsOn: ['P0_EXPORT_BASELINE'],
  },
  {
    id: 'P5_RENDER_TARGET_SNAPSHOT_CONTRACT',
    phase: 'P5',
    title: 'Render target snapshot input is explicit before preview/export implementation',
    status: 'active',
    dependsOn: ['P0_PREVIEW_TARGET_LIFECYCLE'],
  },
  {
    id: 'P6_RENDER_FRAME_SNAPSHOT',
    phase: 'P6',
    title: 'Render frame snapshot contract replaces live store reads in hot paths',
    status: 'active',
    dependsOn: ['P0_RENDER_PLAYBACK_BASELINE'],
  },
  {
    id: 'P7_PHASE0_SMOKES_STABLE',
    phase: 'P7',
    title: 'AI bridge smokes remain stable as verifier surfaces',
    status: 'active',
    dependsOn: ['P0_COMPLETE_ARCHITECTURE_REGISTRY'],
  },
  {
    id: 'P8_ARCHITECTURE_GATE_SUITE',
    phase: 'P8',
    title: 'Architecture gate suite is executable',
    status: 'active',
    dependsOn: ['P0_COMPLETE_ARCHITECTURE_REGISTRY'],
  },
] as const satisfies readonly CompleteArchitectureGate[];

export const completeArchitectureGates = [
  ...completeRefactorArchitectureGates,
  ...storyboardArchitectureGates,
  ...motionDesignArchitectureGates,
] as const satisfies readonly CompleteArchitectureGate[];

export const completeArchitectureGateIds = completeArchitectureGates.map(
  (gate) => gate.id,
);
