import type { CompleteHighConflictOwnership } from './types';

export const completeHighConflictTargets = [
  'src/types/index.ts',
  'src/types/dock.ts',
  'src/services/project/types/**',
  'src/services/project/projectLoad.ts',
  'src/services/mediaRuntime/**',
  'src/signals/**',
  'src/importers/**',
  'src/stores/timeline/**',
  'src/components/timeline/**',
  'src/components/dock/**',
  'src/timeline/architecture/**',
  'src/stores/mediaStore/**',
  // historyStore and dockStore became folders (packets 175/171).
  'src/stores/historyStore/**',
  'src/stores/dockStore/**',
  'src/stores/renderTargetStore.ts',
  'src/engine/render/RenderDispatcher.ts',
  'src/engine/WebGPUEngine.ts',
  'src/components/preview/**',
  'src/components/export/**',
  'src/services/aiTools/**',
  'functions/api/ai/chat.ts',
  'functions/lib/chatBilling.ts',
  'src/services/cloudAiService.ts',
  'src/services/flashboard/FlashBoardChatProviderTransport.ts',
  'src/services/flashboard/FlashBoardChatTypes.ts',
  'src/services/flashboard/FlashBoardChatTools.ts',
  'src/components/panels/flashboard/FlashBoardChatOutput.tsx',
  'src/components/panels/flashboard/useFlashBoardChatController.ts',
  'src/stores/flashboardStore/types.ts',
  'src/types/motionDesign.ts',
  'src/engine/motion/MotionRenderer.ts',
  'src/services/motionDesign/contracts/**',
  'docs/plans/motion-design-md0-md9-multilane-execution-plan.md',
] as const;

export const completeHighConflictOwnership = [
  { path: 'src/types/index.ts', laneId: 'foundation-contracts' },
  { path: 'src/types/dock.ts', laneId: 'media-flashboard' },
  { path: 'src/services/project/types/**', laneId: 'project-schema-freeze' },
  { path: 'src/services/project/projectLoad.ts', laneId: 'project-hydration-adapter' },
  { path: 'src/services/mediaRuntime/**', laneId: 'media-runtime-lease' },
  { path: 'src/signals/**', laneId: 'universal-signals-importers' },
  { path: 'src/importers/**', laneId: 'universal-signals-importers' },
  { path: 'src/stores/timeline/**', laneId: 'store-architecture' },
  { path: 'src/components/timeline/**', laneId: 'store-architecture' },
  { path: 'src/components/dock/**', laneId: 'media-flashboard' },
  { path: 'src/timeline/architecture/**', laneId: 'architecture-registry' },
  { path: 'src/stores/mediaStore/**', laneId: 'store-architecture' },
  { path: 'src/stores/historyStore/**', laneId: 'store-architecture' },
  { path: 'src/stores/dockStore/**', laneId: 'media-flashboard' },
  { path: 'src/stores/renderTargetStore.ts', laneId: 'store-architecture' },
  { path: 'src/engine/render/RenderDispatcher.ts', laneId: 'preview-export-render' },
  { path: 'src/engine/WebGPUEngine.ts', laneId: 'preview-export-render' },
  { path: 'src/components/preview/**', laneId: 'preview-export-render' },
  { path: 'src/components/export/**', laneId: 'preview-export-render' },
  { path: 'src/services/aiTools/**', laneId: 'ai-tools-smokes' },
  { path: 'functions/api/ai/chat.ts', laneId: 'storyboard-contract-integration' },
  { path: 'functions/lib/chatBilling.ts', laneId: 'storyboard-contract-integration' },
  { path: 'src/services/cloudAiService.ts', laneId: 'storyboard-contract-integration' },
  { path: 'src/services/flashboard/FlashBoardChatProviderTransport.ts', laneId: 'storyboard-chat-decisions' },
  { path: 'src/services/flashboard/FlashBoardChatTypes.ts', laneId: 'storyboard-chat-decisions' },
  { path: 'src/services/flashboard/FlashBoardChatTools.ts', laneId: 'storyboard-chat-decisions' },
  { path: 'src/components/panels/flashboard/FlashBoardChatOutput.tsx', laneId: 'storyboard-chat-decisions' },
  { path: 'src/components/panels/flashboard/useFlashBoardChatController.ts', laneId: 'storyboard-chat-decisions' },
  { path: 'src/stores/flashboardStore/types.ts', laneId: 'storyboard-chat-decisions' },
  { path: 'src/types/motionDesign.ts', laneId: 'motion-design-integration' },
  { path: 'src/engine/motion/MotionRenderer.ts', laneId: 'motion-design-integration' },
  { path: 'src/services/motionDesign/contracts/**', laneId: 'motion-design-integration' },
  { path: 'docs/plans/motion-design-md0-md9-multilane-execution-plan.md', laneId: 'motion-design-integration' },
] as const satisfies readonly CompleteHighConflictOwnership[];
