import type { CompleteRefactorLane } from './types';
import { motionDesignRefactorLanes } from './motionDesignRefactorLanes';
import { storyboardRefactorLanes } from './storyboardLaneWriteManifest';

const completeLegacyRefactorLanes = [
  {
    id: 'architecture-registry',
    name: 'Whole-Codebase Architecture Registry',
    owner: 'Master Orchestrator',
    status: 'active',
    writeSet: [
      'src/architecture/**',
      'tests/unit/completeArchitectureRegistry.test.ts',
      'docs/completed/refactor/Complete-refactor.md',
      'docs/completed/refactor/Complete-refactor-checklist.md',
      'docs/completed/refactor/complete-refactor/**',
    ],
    forbiddenWriteSet: [
      'src/components/**',
      'src/stores/**',
      'src/engine/**',
      'src/services/**',
      'src/timeline/architecture/**',
    ],
    exitGates: [
      'P0_COMPLETE_ARCHITECTURE_REGISTRY',
      'P8_ARCHITECTURE_GATE_SUITE',
    ],
  },
  {
    id: 'foundation-contracts',
    name: 'Foundation Type Tiers And Shared Contracts',
    owner: 'Master Orchestrator',
    status: 'planned',
    writeSet: [
      'src/types/**',
      'tests/unit/completeArchitectureRegistry.test.ts',
      'tests/unit/foundationTypeBoundary.test.ts',
    ],
    forbiddenWriteSet: [
      'src/components/**',
      'src/engine/**',
      'src/services/project/projectLoad.ts',
      'src/services/project/projectSave.ts',
      'src/stores/**',
      'src/timeline/architecture/**',
    ],
    exitGates: [
      'P1_TYPE_TIER_DEFINED',
      'P1_GLOBAL_TYPES_BARREL_THIN',
      'P1_TYPE_TIER_NO_RUNTIME_IMPORTS',
      'P1_RUNTIME_HANDLES_FORBIDDEN_IN_SHARED_SCHEMA',
    ],
  },
  {
    id: 'media-runtime-lease',
    name: 'Clip And Media Source Runtime Lease Boundary',
    owner: 'Master Orchestrator',
    status: 'done',
    writeSet: [
      'src/types/**',
      'src/services/mediaRuntime/**',
      'tests/unit/persistedStateRuntimeHandles.test.ts',
      'tests/unit/mediaRuntimeLeaseContracts.test.ts',
    ],
    forbiddenWriteSet: [
      'src/components/panels/MediaPanel.tsx',
      'src/components/timeline/**',
      'src/stores/timeline/**',
      'src/services/project/projectLoad.ts',
      'src/services/project/projectSave.ts',
      'src/engine/render/RenderDispatcher.ts',
      'src/components/export/ExportPanel.tsx',
      'src/timeline/architecture/**',
    ],
    exitGates: [
      'P1A_CLIP_SOURCE_DURABLE_RUNTIME_SPLIT',
      'P1A_MEDIA_FILE_RUNTIME_SIDETABLE',
      'P1A_SINGLE_RUNTIME_LEASE_DOMAIN',
      'P1A_RUNTIME_HANDLE_ROUNDTRIP_GUARD',
      'P1A_HMR_SAFE_RUNTIME_OWNER',
    ],
  },
  {
    id: 'universal-signals-importers',
    name: 'Universal Signal DTOs And Import Routes',
    owner: 'Master Orchestrator',
    status: 'done',
    writeSet: [
      'src/signals/**',
      'src/importers/**',
      'tests/unit/signals/**',
      'tests/unit/importers/**',
      'tests/stores/mediaStore/fileImportSignalSlice.test.ts',
    ],
    forbiddenWriteSet: [
      'src/components/panels/MediaPanel.tsx',
      'src/components/timeline/**',
      'src/services/project/projectLoad.ts',
      'src/services/project/projectSave.ts',
      'src/engine/render/RenderDispatcher.ts',
      'src/components/export/ExportPanel.tsx',
      'src/timeline/architecture/**',
    ],
    exitGates: [
      'P1B_SIGNAL_DTO_RUNTIME_FREE',
      'P1B_UNIVERSAL_IMPORT_ROUTE_MATRIX',
      'P1B_NO_UNSUPPORTED_FILE_FALLBACK',
      'P1B_SIGNAL_PROJECT_ROUNDTRIP',
      'P1B_SIGNAL_TIMELINE_MATERIALIZATION_CONTRACT',
      'P1B_SIGNAL_PREVIEW_EXPORT_FALLBACK',
    ],
  },
  {
    id: 'project-schema-freeze',
    name: 'Project Schema DTO Boundary',
    owner: 'Master Orchestrator',
    status: 'active',
    writeSet: [
      'src/services/project/types/**',
      'tests/unit/projectSchemaBoundary.test.ts',
      'tests/unit/persistedStateRuntimeHandles.test.ts',
    ],
    forbiddenWriteSet: [
      'src/services/project/projectLoad.ts',
      'src/services/project/projectSave.ts',
      'src/components/**',
      'src/engine/**',
      'src/stores/**',
      'src/timeline/architecture/**',
    ],
    exitGates: [
      'P1_PROJECT_SCHEMA_NO_STORE_IMPORTS',
      'P1_PROJECT_SCHEMA_OWNS_PERSISTED_TYPES',
      'P3_PROJECT_SCHEMA_BOUNDARY',
      'P3_CURRENT_PROJECT_SCHEMA_ONLY',
      'P3_LEGACY_PROJECT_COMPAT_RETIRED',
      'P3_DEPRECATED_PAYLOADS_DELETED_OR_IGNORED',
    ],
  },
  {
    id: 'project-hydration-adapter',
    name: 'Project Hydration Adapter Boundary',
    owner: 'Master Orchestrator',
    status: 'active',
    writeSet: [
      'src/services/project/projectLoad.ts',
      'src/services/project/types/schema.types.ts',
      'tests/unit/projectSchemaBoundary.test.ts',
      'src/architecture/**',
      'docs/completed/refactor/Complete-refactor.md',
      'docs/completed/refactor/Complete-refactor-checklist.md',
      'docs/completed/refactor/complete-refactor/**',
    ],
    forbiddenWriteSet: [
      'src/services/project/projectSave.ts',
      'src/stores/**',
      'src/components/**',
      'src/engine/**',
      'src/services/mediaRuntime/**',
      'src/timeline/architecture/**',
    ],
    exitGates: [
      'P3_PROJECT_SCHEMA_BOUNDARY',
      'P3_CURRENT_PROJECT_SCHEMA_ONLY',
      'P3_LEGACY_PROJECT_COMPAT_RETIRED',
    ],
  },
  {
    id: 'store-architecture',
    name: 'Store And Runtime Ownership',
    owner: 'Master Orchestrator',
    status: 'planned',
    writeSet: [
      'src/stores/**',
      'tests/stores/**',
      'tests/unit/storeBoundary.test.ts',
    ],
    forbiddenWriteSet: [
      'src/services/project/projectLoad.ts',
      'src/services/project/projectSave.ts',
      'src/components/timeline/**',
      'src/engine/**',
      'src/timeline/architecture/**',
    ],
    exitGates: ['P2_STORE_PROJECT_CONTRACT_FREEZE'],
  },
  {
    id: 'media-flashboard',
    name: 'Media Panel And FlashBoard',
    owner: 'Master Orchestrator',
    status: 'planned',
    writeSet: [
      'src/types/dock.ts',
      'src/stores/dockStore.ts',
      'src/components/common/Toolbar.tsx',
      'src/components/dock/**',
      'src/components/panels/MediaPanel*',
      'src/components/panels/flashboard/**',
      'src/stores/flashboardStore/**',
      'src/services/flashboard/**',
      'tests/unit/dockPanelConfigs.test.ts',
      'tests/unit/dockStoreLayouts.test.ts',
      'tests/unit/mediaPanel*.test.ts',
      'tests/unit/flashboard*.test.ts',
    ],
    forbiddenWriteSet: [
      'src/services/project/projectLoad.ts',
      'src/services/project/projectSave.ts',
      'src/engine/**',
      'src/services/mediaRuntime/**',
      'src/timeline/architecture/**',
    ],
    exitGates: [
      'P4_MEDIA_PANEL_SHELL_SPLIT',
      'P4_DOWNLOADS_ACTIVE_IN_MEDIA_PANEL',
      'P4_MEDIA_BOARD_VS_FLASHBOARD_BOARD_CLASSIFIED',
      'P4_FLASHBOARD_RETIRED_BOARD_LEDGER',
      'P3_DOCK_DEPRECATED_PANEL_PAYLOADS_RETIRED',
    ],
    activeUntilGate: 'P4_FLASHBOARD_RETIRED_BOARD_LEDGER',
  },
  {
    id: 'preview-export-render',
    name: 'Preview Export And Render Snapshot Contracts',
    owner: 'Master Orchestrator',
    status: 'planned',
    writeSet: [
      'src/components/preview/**',
      'src/components/export/**',
      'src/engine/**',
      'tests/unit/preview*.test.ts',
      'tests/unit/export*.test.ts',
      'tests/unit/render*.test.ts',
    ],
    forbiddenWriteSet: [
      'src/services/project/**',
      'src/components/timeline/**',
      'src/stores/timeline/**',
      'src/timeline/architecture/**',
    ],
    exitGates: [
      'P5_EXPORT_RENDER_SESSION_CONTRACT',
      'P6_RENDER_FRAME_SNAPSHOT',
    ],
  },
  {
    id: 'ai-tools-smokes',
    name: 'AI Tools Dev Bridge And Smokes',
    owner: 'Master Orchestrator',
    status: 'planned',
    writeSet: [
      'src/services/aiTools/**',
      'tests/unit/aiTool*.test.ts',
      'scripts/run-timeline-canvas-verification.mjs',
    ],
    forbiddenWriteSet: [
      'src/components/**',
      'src/services/project/projectLoad.ts',
      'src/services/project/projectSave.ts',
      'src/engine/render/RenderDispatcher.ts',
      'src/timeline/architecture/**',
    ],
    exitGates: ['P7_PHASE0_SMOKES_STABLE'],
  },
  {
    id: 'test-architecture-gates',
    name: 'Test Migration And Architecture Gates',
    owner: 'Master Orchestrator',
    status: 'planned',
    writeSet: [
      'tests/**',
      'src/architecture/**',
      'docs/completed/refactor/complete-refactor/**',
    ],
    forbiddenWriteSet: [
      'src/components/**',
      'src/stores/**',
      'src/services/**',
      'src/engine/**',
      'src/timeline/architecture/**',
    ],
    exitGates: ['P8_ARCHITECTURE_GATE_SUITE'],
  },
] as const satisfies readonly CompleteRefactorLane[];

export const completeRefactorLanes = [
  ...completeLegacyRefactorLanes,
  ...storyboardRefactorLanes,
  ...motionDesignRefactorLanes,
] as const satisfies readonly CompleteRefactorLane[];
