import type { CompleteRefactorLane } from './types';

const MDX0 = 'MDX0_BASELINE_CLOSED';
const MDX1 = 'MDX1_OWNERSHIP_REGISTERED';
const MDX2 = 'MDX2_CONTRACTS_FROZEN';
const MDX3 = 'MDX3_FOUNDATIONS_INTEGRATED';
const MDX4 = 'MDX4_PROCEDURAL_MEDIA_INTEGRATED';
const MDX5 = 'MDX5_REUSABLE_CONTENT_INTEGRATED';
const MDX6 = 'MDX6_RELEASE_GREEN';

/**
 * Persistent Motion Design ownership. Contract workers write only new leaf
 * modules; the integration lane retains every shared store, renderer, project,
 * UI, AI, registry, and documentation seam.
 */
export const motionDesignRefactorLanes = [
  {
    id: 'motion-design-integration',
    name: 'Motion Design Contracts, Integration, And Gates',
    owner: 'L0 Main Integrator',
    status: 'active',
    writeSet: [
      'src/architecture/motionDesign*.ts',
      'src/services/motionDesign/contracts/**',
      'src/types/motionDesign.ts',
      'src/types/timeline.ts',
      'src/services/project/types/**motion*',
      'src/services/project/types/composition.types.ts',
      'src/services/project/projectSave.ts',
      'src/services/project/load/loadTimelineHydration.ts',
      'src/stores/timeline/motionClipSlice.ts',
      'src/stores/timeline/clipSlice.ts',
      'src/stores/timeline/clipboardSlice.ts',
      'src/stores/timeline/clipboard/**',
      'src/stores/timeline/historyTimelineEditState.ts',
      'src/stores/timeline/historyTimelineRestoreState.ts',
      'src/stores/timeline/nestedRestore.ts',
      'src/stores/timeline/editOperations/deleteOperations.ts',
      'src/stores/timeline/editOperations/splitBatchOperations.ts',
      'src/stores/timeline/serialization/**',
      'src/services/properties/motionReplicatorProperties.ts',
      'src/services/properties/motionDesignProperties.ts',
      'src/services/motionDesign/mvpCapabilities.ts',
      'src/utils/motionInterpolation.ts',
      'src/components/panels/properties/MotionShapeTab.tsx',
      'src/engine/motion/MotionTypes.ts',
      'src/engine/motion/MotionFrameRuntime.ts',
      'src/engine/motion/MotionBuffers.ts',
      'src/engine/motion/MotionPipeline.ts',
      'src/engine/motion/MotionRenderer.ts',
      'src/engine/motion/shaders/motionShapes.wgsl',
      'src/engine/render/RenderDispatcher.ts',
      'src/engine/render/NestedCompRenderer.ts',
      'src/engine/render/dispatcher/targetPreviewRenderer.ts',
      'src/engine/render/dispatcher/targetPreviewLayerCollector.ts',
      'src/engine/render/layerCollector/staticSourceCollectors.ts',
      'src/engine/WebGPUEngine.ts',
      'src/engine/export/ExportRenderSessionImpl.ts',
      'src/engine/export/FrameExporter.ts',
      'src/engine/export/exportRenderHostPort.ts',
      'src/services/render/renderHostTypes.ts',
      'src/services/render/mainFallbackRenderHostPort.ts',
      'src/services/render/workerShadowRenderHostPort.ts',
      'src/services/render/workerPresentingRenderHostPort.ts',
      'src/services/renderScheduler.ts',
      'src/services/aiTools/**motionDesign*',
      'src/services/flashboard/FlashBoardChatPrompt.ts',
      'src/services/flashboard/FlashBoardChatPlaybooks.ts',
      'tests/unit/motionDesignArchitectureRegistry.test.ts',
      'tests/unit/motionFrameStateContractFreeze.test.ts',
      'tests/unit/motionFrameRuntimeIntegration.test.ts',
      'tests/unit/motionDesignRendering.test.ts',
      'tests/unit/exportRenderSession.test.ts',
      'tests/unit/exportRenderHostPortWorker.test.ts',
      'tests/unit/motionDesignMd1Lifecycle.test.ts',
      'docs/Features/Motion-Design.md',
      'docs/plans/motion-design-*.md',
      'docs/evidence/motion-design/**',
    ],
    forbiddenWriteSet: [
      'src/services/motionDesign/replicator/**',
      'src/services/motionDesign/modifiers/**',
      'src/services/motionDesign/structure/**',
      'src/services/motionDesign/presets/**',
      'src/services/motionDesign/templates/**',
      'src/services/motionDesign/expressions/**',
      'src/services/motionDesign/adjustment/**',
      'src/services/motionDesign/media/**',
    ],
    highConflictFiles: [
      'src/types/motionDesign.ts',
      'src/stores/timeline/motionClipSlice.ts',
      'src/engine/motion/MotionRenderer.ts',
      'docs/plans/motion-design-md0-md9-multilane-execution-plan.md',
    ],
    exitGates: [MDX0, MDX1, MDX2, MDX3, MDX4, MDX5, MDX6],
  },
  {
    id: 'motion-design-procedural',
    name: 'Motion Design Replicators, Modifiers, And Falloffs',
    owner: 'L1 Procedural Instances',
    status: 'active',
    writeSet: [
      'src/services/motionDesign/replicator/**',
      'src/services/motionDesign/modifiers/**',
      'src/engine/motion/replicator/**',
      'tests/unit/motionReplicator*.test.ts',
      'tests/unit/motionModifier*.test.ts',
    ],
    forbiddenWriteSet: [
      'src/architecture/**',
      'src/types/**',
      'src/stores/**',
      'src/services/project/**',
      'src/services/aiTools/**',
      'src/components/**',
      'src/engine/motion/MotionRenderer.ts',
      'src/engine/render/**',
      'src/engine/export/**',
    ],
    exitGates: [MDX2, MDX3, MDX4, MDX6],
    activeUntilGate: MDX6,
  },
  {
    id: 'motion-design-structure-reuse',
    name: 'Motion Design Structure, Presets, Templates, And Expressions',
    owner: 'L2 Structure And Reuse',
    status: 'active',
    writeSet: [
      'src/services/motionDesign/structure/**',
      'src/services/motionDesign/presets/**',
      'src/services/motionDesign/templates/**',
      'src/services/motionDesign/expressions/**',
      'tests/unit/motionParentGraph*.test.ts',
      'tests/unit/motionPreset*.test.ts',
      'tests/unit/motionTemplate*.test.ts',
      'tests/unit/motionExpression*.test.ts',
    ],
    forbiddenWriteSet: [
      'src/architecture/**',
      'src/types/**',
      'src/stores/**',
      'src/services/project/**',
      'src/services/aiTools/**',
      'src/components/**',
      'src/engine/**',
      'src/utils/transformComposition.ts',
    ],
    exitGates: [MDX2, MDX3, MDX5, MDX6],
    activeUntilGate: MDX6,
  },
  {
    id: 'motion-design-compositor-media',
    name: 'Motion Design Adjustment Compositor And Media Motion',
    owner: 'L3 Compositor And Media',
    status: 'active',
    writeSet: [
      'src/services/motionDesign/adjustment/**',
      'src/services/motionDesign/media/**',
      'src/engine/motion/media/**',
      'tests/unit/motionAdjustment*.test.ts',
      'tests/unit/motionMedia*.test.ts',
    ],
    forbiddenWriteSet: [
      'src/architecture/**',
      'src/types/**',
      'src/stores/**',
      'src/services/project/**',
      'src/services/aiTools/**',
      'src/components/**',
      'src/engine/render/**',
      'src/engine/export/**',
      'src/engine/core/types.ts',
    ],
    exitGates: [MDX2, MDX3, MDX4, MDX5, MDX6],
    activeUntilGate: MDX6,
  },
] as const satisfies readonly CompleteRefactorLane[];
