import type { CompleteRetiredPathEntry } from './types';

export const completeRetiredPathLedger = [
  {
    id: 'project-model-sequence-frame-file-field',
    path: 'src/services/project/types/schema.types.ts#ProjectModelSequenceFrame.file',
    classification: 'delete now',
    ownerLane: 'project-hydration-adapter',
    deleteBy: 'P3_PROJECT_SCHEMA_BOUNDARY',
    replacementGate: 'P3_PROJECT_SCHEMA_BOUNDARY',
    note: 'Persisted model sequence frames carry project/source paths only; projectLoad hydrates runtime File handles from raw project files or stored handles.',
  },
  {
    id: 'project-model-sequence-frame-object-url',
    path: 'src/services/project/types/schema.types.ts#ProjectModelSequenceFrame.modelUrl',
    classification: 'delete now',
    ownerLane: 'project-hydration-adapter',
    deleteBy: 'P3_PROJECT_SCHEMA_BOUNDARY',
    replacementGate: 'P3_PROJECT_SCHEMA_BOUNDARY',
    note: 'Persisted model sequence frames do not carry object URLs; projectLoad creates runtime URLs as adapter outputs.',
  },
  {
    id: 'project-gaussian-sequence-frame-file-field',
    path: 'src/services/project/types/schema.types.ts#ProjectGaussianSplatSequenceFrame.file',
    classification: 'delete now',
    ownerLane: 'project-hydration-adapter',
    deleteBy: 'P3_PROJECT_SCHEMA_BOUNDARY',
    replacementGate: 'P3_PROJECT_SCHEMA_BOUNDARY',
    note: 'Persisted gaussian sequence frames carry project/source paths only; projectLoad hydrates runtime File handles from raw project files or stored handles.',
  },
  {
    id: 'project-gaussian-sequence-frame-object-url',
    path: 'src/services/project/types/schema.types.ts#ProjectGaussianSplatSequenceFrame.splatUrl',
    classification: 'delete now',
    ownerLane: 'project-hydration-adapter',
    deleteBy: 'P3_PROJECT_SCHEMA_BOUNDARY',
    replacementGate: 'P3_PROJECT_SCHEMA_BOUNDARY',
    note: 'Persisted gaussian sequence frames do not carry object URLs; projectLoad creates runtime URLs as adapter outputs.',
  },
  {
    id: 'deprecated-ai-video-panel',
    path: 'src/types/dock.ts#ai-video',
    classification: 'delete at gate',
    ownerLane: 'media-flashboard',
    deleteBy: 'P3_DOCK_DEPRECATED_PANEL_PAYLOADS_RETIRED',
    replacementGate: 'P4_FLASHBOARD_RETIRED_BOARD_LEDGER',
    note: 'The old ai-video dock panel type is a retired payload candidate and must not drive active UI architecture.',
  },
  {
    id: 'deprecated-youtube-panel',
    path: 'src/types/dock.ts#youtube',
    classification: 'delete at gate',
    ownerLane: 'media-flashboard',
    deleteBy: 'P3_DOCK_DEPRECATED_PANEL_PAYLOADS_RETIRED',
    replacementGate: 'P4_DOWNLOADS_ACTIVE_IN_MEDIA_PANEL',
    note: 'The old youtube dock panel type must retire after active search/download workflow coverage lives in the Media Panel workflow.',
  },
  {
    id: 'deprecated-download-panel',
    path: 'src/types/dock.ts#download',
    classification: 'delete at gate',
    ownerLane: 'media-flashboard',
    deleteBy: 'P3_DOCK_DEPRECATED_PANEL_PAYLOADS_RETIRED',
    replacementGate: 'P4_DOWNLOADS_ACTIVE_IN_MEDIA_PANEL',
    note: 'The old download dock panel type must retire after the Media Panel download tray is the only active UI surface.',
  },
  {
    id: 'project-youtube-panel-payload',
    path: 'src/services/project/types/project.types.ts#ProjectFile.youtube',
    classification: 'delete now',
    ownerLane: 'project-hydration-adapter',
    deleteBy: 'P3_DEPRECATED_PAYLOADS_DELETED_OR_IGNORED',
    replacementGate: 'P3_DEPRECATED_PAYLOADS_DELETED_OR_IGNORED',
    note: 'The old YouTube panel state is not part of the current project schema; active downloads live in the Media/AI tools workflow.',
  },
  {
    id: 'project-youtube-panel-autosync',
    path: 'src/services/project/projectLifecycle.ts#YouTube autosync subscription',
    classification: 'delete now',
    ownerLane: 'project-hydration-adapter',
    deleteBy: 'P3_DEPRECATED_PAYLOADS_DELETED_OR_IGNORED',
    replacementGate: 'P3_DEPRECATED_PAYLOADS_DELETED_OR_IGNORED',
    note: 'YouTube search results are transient workflow state and no longer mark projects dirty.',
  },
  {
    id: 'flashboard-board-canvas-state',
    path: 'src/stores/flashboardStore/**#board-canvas-state',
    classification: 'delete at gate',
    ownerLane: 'media-flashboard',
    deleteBy: 'P4_FLASHBOARD_RETIRED_BOARD_LEDGER',
    replacementGate: 'P4_MEDIA_BOARD_VS_FLASHBOARD_BOARD_CLASSIFIED',
    note: 'Old FlashBoard board/canvas state is a retired-path candidate and requires a usage scan before deletion.',
  },
] as const satisfies readonly CompleteRetiredPathEntry[];
