import type { ShortcutActionId } from '../../../../services/shortcutTypes';
import type { TimelineToolGroupId, TimelineToolId, TimelineToolKind } from '../../../../stores/timeline/types';
import { TIMELINE_TOOL_ICONS, type TimelineToolIcon } from '../toolIcons';

export type TimelineToolPriority = 'P0' | 'P1' | 'P2';
export type TimelineToolAvailability = 'enabled' | 'future' | 'requires-source';

export interface TimelineToolDefinition {
  id: TimelineToolId;
  groupId: TimelineToolGroupId;
  kind: TimelineToolKind;
  label: string;
  description: string;
  icon: TimelineToolIcon;
  priority: TimelineToolPriority;
  availability: TimelineToolAvailability;
  mutatesTimeline: boolean;
  shortcutActionId?: ShortcutActionId;
  disabledReason?: string;
}

function tool(definition: Omit<TimelineToolDefinition, 'icon'>): TimelineToolDefinition {
  return {
    ...definition,
    icon: TIMELINE_TOOL_ICONS[definition.id],
  };
}

export const TIMELINE_TOOL_DEFINITIONS: TimelineToolDefinition[] = [
  tool({
    id: 'select',
    groupId: 'selection',
    kind: 'mode',
    label: 'Select / Move',
    description: 'Select, move, and edit clips with the standard timeline pointer.',
    priority: 'P0',
    availability: 'enabled',
    mutatesTimeline: false,
    shortcutActionId: 'tool.select',
  }),
  tool({
    id: 'track-select-forward',
    groupId: 'selection',
    kind: 'mode',
    label: 'Track Select Forward',
    description: 'Select clips from the click position to the right on the target track.',
    priority: 'P0',
    availability: 'enabled',
    mutatesTimeline: false,
    shortcutActionId: 'tool.trackSelectForward',
  }),
  tool({
    id: 'track-select-backward',
    groupId: 'selection',
    kind: 'mode',
    label: 'Track Select Backward',
    description: 'Select clips from the click position to the left on the target track.',
    priority: 'P1',
    availability: 'enabled',
    mutatesTimeline: false,
    shortcutActionId: 'tool.trackSelectBackward',
  }),
  tool({
    id: 'track-select-forward-all',
    groupId: 'selection',
    kind: 'mode',
    label: 'Track Select Forward All Tracks',
    description: 'Select clips from the click position to the right across unlocked visible tracks.',
    priority: 'P0',
    availability: 'enabled',
    mutatesTimeline: false,
    shortcutActionId: 'tool.trackSelectForwardAll',
  }),
  tool({
    id: 'range-select',
    groupId: 'selection',
    kind: 'mode',
    label: 'Range Selection',
    description: 'Draw a timeline time range across tracks for later lift, extract, or copy commands.',
    priority: 'P1',
    availability: 'enabled',
    mutatesTimeline: false,
    shortcutActionId: 'tool.rangeSelect',
  }),
  tool({
    id: 'blade',
    groupId: 'cut',
    kind: 'mode',
    label: 'Blade / Razor',
    description: 'Click a clip to split it at the pointer time.',
    priority: 'P0',
    availability: 'enabled',
    mutatesTimeline: true,
    shortcutActionId: 'tool.blade',
  }),
  tool({
    id: 'blade-all-tracks',
    groupId: 'cut',
    kind: 'mode',
    label: 'Blade All Tracks',
    description: 'Split every unlocked clip under the pointer time.',
    priority: 'P0',
    availability: 'enabled',
    mutatesTimeline: true,
    shortcutActionId: 'tool.bladeAllTracks',
  }),
  tool({
    id: 'glue',
    groupId: 'cut',
    kind: 'mode',
    label: 'Glue',
    description: 'Click a MIDI clip to merge it with the next clip on its track; Alt-click glues all following clips.',
    priority: 'P1',
    availability: 'enabled',
    mutatesTimeline: true,
    shortcutActionId: 'tool.glue',
  }),
  tool({
    id: 'split-at-playhead',
    groupId: 'cut',
    kind: 'command',
    label: 'Split at Playhead',
    description: 'Split selected clips, or clips under the playhead when no selection exists.',
    priority: 'P0',
    availability: 'enabled',
    mutatesTimeline: true,
    shortcutActionId: 'edit.splitAtPlayhead',
  }),
  tool({
    id: 'split-all-at-playhead',
    groupId: 'cut',
    kind: 'command',
    label: 'Split All Tracks at Playhead',
    description: 'Split all clips crossing the playhead on unlocked visible tracks.',
    priority: 'P0',
    availability: 'enabled',
    mutatesTimeline: true,
    shortcutActionId: 'edit.splitAllAtPlayhead',
  }),
  tool({
    id: 'trim-start-to-playhead',
    groupId: 'cut',
    kind: 'command',
    label: 'Trim Start to Playhead',
    description: 'Move the selected clip start edge to the playhead.',
    priority: 'P0',
    availability: 'enabled',
    mutatesTimeline: true,
    shortcutActionId: 'edit.trimStartToPlayhead',
  }),
  tool({
    id: 'trim-end-to-playhead',
    groupId: 'cut',
    kind: 'command',
    label: 'Trim End to Playhead',
    description: 'Move the selected clip end edge to the playhead.',
    priority: 'P0',
    availability: 'enabled',
    mutatesTimeline: true,
    shortcutActionId: 'edit.trimEndToPlayhead',
  }),
  tool({
    id: 'ripple-trim-start-to-playhead',
    groupId: 'cut',
    kind: 'command',
    label: 'Ripple Trim Start to Playhead',
    description: 'Trim the start edge to the playhead and close the affected gap.',
    priority: 'P1',
    availability: 'enabled',
    mutatesTimeline: true,
    shortcutActionId: 'edit.rippleTrimStartToPlayhead',
  }),
  tool({
    id: 'ripple-trim-end-to-playhead',
    groupId: 'cut',
    kind: 'command',
    label: 'Ripple Trim End to Playhead',
    description: 'Trim the end edge to the playhead and ripple following clips.',
    priority: 'P1',
    availability: 'enabled',
    mutatesTimeline: true,
    shortcutActionId: 'edit.rippleTrimEndToPlayhead',
  }),
  tool({
    id: 'ripple-delete',
    groupId: 'cut',
    kind: 'command',
    label: 'Ripple Delete',
    description: 'Delete the selected clips and close the gap on their tracks.',
    priority: 'P0',
    availability: 'enabled',
    mutatesTimeline: true,
    shortcutActionId: 'edit.rippleDelete',
  }),
  tool({
    id: 'delete-gap',
    groupId: 'cut',
    kind: 'command',
    label: 'Delete Gap',
    description: 'Close an empty gap at the playhead on unlocked visible tracks.',
    priority: 'P0',
    availability: 'enabled',
    mutatesTimeline: true,
    shortcutActionId: 'edit.deleteGap',
  }),
  tool({
    id: 'lift-range',
    groupId: 'cut',
    kind: 'command',
    label: 'Lift Range',
    description: 'Remove the selected timeline range and leave the gap in place.',
    priority: 'P1',
    availability: 'enabled',
    mutatesTimeline: true,
    shortcutActionId: 'edit.liftRange',
  }),
  tool({
    id: 'extract-range',
    groupId: 'cut',
    kind: 'command',
    label: 'Extract Range',
    description: 'Remove the selected timeline range and ripple following clips left.',
    priority: 'P1',
    availability: 'enabled',
    mutatesTimeline: true,
    shortcutActionId: 'edit.extractRange',
  }),
  tool({
    id: 'edge-trim',
    groupId: 'trim',
    kind: 'mode',
    label: 'Normal Edge Trim',
    description: 'Adjust clip in/out edges without rippling the timeline.',
    priority: 'P0',
    availability: 'enabled',
    mutatesTimeline: true,
    shortcutActionId: 'tool.edgeTrim',
  }),
  tool({
    id: 'ripple-trim',
    groupId: 'trim',
    kind: 'mode',
    label: 'Ripple Trim',
    description: 'Trim an edge and move following clips on the affected scope.',
    priority: 'P1',
    availability: 'enabled',
    mutatesTimeline: true,
    shortcutActionId: 'tool.rippleTrim',
  }),
  tool({
    id: 'rolling-edit',
    groupId: 'trim',
    kind: 'mode',
    label: 'Rolling Edit',
    description: 'Move an edit point between adjacent clips while preserving total duration.',
    priority: 'P1',
    availability: 'enabled',
    mutatesTimeline: true,
    shortcutActionId: 'tool.rollingEdit',
  }),
  tool({
    id: 'slip',
    groupId: 'trim',
    kind: 'mode',
    label: 'Slip',
    description: 'Keep the clip in place while changing the source in/out timing.',
    priority: 'P1',
    availability: 'enabled',
    mutatesTimeline: true,
    shortcutActionId: 'tool.slip',
  }),
  tool({
    id: 'slide',
    groupId: 'trim',
    kind: 'mode',
    label: 'Slide',
    description: 'Move a clip between neighbors while counter-trimming the adjacent clips.',
    priority: 'P2',
    availability: 'enabled',
    mutatesTimeline: true,
    shortcutActionId: 'tool.slide',
  }),
  tool({
    id: 'rate-stretch',
    groupId: 'trim',
    kind: 'mode',
    label: 'Rate Stretch',
    description: 'Change clip duration by adjusting playback speed.',
    priority: 'P2',
    availability: 'enabled',
    mutatesTimeline: true,
    shortcutActionId: 'tool.rateStretch',
  }),
  tool({
    id: 'position-overwrite',
    groupId: 'placement',
    kind: 'mode',
    label: 'Position / Overwrite Move',
    description: 'Place clips with overwrite or gap-aware collision policy.',
    priority: 'P1',
    availability: 'enabled',
    mutatesTimeline: true,
    shortcutActionId: 'tool.positionOverwrite',
  }),
  tool({
    id: 'insert',
    groupId: 'placement',
    kind: 'command',
    label: 'Insert',
    description: 'Insert the current source at the playhead and ripple later clips.',
    priority: 'P1',
    availability: 'requires-source',
    mutatesTimeline: true,
    shortcutActionId: 'edit.insertSource',
    disabledReason: 'Select a source first.',
  }),
  tool({
    id: 'overwrite',
    groupId: 'placement',
    kind: 'command',
    label: 'Overwrite',
    description: 'Place the current source at the playhead and overwrite the target range.',
    priority: 'P1',
    availability: 'requires-source',
    mutatesTimeline: true,
    shortcutActionId: 'edit.overwriteSource',
    disabledReason: 'Select a source first.',
  }),
  tool({
    id: 'replace',
    groupId: 'placement',
    kind: 'command',
    label: 'Replace',
    description: 'Replace the target clip with the current source.',
    priority: 'P2',
    availability: 'requires-source',
    mutatesTimeline: true,
    shortcutActionId: 'edit.replaceSource',
    disabledReason: 'Select a source first.',
  }),
  tool({
    id: 'fit-to-fill',
    groupId: 'placement',
    kind: 'command',
    label: 'Fit to Fill',
    description: 'Fit source material into a target range by adjusting speed.',
    priority: 'P2',
    availability: 'requires-source',
    mutatesTimeline: true,
    shortcutActionId: 'edit.fitToFillSource',
    disabledReason: 'Select a source first.',
  }),
  tool({
    id: 'append-at-end',
    groupId: 'placement',
    kind: 'command',
    label: 'Append at End',
    description: 'Append the current source to the end of the sequence.',
    priority: 'P2',
    availability: 'requires-source',
    mutatesTimeline: true,
    shortcutActionId: 'edit.appendSourceAtEnd',
    disabledReason: 'Select a source first.',
  }),
  tool({
    id: 'place-on-top',
    groupId: 'placement',
    kind: 'command',
    label: 'Place on Top',
    description: 'Place the current source on an upper free video track.',
    priority: 'P2',
    availability: 'requires-source',
    mutatesTimeline: true,
    shortcutActionId: 'edit.placeSourceOnTop',
    disabledReason: 'Select a source first.',
  }),
  tool({
    id: 'ripple-overwrite',
    groupId: 'placement',
    kind: 'command',
    label: 'Ripple Overwrite',
    description: 'Overwrite a target range and ripple the remaining tail.',
    priority: 'P2',
    availability: 'requires-source',
    mutatesTimeline: true,
    shortcutActionId: 'edit.rippleOverwriteSource',
    disabledReason: 'Select a source first.',
  }),
  tool({
    id: 'hand',
    groupId: 'navigation',
    kind: 'mode',
    label: 'Hand / Pan',
    description: 'Pan the timeline surface by dragging.',
    priority: 'P2',
    availability: 'enabled',
    mutatesTimeline: false,
    shortcutActionId: 'tool.hand',
  }),
  tool({
    id: 'zoom',
    groupId: 'navigation',
    kind: 'mode',
    label: 'Zoom',
    description: 'Zoom in or out around the pointer or a dragged range.',
    priority: 'P2',
    availability: 'enabled',
    mutatesTimeline: false,
    shortcutActionId: 'tool.zoom',
  }),
  tool({
    id: 'marker',
    groupId: 'navigation',
    kind: 'command',
    label: 'Marker',
    description: 'Add a marker at the playhead or clicked timeline position.',
    priority: 'P1',
    availability: 'enabled',
    mutatesTimeline: true,
    shortcutActionId: 'edit.addMarker',
  }),
  tool({
    id: 'in-point',
    groupId: 'navigation',
    kind: 'command',
    label: 'In Point',
    description: 'Set the sequence in point from the playhead or clicked position.',
    priority: 'P1',
    availability: 'enabled',
    mutatesTimeline: false,
    shortcutActionId: 'edit.setIn',
  }),
  tool({
    id: 'out-point',
    groupId: 'navigation',
    kind: 'command',
    label: 'Out Point',
    description: 'Set the sequence out point from the playhead or clicked position.',
    priority: 'P1',
    availability: 'enabled',
    mutatesTimeline: false,
    shortcutActionId: 'edit.setOut',
  }),
  tool({
    id: 'pen-keyframe',
    groupId: 'navigation',
    kind: 'mode',
    label: 'Pen / Keyframe',
    description: 'Place and edit keyframes directly on supported timeline lanes.',
    priority: 'P1',
    availability: 'enabled',
    mutatesTimeline: true,
    shortcutActionId: 'tool.penKeyframe',
  }),
  tool({
    id: 'midi-draw',
    groupId: 'navigation',
    kind: 'mode',
    label: 'MIDI Pencil',
    description: 'Draw MIDI clip regions on a MIDI track by click-dragging on empty lane space.',
    priority: 'P1',
    availability: 'enabled',
    mutatesTimeline: true,
    shortcutActionId: 'tool.midiDraw',
  }),
];

export const TIMELINE_TOOL_DEFINITION_BY_ID = Object.fromEntries(
  TIMELINE_TOOL_DEFINITIONS.map((definition) => [definition.id, definition]),
) as Record<TimelineToolId, TimelineToolDefinition>;
