import type { TransitionDefinition } from '../types';

export const vignetteBloom: TransitionDefinition = {
  id: 'vignette-bloom',
  name: 'Vignette Bloom',
  category: 'light',
  defaultDuration: 1.1,
  minDuration: 0.1,
  maxDuration: 5,
  description: 'Soft glow and edge vignette hide the cut',
  recipe: [
    {
      kind: 'opacity',
      target: 'outgoing',
      from: 1,
      to: 0,
      startProgress: 0.2,
      endProgress: 0.78,
      curve: 'ease-in',
    },
    {
      kind: 'opacity',
      target: 'incoming',
      from: 0,
      to: 1,
      startProgress: 0.22,
      endProgress: 0.84,
      curve: 'ease-out',
    },
    {
      kind: 'effect',
      target: 'outgoing',
      effectType: 'glow',
      effectName: 'Glow',
      params: {
        amount: { from: 0.2, to: 2.2 },
        threshold: { from: 0.78, to: 0.42 },
        radius: { from: 18, to: 44 },
        softness: 0.65,
        rings: 3,
        samplesPerRing: 10,
      },
      startProgress: 0,
      endProgress: 0.7,
      curve: 'ease-in',
    },
    {
      kind: 'effect',
      target: 'incoming',
      effectType: 'glow',
      effectName: 'Glow',
      params: {
        amount: { from: 2.2, to: 0.2 },
        threshold: { from: 0.42, to: 0.78 },
        radius: { from: 44, to: 18 },
        softness: 0.65,
        rings: 3,
        samplesPerRing: 10,
      },
      startProgress: 0.3,
      endProgress: 1,
      curve: 'ease-out',
    },
    {
      kind: 'effect',
      target: 'outgoing',
      effectType: 'vignette',
      effectName: 'Vignette',
      params: {
        amount: { from: 0.12, to: 0.72 },
        size: { from: 0.82, to: 0.58 },
        softness: 0.78,
        roundness: 1,
      },
      startProgress: 0,
      endProgress: 0.72,
      curve: 'ease-in',
    },
    {
      kind: 'effect',
      target: 'incoming',
      effectType: 'vignette',
      effectName: 'Vignette',
      params: {
        amount: { from: 0.72, to: 0.12 },
        size: { from: 0.58, to: 0.82 },
        softness: 0.78,
        roundness: 1,
      },
      startProgress: 0.28,
      endProgress: 1,
      curve: 'ease-out',
    },
  ],
};
