import type { Messages } from './keys';

export const enUS = {
  'app.name': 'Atlas', 'app.product': 'Firefly', 'app.tagline': 'Shape footage naturally on the timeline',
  'app.backToFirefly': 'Back to Firefly', 'app.account': 'Current account', 'app.retry': 'Retry', 'app.loading': 'Loading', 'app.offline': 'Offline', 'app.close': 'Close', 'app.cancel': 'Cancel', 'app.confirm': 'Confirm', 'app.save': 'Save', 'app.delete': 'Delete', 'app.rename': 'Rename', 'app.more': 'More', 'app.search': 'Search', 'app.notAvailable': 'Unavailable',
  'bootstrap.title': 'Entering Atlas', 'bootstrap.body': 'Restoring your account, projects, and local workspace.', 'bootstrap.failedTitle': 'Atlas is temporarily unavailable', 'bootstrap.failedBody': 'Your session could not be verified. Check the network and try again.',
  'browser.unsupportedTitle': 'Use the latest Chrome or Edge', 'browser.unsupportedBody': 'This browser is missing local media capabilities. You can view projects, but preview or export may not work.', 'browser.continueAnyway': 'Continue anyway',
  'projects.title': 'Your editing projects', 'projects.subtitle': 'Edit locally at full speed while Firefly safely archives project checkpoints.', 'projects.new': 'New project', 'projects.newName': 'Untitled edit', 'projects.emptyTitle': 'Start with your first piece of media', 'projects.emptyBody': 'Create a project, then add local media or choose from Firefly assets.', 'projects.open': 'Open project', 'projects.restore': 'Restore checkpoint', 'projects.updated': 'Last edited', 'projects.localDraft': 'Local draft', 'projects.cloudReady': 'Cloud backup ready', 'projects.renameTitle': 'Rename project', 'projects.deleteTitle': 'Delete this project?', 'projects.deleteBody': 'The project will disappear from the list. Archived media will be cleaned up safely in the background.', 'projects.deleteConfirm': 'Delete project', 'projects.operationFailed': 'The project action failed. Try again.',
  'workspace.back': 'All projects', 'workspace.saved': 'Saved', 'workspace.saving': 'Saving', 'workspace.localSaved': 'Saved locally', 'workspace.saveFailed': 'Cloud save failed; your local draft is safe', 'workspace.conflictTitle': 'A newer project version exists', 'workspace.conflictBody': 'Another window or device updated this project. Your local draft was not overwritten.', 'workspace.reloadCloud': 'Load cloud version', 'workspace.keepCopy': 'Save a copy', 'workspace.takeOver': 'Take over editing', 'workspace.readOnly': 'Read only', 'workspace.editor': 'Editing', 'workspace.undo': 'Undo', 'workspace.redo': 'Redo', 'workspace.export': 'Export',
  'media.title': 'Project media', 'media.importLocal': 'Local media', 'media.importLibrary': 'Asset library', 'media.localHint': 'Select multiple files; previews appear immediately', 'media.emptyTitle': 'No media yet', 'media.emptyBody': 'Choose video, images, or audio from this device.', 'media.loading': 'Reading', 'media.uploading': 'Archiving', 'media.ready': 'Ready', 'media.failed': 'Processing failed', 'media.retryUpload': 'Retry archive', 'media.reconnect': 'Relink source file', 'media.reconnectRequired': 'The local source is no longer available. Select the media again.', 'media.fileTooLarge': 'The file exceeds the 8 GiB limit and was not uploaded.', 'media.unsupportedFile': 'An unrecognized file was skipped.', 'media.addTimeline': 'Add to timeline', 'media.libraryTitle': 'Firefly asset library', 'media.libraryHint': 'Imported media receives a project-owned copy.', 'media.libraryEmpty': 'No importable assets found.', 'media.import': 'Import', 'media.imported': 'Imported', 'media.importFailed': 'Could not import this asset. Try again.', 'media.libraryLoadFailed': 'The asset library is temporarily unavailable. Try again.', 'media.libraryPartial': 'Some assets could not be loaded. Available items are shown.', 'media.image': 'Image', 'media.video': 'Video', 'media.audio': 'Audio',
  'preview.title': 'Preview', 'preview.emptyTitle': 'Select media or a clip', 'preview.emptyBody': 'The current selection appears here. Editing never waits on the cloud.', 'preview.play': 'Play', 'preview.pause': 'Pause', 'preview.transitioning': 'Transition preview', 'preview.unsupported': 'This browser cannot decode the original. Use the H.264 preview version.', 'preview.downloadOriginal': 'Open source file',
  'timeline.title': 'Timeline', 'timeline.playhead': 'Playhead', 'timeline.addTrack': 'Add track', 'timeline.videoTrack': 'Video', 'timeline.audioTrack': 'Audio', 'timeline.empty': 'Drag media here or choose “Add to timeline”', 'timeline.split': 'Split at playhead', 'timeline.delete': 'Delete clip', 'timeline.mute': 'Mute', 'timeline.unmute': 'Unmute', 'timeline.locked': 'Track locked', 'timeline.lock': 'Lock track', 'timeline.unlock': 'Unlock track', 'timeline.clip': 'Clip',
  'inspector.title': 'Clip settings', 'inspector.noSelection': 'Select a timeline clip to adjust trim, volume, and transitions.', 'inspector.trim': 'Trim', 'inspector.start': 'In', 'inspector.end': 'Out', 'inspector.volume': 'Volume', 'inspector.transform': 'Visual transform', 'inspector.position': 'Position', 'inspector.scale': 'Scale', 'inspector.rotation': 'Rotation', 'inspector.transition': 'Incoming transition', 'inspector.transitionNone': 'No transition', 'inspector.crossfade': 'Crossfade', 'inspector.wipeLeft': 'Wipe left', 'inspector.wipeRight': 'Wipe right', 'inspector.wipeUp': 'Wipe up', 'inspector.wipeDown': 'Wipe down', 'inspector.dipBlack': 'Dip to black',
  'export.title': 'Export video', 'export.subtitle': 'Encoding runs in your browser and uploads directly to Beijing TOS.', 'export.format': 'Format', 'export.resolution': 'Resolution', 'export.frameRate': 'Frame rate', 'export.preflight': 'Export capability check', 'export.refresh': 'Check again', 'export.webCodecs': 'Local media encoding', 'export.h264': 'H.264 encoder', 'export.audio': 'Audio encoder', 'export.isolation': 'High-performance isolation', 'export.storage': 'Available local space', 'export.supported': 'Available', 'export.unsupported': 'Unavailable', 'export.unknown': 'Not checked', 'export.ready': 'Ready to export', 'export.blocked': 'This environment cannot export', 'export.start': 'Start export', 'export.notReadyBody': 'Resolve the unavailable browser capabilities first. Your project remains safe.', 'export.preparing': 'Preparing media', 'export.encoding': 'Encoding locally', 'export.uploading': 'Uploading directly to TOS', 'export.finalizing': 'Verifying output', 'export.completed': 'Output archived to your assets', 'export.failed': 'Export did not finish; your timeline is unchanged', 'export.cancel': 'Cancel export',
  'agent.title': 'Atlas Agent', 'agent.subtitle': 'Turn editing intent into reviewable atomic operations.', 'agent.placeholder': 'For example: arrange the first three clips to the rhythm and leave breathing room at each cut…', 'agent.send': 'Create edit plan', 'agent.connecting': 'Connecting', 'agent.thinking': 'Reading the timeline', 'agent.planReady': 'Edit plan ready', 'agent.applyPlan': 'Apply plan', 'agent.confirmPlan': 'Confirm and apply', 'agent.cancelRun': 'Stop', 'agent.emptyTitle': 'Organize the timeline with natural language', 'agent.emptyBody': 'Agent only proposes allowlisted operations. Every step is checked in the browser and can be undone as one action.', 'agent.failed': 'Agent could not complete this plan', 'agent.completed': 'Plan applied', 'agent.operationCount': 'operations', 'agent.destructiveWarning': 'This plan includes deletion or export and needs confirmation.', 'agent.unsupportedOperation': 'The plan contains an unsupported operation. No changes were applied.', 'agent.stalePlan': 'The timeline changed while this plan was being prepared. Nothing was applied; create a new plan.', 'agent.retryReceipt': 'Sync result', 'agent.discardPlan': 'Discard plan', 'agent.cancelled': 'This plan was stopped', 'agent.errorTimeout': 'Agent timed out. Try again shortly.', 'agent.errorRateLimited': 'Agent is busy. Try again shortly.', 'agent.toolSplit': 'Split clip', 'agent.toolTrim': 'Trim clip', 'agent.toolMove': 'Move clip', 'agent.toolReorder': 'Reorder clips', 'agent.toolDelete': 'Delete clip', 'agent.toolInsert': 'Insert project media', 'agent.toolCreateTrack': 'Create track', 'agent.toolTrackMute': 'Set track mute', 'agent.toolVolume': 'Adjust volume', 'agent.toolTransform': 'Adjust picture', 'agent.toolAddTransition': 'Add transition', 'agent.toolRemoveTransition': 'Remove transition', 'agent.toolExport': 'Request export',
  'notice.localFirst': 'Local first · Cloud recovery', 'notice.desktopOnly': 'Atlas editing currently supports desktop Chrome and Edge only.', 'notice.storageDenied': 'Persistent storage permission was not granted. Keep this tab open until cloud save completes.',
  'shortcut.title': 'Shortcuts', 'shortcut.undo': 'Undo', 'shortcut.redo': 'Redo', 'shortcut.delete': 'Delete clip', 'shortcut.split': 'Split clip',
} satisfies Messages;
