import type { TransitionDefinition } from '../types';

export const filmRoll: TransitionDefinition = {
  id: 'film-roll',
  name: 'Film Roll',
  category: 'light',
  defaultDuration: 0.9,
  minDuration: 0.1,
  maxDuration: 4,
  description: 'Vertical film-roll movement through the cut with motion blur',
  recipe: [
    {
      kind: 'opacity',
      target: 'outgoing',
      from: 1,
      to: 0,
      startProgress: 0.2,
      endProgress: 0.72,
      curve: 'ease-in',
    },
    {
      kind: 'opacity',
      target: 'incoming',
      from: 0,
      to: 1,
      startProgress: 0.28,
      endProgress: 0.84,
      curve: 'ease-out',
    },
    {
      kind: 'transform',
      target: 'outgoing',
      translateY: { from: 0, to: -0.18 },
      scaleX: { from: 1, to: 1.1 },
      scaleY: { from: 1, to: 1.28 },
      startProgress: 0,
      endProgress: 0.72,
      curve: 'ease-in',
    },
    {
      kind: 'transform',
      target: 'incoming',
      translateY: { from: 0.18, to: 0 },
      scaleX: { from: 1.1, to: 1 },
      scaleY: { from: 1.28, to: 1 },
      startProgress: 0.28,
      endProgress: 1,
      curve: 'ease-out',
    },
    {
      kind: 'effect',
      target: 'outgoing',
      effectType: 'motion-blur',
      effectName: 'Motion Blur',
      params: {
        amount: { from: 0, to: 0.1 },
        angle: 1.5708,
        samples: 32,
      },
      startProgress: 0,
      endProgress: 0.72,
      curve: 'ease-in',
    },
    {
      kind: 'effect',
      target: 'incoming',
      effectType: 'motion-blur',
      effectName: 'Motion Blur',
      params: {
        amount: { from: 0.1, to: 0 },
        angle: 1.5708,
        samples: 32,
      },
      startProgress: 0.28,
      endProgress: 1,
      curve: 'ease-out',
    },
  ],
};
