import type { TransitionDefinition } from '../types';

// A generated transparent light-band overlay sweeps across the cut.
export const lightSweep: TransitionDefinition = {
  id: 'light-sweep',
  name: 'Light Sweep',
  category: 'light',
  defaultDuration: 1.1,
  minDuration: 0.1,
  maxDuration: 5,
  description: 'A deterministic diagonal highlight band sweeps across the cut',
  params: {
    color: {
      type: 'color',
      label: 'Color',
      defaultValue: '#fff7d2',
    },
  },
  recipe: [
    {
      kind: 'opacity',
      target: 'outgoing',
      from: 1,
      to: 0,
      startProgress: 0.15,
      endProgress: 0.78,
      curve: 'ease-in',
    },
    {
      kind: 'opacity',
      target: 'incoming',
      from: 0,
      to: 1,
      startProgress: 0.2,
      endProgress: 0.86,
      curve: 'ease-out',
    },
    {
      kind: 'overlay',
      overlay: 'light-sweep',
      color: '#fff7d2',
      colorParam: 'color',
      blendMode: 'screen',
      opacity: { from: 0, to: 0.92 },
      centerX: { from: -0.28, to: 1.28 },
      width: 0.18,
      softness: 0.32,
      angle: -0.38,
      startProgress: 0.08,
      endProgress: 0.82,
      curve: 'ease-in-out',
    },
    {
      kind: 'overlay',
      overlay: 'light-sweep',
      color: '#fff7d2',
      colorParam: 'color',
      blendMode: 'screen',
      opacity: { from: 0.42, to: 0 },
      centerX: { from: 0.55, to: 1.42 },
      width: 0.32,
      softness: 0.44,
      angle: -0.38,
      startProgress: 0.5,
      endProgress: 1,
      curve: 'ease-out',
    },
  ],
};
