import type { TransitionDefinition } from '../types';

// Chromatic analog leak with deterministic red/cyan edge streaks.
export const chromaLeak: TransitionDefinition = {
  id: 'chroma-leak',
  name: 'Chroma Leak',
  category: 'light',
  defaultDuration: 1.1,
  minDuration: 0.1,
  maxDuration: 5,
  description: 'Chromatic color leak and split streaks wash across the cut',
  params: {
    color: {
      type: 'color',
      label: 'Color',
      defaultValue: '#ff3b8f',
    },
  },
  recipe: [
    {
      kind: 'opacity',
      target: 'outgoing',
      from: 1,
      to: 0,
      startProgress: 0.18,
      endProgress: 0.86,
      curve: 'ease-in',
    },
    {
      kind: 'opacity',
      target: 'incoming',
      from: 0,
      to: 1,
      startProgress: 0.14,
      endProgress: 0.82,
      curve: 'ease-out',
    },
    {
      kind: 'overlay',
      overlay: 'chroma-leak',
      color: '#ff3b8f',
      colorParam: 'color',
      blendMode: 'normal',
      opacity: { from: 0, to: 0.58 },
      centerX: { from: -0.18, to: 0.48 },
      width: 0.42,
      softness: 0.3,
      angle: 0.16,
      startProgress: 0,
      endProgress: 0.6,
      curve: 'ease-out',
    },
    {
      kind: 'overlay',
      overlay: 'chroma-leak',
      color: '#ff3b8f',
      colorParam: 'color',
      blendMode: 'normal',
      opacity: { from: 0.42, to: 0 },
      centerX: { from: 0.38, to: 1.1 },
      width: 0.36,
      softness: 0.36,
      angle: -0.12,
      startProgress: 0.44,
      endProgress: 1,
      curve: 'ease-in',
    },
  ],
};
