import type { CatalogEntry } from './types';
import { DEFAULT_ELEVENLABS_MODEL_ID } from '../../stores/flashboardStore/defaults';
import { DEFAULT_SUNO_MODEL_ID, SUNO_MODEL_IDS, SUNO_PROVIDER_ID, SUNO_SOUNDS_PROVIDER_ID } from '../sunoContracts';
import {
  FLUX_KONTEXT_MAX_PROVIDER_ID,
  FLUX_KONTEXT_PRO_PROVIDER_ID,
  KLING_3_ASPECT_RATIOS,
  KLING_3_DURATIONS,
  KLING_3_MODES,
  RECRAFT_CRISP_UPSCALE_PROVIDER_ID,
  RECRAFT_REMOVE_BACKGROUND_PROVIDER_ID,
  RUNWAY_ASPECT_RATIOS,
  RUNWAY_VIDEO_PROVIDER_ID,
  SEEDANCE_2_ASPECT_RATIOS,
  TOPAZ_IMAGE_UPSCALE_PROVIDER_ID,
  TOPAZ_VIDEO_UPSCALE_PROVIDER_ID,
  VEO_3_1_PROVIDER_ID,
} from '../kieAi/config';

const NANO_BANANA_ASPECT_RATIOS = ['auto', '1:1', '1:4', '1:8', '2:3', '3:2', '3:4', '4:1', '4:3', '4:5', '5:4', '8:1', '9:16', '16:9', '21:9'];
const GPT_IMAGE_2_ASPECT_RATIOS = ['auto', '1:1', '3:2', '2:3', '4:3', '3:4', '16:9', '9:16', '2:1', '1:2', '3:1', '1:3', '21:9', '9:21', '5:4', '4:5'];
const FLUX_2_TEXT_ASPECT_RATIOS = ['1:1', '4:3', '3:4', '16:9', '9:16', '3:2', '2:3'];
const FLUX_2_IMAGE_ASPECT_RATIOS = [...FLUX_2_TEXT_ASPECT_RATIOS, 'auto'];
const SEEDREAM_5_LITE_ASPECT_RATIOS = ['1:1', '4:3', '3:4', '16:9', '9:16', '2:3', '3:2', '21:9'];
const FLUX_KONTEXT_ASPECT_RATIOS = ['16:9', '21:9', '4:3', '1:1', '3:4', '9:16', '16:21'];
const NANO_BANANA_IMAGE_SIZES = ['1K', '2K', '4K'];
const KLING_MODE_LABELS = { std: '720p', pro: '1080p', '4K': '4K' };
const VEO_MODE_LABELS = { veo3_fast: 'Fast', veo3: 'Quality', veo3_lite: 'Lite' };
const HOSTED_KIE_IMAGE_ENTRIES: CatalogEntry[] = [
  {
    service: 'cloud',
    providerId: 'nano-banana-2',
    name: 'Nano Banana 2',
    description: 'Image generation via Kie.ai with up to 14 ordered reference images',
    versions: ['3.1'],
    modes: [],
    durations: [],
    aspectRatios: NANO_BANANA_ASPECT_RATIOS,
    supportsTextToVideo: false,
    supportsImageToVideo: false,
    supportsTextToImage: true,
    supportsGenerateAudio: false,
    supportsMultiShot: false,
    imageSizes: NANO_BANANA_IMAGE_SIZES,
    maxReferenceImages: 14,
    maxReferenceMedia: 14,
    outputType: 'image',
    promptRefinerProfile: 'nano-banana',
  },
  {
    service: 'cloud',
    providerId: 'nano-banana-pro',
    name: 'Nano Banana Pro',
    description: 'Higher-fidelity Nano Banana image generation via Kie.ai',
    versions: ['latest'],
    modes: [],
    durations: [],
    aspectRatios: NANO_BANANA_ASPECT_RATIOS,
    supportsTextToVideo: false,
    supportsImageToVideo: false,
    supportsTextToImage: true,
    supportsGenerateAudio: false,
    supportsMultiShot: false,
    imageSizes: NANO_BANANA_IMAGE_SIZES,
    maxReferenceImages: 14,
    maxReferenceMedia: 14,
    outputType: 'image',
    promptRefinerProfile: 'nano-banana',
  },
  {
    service: 'cloud',
    providerId: 'gpt-image-2-text-to-image',
    name: 'GPT Image 2',
    description: 'GPT Image 2 text-to-image generation via Kie.ai',
    versions: ['latest'],
    modes: [],
    durations: [],
    aspectRatios: GPT_IMAGE_2_ASPECT_RATIOS,
    supportsTextToVideo: false,
    supportsImageToVideo: false,
    supportsTextToImage: true,
    supportsGenerateAudio: false,
    supportsMultiShot: false,
    outputType: 'image',
    promptRefinerProfile: 'gpt-image',
  },
  {
    service: 'cloud',
    providerId: 'gpt-image-2-image-to-image',
    name: 'GPT Image 2 Edit',
    description: 'GPT Image 2 image-to-image editing via Kie.ai',
    versions: ['latest'],
    modes: [],
    durations: [],
    aspectRatios: GPT_IMAGE_2_ASPECT_RATIOS,
    supportsTextToVideo: false,
    supportsImageToVideo: false,
    supportsTextToImage: true,
    supportsGenerateAudio: false,
    supportsMultiShot: false,
    maxReferenceImages: 16,
    maxReferenceMedia: 16,
    outputType: 'image',
    promptRefinerProfile: 'gpt-image-edit',
    requiresReferenceMedia: true,
  },
  {
    service: 'cloud',
    providerId: 'flux-2/pro-text-to-image',
    name: 'Flux 2 Pro',
    description: 'Flux 2 Pro text-to-image generation via Kie.ai',
    versions: ['latest'],
    modes: [],
    durations: [],
    aspectRatios: FLUX_2_TEXT_ASPECT_RATIOS,
    supportsTextToVideo: false,
    supportsImageToVideo: false,
    supportsTextToImage: true,
    supportsGenerateAudio: false,
    supportsMultiShot: false,
    imageSizes: ['1K', '2K', '4K'],
    outputType: 'image',
    promptRefinerProfile: 'flux',
  },
  {
    service: 'cloud',
    providerId: 'flux-2/pro-image-to-image',
    name: 'Flux 2 Pro Edit',
    description: 'Flux 2 Pro image-to-image editing via Kie.ai',
    versions: ['latest'],
    modes: [],
    durations: [],
    aspectRatios: FLUX_2_IMAGE_ASPECT_RATIOS,
    supportsTextToVideo: false,
    supportsImageToVideo: false,
    supportsTextToImage: true,
    supportsGenerateAudio: false,
    supportsMultiShot: false,
    imageSizes: ['1K', '2K', '4K'],
    maxReferenceImages: 8,
    maxReferenceMedia: 8,
    outputType: 'image',
    promptRefinerProfile: 'flux-edit',
    requiresReferenceMedia: true,
  },
  {
    service: 'cloud',
    providerId: 'seedream/5-lite-text-to-image',
    name: 'Seedream 5 Lite',
    description: 'Seedream 5 Lite text-to-image generation via Kie.ai',
    versions: ['latest'],
    modes: [],
    durations: [],
    aspectRatios: SEEDREAM_5_LITE_ASPECT_RATIOS,
    supportsTextToVideo: false,
    supportsImageToVideo: false,
    supportsTextToImage: true,
    supportsGenerateAudio: false,
    supportsMultiShot: false,
    outputType: 'image',
    promptRefinerProfile: 'seedream-image',
  },
  {
    service: 'cloud',
    providerId: 'seedream/5-lite-image-to-image',
    name: 'Seedream 5 Lite Edit',
    description: 'Seedream 5 Lite image-to-image editing via Kie.ai',
    versions: ['latest'],
    modes: [],
    durations: [],
    aspectRatios: SEEDREAM_5_LITE_ASPECT_RATIOS,
    supportsTextToVideo: false,
    supportsImageToVideo: false,
    supportsTextToImage: true,
    supportsGenerateAudio: false,
    supportsMultiShot: false,
    maxReferenceImages: 14,
    maxReferenceMedia: 14,
    outputType: 'image',
    promptRefinerProfile: 'seedream-edit',
    requiresReferenceMedia: true,
  },
  {
    service: 'cloud',
    providerId: FLUX_KONTEXT_PRO_PROVIDER_ID,
    name: 'Flux Kontext Pro',
    description: 'Flux Kontext image generation and single-image editing via Kie.ai',
    versions: ['latest'],
    modes: [],
    durations: [],
    aspectRatios: FLUX_KONTEXT_ASPECT_RATIOS,
    supportsTextToVideo: false,
    supportsImageToVideo: false,
    supportsTextToImage: true,
    supportsGenerateAudio: false,
    supportsMultiShot: false,
    maxReferenceImages: 1,
    maxReferenceMedia: 1,
    outputType: 'image',
    promptRefinerProfile: 'flux-kontext',
    requiredReferenceMediaType: 'image',
  },
  {
    service: 'cloud',
    providerId: FLUX_KONTEXT_MAX_PROVIDER_ID,
    name: 'Flux Kontext Max',
    description: 'Higher-quality Flux Kontext image generation and editing via Kie.ai',
    versions: ['latest'],
    modes: [],
    durations: [],
    aspectRatios: FLUX_KONTEXT_ASPECT_RATIOS,
    supportsTextToVideo: false,
    supportsImageToVideo: false,
    supportsTextToImage: true,
    supportsGenerateAudio: false,
    supportsMultiShot: false,
    maxReferenceImages: 1,
    maxReferenceMedia: 1,
    outputType: 'image',
    promptRefinerProfile: 'flux-kontext',
    requiredReferenceMediaType: 'image',
  },
  {
    service: 'cloud',
    providerId: RECRAFT_REMOVE_BACKGROUND_PROVIDER_ID,
    name: 'Recraft Remove Background',
    description: 'Remove image backgrounds via Kie.ai',
    versions: ['latest'],
    modes: [],
    durations: [],
    aspectRatios: [],
    supportsTextToVideo: false,
    supportsImageToVideo: false,
    supportsTextToImage: true,
    supportsGenerateAudio: false,
    supportsMultiShot: false,
    maxReferenceImages: 1,
    maxReferenceMedia: 1,
    outputType: 'image',
    promptRefinerProfile: 'utility-image',
    requiredReferenceMediaType: 'image',
    requiresPrompt: false,
    requiresReferenceMedia: true,
  },
  {
    service: 'cloud',
    providerId: RECRAFT_CRISP_UPSCALE_PROVIDER_ID,
    name: 'Recraft Crisp Upscale',
    description: 'Crisp image upscaling via Kie.ai',
    versions: ['latest'],
    modes: [],
    durations: [],
    aspectRatios: [],
    supportsTextToVideo: false,
    supportsImageToVideo: false,
    supportsTextToImage: true,
    supportsGenerateAudio: false,
    supportsMultiShot: false,
    maxReferenceImages: 1,
    maxReferenceMedia: 1,
    outputType: 'image',
    promptRefinerProfile: 'utility-image',
    requiredReferenceMediaType: 'image',
    requiresPrompt: false,
    requiresReferenceMedia: true,
  },
  {
    service: 'cloud',
    providerId: TOPAZ_IMAGE_UPSCALE_PROVIDER_ID,
    name: 'Topaz Image Upscale',
    description: 'Topaz image upscaling via Kie.ai',
    versions: ['latest'],
    modes: [],
    durations: [],
    aspectRatios: [],
    supportsTextToVideo: false,
    supportsImageToVideo: false,
    supportsTextToImage: true,
    supportsGenerateAudio: false,
    supportsMultiShot: false,
    imageSizes: ['2x', '4x'],
    maxReferenceImages: 1,
    maxReferenceMedia: 1,
    outputType: 'image',
    promptRefinerProfile: 'utility-image',
    requiredReferenceMediaType: 'image',
    requiresPrompt: false,
    requiresReferenceMedia: true,
  },
];

export function getCatalogEntries(): CatalogEntry[] {
  const entries: CatalogEntry[] = [];

  entries.push({
    service: 'cloud',
    providerId: 'cloud-elevenlabs-tts',
    name: 'ElevenLabs',
    description: 'Hosted text-to-speech generation via MasterSelects Cloud credits',
    versions: [DEFAULT_ELEVENLABS_MODEL_ID],
    modes: [],
    durations: [],
    aspectRatios: [],
    supportsTextToVideo: false,
    supportsImageToVideo: false,
    supportsTextToImage: false,
    supportsTextToAudio: true,
    supportsGenerateAudio: false,
    supportsMultiShot: false,
    outputType: 'audio',
  });

  entries.push({
    service: 'cloud',
    providerId: SUNO_PROVIDER_ID,
    name: 'Suno',
    description: 'Hosted text-to-music generation via MasterSelects Cloud credits',
    versions: [DEFAULT_SUNO_MODEL_ID, ...SUNO_MODEL_IDS.filter((model) => model !== DEFAULT_SUNO_MODEL_ID)],
    modes: [],
    durations: [],
    aspectRatios: [],
    supportsTextToVideo: false,
    supportsImageToVideo: false,
    supportsTextToImage: false,
    supportsTextToAudio: true,
    supportsGenerateAudio: false,
    supportsMultiShot: false,
    outputType: 'audio',
  });

  entries.push({
    service: 'cloud',
    providerId: SUNO_SOUNDS_PROVIDER_ID,
    name: 'Suno Sounds',
    description: 'Hosted text-to-sound generation via MasterSelects Cloud',
    versions: [DEFAULT_SUNO_MODEL_ID, ...SUNO_MODEL_IDS.filter((model) => model !== DEFAULT_SUNO_MODEL_ID)],
    modes: ['one-shot', 'loop'],
    durations: [],
    aspectRatios: [],
    supportsTextToVideo: false,
    supportsImageToVideo: false,
    supportsTextToImage: false,
    supportsTextToAudio: true,
    supportsGenerateAudio: false,
    supportsMultiShot: false,
    outputType: 'audio',
    promptRefinerProfile: 'suno-sounds',
  });

  entries.push({
    service: 'cloud',
    providerId: 'cloud-kling',
    name: 'Kling',
    description: 'Hosted Kling via MasterSelects Cloud',
    versions: ['latest'],
    modes: KLING_3_MODES,
    modeLabels: KLING_MODE_LABELS,
    modeControlLabel: 'Resolution',
    durations: KLING_3_DURATIONS,
    aspectRatios: KLING_3_ASPECT_RATIOS,
    referenceInputKinds: ['start-frame', 'end-frame', 'image-reference', 'video-reference'],
    supportsTextToVideo: true,
    supportsImageToVideo: true,
    supportsGenerateAudio: true,
    supportsMultiShot: true,
    maxReferenceMedia: 3,
    outputType: 'video',
  });

  entries.push({
    service: 'cloud',
    providerId: 'bytedance/seedance-2',
    name: 'Seedance 2.0',
    description: 'Hosted Seedance 2.0 with exact first/last-frame inputs',
    versions: ['latest'],
    modes: ['480p', '720p', '1080p'],
    modeControlLabel: 'Resolution',
    durations: [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    aspectRatios: SEEDANCE_2_ASPECT_RATIOS,
    referenceInputKinds: ['start-frame', 'end-frame'],
    supportsTextToVideo: true,
    supportsImageToVideo: true,
    supportsGenerateAudio: true,
    supportsMultiShot: false,
    maxReferenceMedia: 0,
    outputType: 'video',
  });

  entries.push({
    service: 'cloud',
    providerId: 'bytedance/seedance-2-fast',
    name: 'Seedance 2.0 Fast',
    description: 'Hosted Seedance 2.0 Fast with exact first/last-frame inputs',
    versions: ['latest'],
    modes: ['480p', '720p'],
    modeControlLabel: 'Resolution',
    durations: [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    aspectRatios: SEEDANCE_2_ASPECT_RATIOS,
    referenceInputKinds: ['start-frame', 'end-frame'],
    supportsTextToVideo: true,
    supportsImageToVideo: true,
    supportsGenerateAudio: true,
    supportsMultiShot: false,
    maxReferenceMedia: 0,
    outputType: 'video',
  });

  entries.push({
    service: 'cloud',
    providerId: VEO_3_1_PROVIDER_ID,
    name: 'Veo 3.1',
    description: 'Hosted Veo 3.1 via MasterSelects Cloud',
    versions: ['3.1'],
    modes: ['veo3_fast', 'veo3', 'veo3_lite'],
    modeLabels: VEO_MODE_LABELS,
    modeControlLabel: 'Model',
    durations: [],
    aspectRatios: ['16:9', '9:16'],
    referenceInputKinds: ['start-frame', 'end-frame', 'image-reference'],
    supportsTextToVideo: true,
    supportsImageToVideo: true,
    supportsGenerateAudio: false,
    supportsMultiShot: false,
    maxReferenceMedia: 3,
    outputType: 'video',
    promptRefinerProfile: 'veo',
  });

  entries.push({
    service: 'cloud',
    providerId: RUNWAY_VIDEO_PROVIDER_ID,
    name: 'Runway',
    description: 'Hosted Runway via MasterSelects Cloud',
    versions: ['latest'],
    modes: ['720p', '1080p'],
    modeControlLabel: 'Resolution',
    durations: [5, 10],
    aspectRatios: RUNWAY_ASPECT_RATIOS,
    referenceInputKinds: ['start-frame', 'image-reference'],
    supportsTextToVideo: true,
    supportsImageToVideo: true,
    supportsGenerateAudio: false,
    supportsMultiShot: false,
    maxReferenceMedia: 1,
    outputType: 'video',
    promptRefinerProfile: 'runway',
  });

  entries.push({
    service: 'cloud',
    providerId: TOPAZ_VIDEO_UPSCALE_PROVIDER_ID,
    name: 'Topaz Video Upscale',
    description: 'Hosted Topaz video upscaling via MasterSelects Cloud',
    versions: ['latest'],
    modes: ['2x', '4x'],
    modeControlLabel: 'Scale',
    durations: [],
    aspectRatios: [],
    referenceInputKinds: ['video-input'],
    supportsTextToVideo: true,
    supportsImageToVideo: false,
    supportsGenerateAudio: false,
    supportsMultiShot: false,
    maxReferenceMedia: 1,
    outputType: 'video',
    promptRefinerProfile: 'utility-video',
    requiredReferenceMediaType: 'video',
    requiresPrompt: false,
    requiresReferenceMedia: true,
  });

  entries.push(...HOSTED_KIE_IMAGE_ENTRIES.map((entry) => ({
    ...entry,
    versions: entry.providerId === 'nano-banana-2' ? ['latest'] : entry.versions,
  })));

  return entries;
}

export function getCatalogEntry(service: string, providerId: string): CatalogEntry | undefined {
  return getCatalogEntries().find(e => e.service === service && e.providerId === providerId);
}
