// Timeline component - Main orchestrator for video editing timeline
// Composes TimelineRuler, TimelineControls, TimelineHeader, TimelineTrack, TimelineKeyframes

import './Timeline.css';
import './TimelineTracks.css';
import './TimelineClip.css';
import { TimelineAuxiliaryLayer } from './components/TimelineAuxiliaryLayer';
import { TimelineBodySurface } from './components/TimelineBodySurface';
import { TimelineNavigatorChrome } from './components/TimelineNavigatorChrome';
import { TimelineSlotGridChrome } from './components/TimelineSlotGridChrome';
import { TimelineToolbarChrome } from './components/TimelineToolbarChrome';
import { TimelineRootShell } from './components/TimelineRootShell';
import { useTimelineZoom } from './hooks/useTimelineZoom';
import { useTimelineHelpers } from './hooks/useTimelineHelpers';
import { useTimelineHeaderWidthResize } from './hooks/useTimelineHeaderWidthResize';
import { useTimelineAuxiliaryInteractionController } from './hooks/useTimelineAuxiliaryInteractionController';
import { useTimelineActionController } from './hooks/useTimelineActionController';
import { useTimelineCompositionSwitchState } from './hooks/useTimelineCompositionSwitchState';
import { useTimelineRootStoreState } from './hooks/useTimelineRootStoreState';
import { useTimelineRenderedTrackMetrics } from './hooks/useTimelineRenderedTrackMetrics';
import { useTimelineHostRefs } from './hooks/useTimelineHostRefs';
import { useTimelineToolbarHostController } from './hooks/useTimelineToolbarHostController';
import { useTimelineRootChromeController } from './hooks/useTimelineRootChromeController';
import { useTimelinePlaybackController } from './hooks/useTimelinePlaybackController';
import { useTimelineInteractionController } from './hooks/useTimelineInteractionController';
import { useTimelineSurfaceController } from './hooks/useTimelineSurfaceController';
import { useTimelineTrackStackController } from './hooks/useTimelineTrackStackController';
import { useTimelineGraphHostController } from './hooks/useTimelineGraphHostController';
import { TimelinePickWhipProvider } from './TimelinePickWhipContext';

export function Timeline() {
  const timelineRootState = useTimelineRootStoreState();
  const {
    activeComposition,
    activeTimelineToolId,
    audioDisplayMode,
    audioFocusMode,
    audioRegionGainPreview,
    audioRegionSelection,
    audioSpectralRegionSelection,
    clipDragPreview,
    clipKeyframes,
    clipStemSeparationJobs,
    clips,
    currentlyGeneratingProxyId,
    duration,
    effectiveAudioLayerAdvancedMode,
    expandedCurveProperties,
    expandedTracks,
    exportProgress,
    exportRange,
    inPoint,
    isDraggingPlayhead,
    isExporting,
    isPlaying,
    isRamPreviewing,
    markers,
    mediaFiles,
    openCompositionTab,
    openCompositions,
    outPoint,
    playheadPosition,
    propertiesSelection,
    proxyEnabled,
    ramPreviewEnabled,
    ramPreviewProgress,
    ramPreviewRange,
    scrollX,
    selectedClipIds,
    selectedKeyframeIds,
    showInExplorer,
    slotGridProgress,
    snappingEnabled,
    thumbnailsEnabled,
    timelineRangeSelection,
    timelineSplitRatio,
    timelineToolCursor,
    timelineToolPreview,
    timelineTrackColorsVisible,
    toolMode,
    trackFocusMode,
    trackHeaderWidth,
    tracks,
    videoBakeRegionSelection,
    videoBakeRegions,
    waveformsEnabled,
    zoom,
  } = timelineRootState;

  const {
    actions: timelineActions,
    effectiveRamPreviewEnabled,
    effectiveRamPreviewProgress,
    effectiveRamPreviewRange,
    effectiveIsRamPreviewing,
  } = useTimelineActionController({
    clips,
    videoBakeRegions,
    ramPreviewEnabled,
    ramPreviewProgress,
    ramPreviewRange,
    isRamPreviewing,
  });

  const { timelineRef, timelineBodyRef, trackLanesRef, playheadRef, scrollWrapperRef } = useTimelineHostRefs();

  const {
    clipAnimationPhase,
    compositionSwitchDirection,
    isCompositionTrackMorphing,
    isTrackExpandedFromState,
    isTrackExpandedForRender,
    timelineSwitchMotionClass,
    timelineViewTracks,
  } = useTimelineCompositionSwitchState({
    tracks,
    expandedTracks,
  });

  const {
    clipMap,
    getRenderedTrackBaseHeight,
    getRenderedTrackHeight,
    getRenderedTrackHeightForTrack,
    isClipLocked,
    keyframeLayoutInputs,
    timelineViewTrackMap,
    trackMap,
  } = useTimelineRenderedTrackMetrics({
    audioDisplayMode,
    audioFocusMode,
    clipKeyframes,
    clips,
    expandedCurveProperties,
    getExpandedTrackHeight: timelineActions.getExpandedTrackHeight,
    isTrackExpandedForRender,
    selectedClipIds,
    timelineViewTracks,
    tracks,
  });

  // Time helpers - extracted to hook
  const compositionFrameRate = activeComposition?.frameRate ?? 30;
  const timelineHelpers = useTimelineHelpers({ zoom, frameRate: compositionFrameRate, clips, getClipKeyframes: timelineActions.getClipKeyframes });
  const {
    timeToPixel,
    pixelToTime,
    gridSize,
    gridPlan,
    formatTime,
    parseTime,
    getClipsAtTime,
    getSnapTargetTimes,
  } = timelineHelpers;

  const {
    activeJunction,
    aiAnimatedMarkers,
    clipDrag,
    clipFade,
    clipTrim,
    externalDrag,
    handleCombinedDragLeave,
    handleCombinedDragOver,
    handleCombinedDrop,
    handleClipDoubleClick,
    handleClipMouseDown,
    handleContainerDragLeave,
    handleFadeStart,
    handleNewTrackDragEnter,
    handleNewTrackDragOver,
    handleNewTrackDrop,
    markerDrag,
    markerCreateDrag,
    handleMarkerMouseDown,
    handlePlayheadMouseDown,
    handleSectionTracksMouseDown,
    handleTimelineMarkerMouseDown,
    handleTimelineRulerMouseDown,
    handleTrackDragEnter,
    handleTrackDragLeave,
    handleTrimStart,
    marquee,
    midiDrawGhost,
    timelineMarkerDrag,
  } = useTimelineInteractionController({
    activeTimelineToolId,
    addCameraClip: timelineActions.addCameraClip,
    addClip: timelineActions.addClip,
    addClipEffect: timelineActions.addClipEffect,
    addCompClip: timelineActions.addCompClip,
    addCompositionVideoBakeRegion: timelineActions.addCompositionVideoBakeRegion,
    addMarker: timelineActions.addMarker,
    addMathSceneClip: timelineActions.addMathSceneClip,
    addLightClip: timelineActions.addLightClip,
    addMeshClip: timelineActions.addMeshClip,
    addMotionShapeClip: timelineActions.addMotionShapeClip,
    addSolidClip: timelineActions.addSolidClip,
    addSplatEffectorClip: timelineActions.addSplatEffectorClip,
    addTextClip: timelineActions.addTextClip,
    addTrack: timelineActions.addTrack,
    applyTimelineEditOperation: timelineActions.applyTimelineEditOperation,
    cancelRamPreview: timelineActions.cancelRamPreview,
    clearTimelineRangeSelection: timelineActions.clearTimelineRangeSelection,
    clearVideoBakeRegionSelection: timelineActions.clearVideoBakeRegionSelection,
    clipKeyframes,
    clipMap,
    clips,
    deselectAllKeyframes: timelineActions.deselectAllKeyframes,
    duration,
    getClipKeyframes: timelineActions.getClipKeyframes,
    getExpandedTrackHeight: getRenderedTrackHeight,
    getPositionWithResistance: timelineActions.getPositionWithResistance,
    getRenderedTrackHeight: getRenderedTrackHeightForTrack,
    getSnapTargetTimes,
    getSnappedPosition: timelineActions.getSnappedPosition,
    getTrackBaseHeight: getRenderedTrackBaseHeight,
    inPoint,
    isDraggingPlayhead,
    isExporting,
    isPlaying,
    isRamPreviewing: effectiveIsRamPreviewing,
    isTrackExpanded: isTrackExpandedForRender,
    markers,
    moveMarker: timelineActions.moveMarker,
    openCompositionTab,
    outPoint,
    pause: timelineActions.pause,
    pixelToTime,
    playheadPosition,
    prepareTimelinePlacementRange: timelineActions.prepareTimelinePlacementRange,
    scrollX,
    selectClip: timelineActions.selectClip,
    selectClips: timelineActions.selectClips,
    selectKeyframe: timelineActions.selectKeyframe,
    selectedClipIds,
    selectedKeyframeIds,
    setDraggingPlayhead: timelineActions.setDraggingPlayhead,
    setInPoint: timelineActions.setInPoint,
    setOutPoint: timelineActions.setOutPoint,
    setPlayheadPosition: timelineActions.setPlayheadPosition,
    setTimelineRangeSelection: timelineActions.setTimelineRangeSelection,
    setTimelineToolPreview: timelineActions.setTimelineToolPreview,
    setVideoBakeRegionSelection: timelineActions.setVideoBakeRegionSelection,
    snappingEnabled,
    timeToPixel,
    timelineBodyRef,
    timelineRef,
    trackFocusMode,
    trackLanesRef,
    trackMap,
    tracks,
    updateClip: timelineActions.updateClip,
    updateTextProperties: timelineActions.updateTextProperties,
    videoBakeRegionSelection,
  });

  const timelineTrackStack = useTimelineTrackStackController({
    audioDisplayMode,
    audioFocusMode,
    clipDrag,
    clipKeyframes,
    clips,
    expandedCurveProperties,
    externalDrag,
    getExpandedTrackHeight: timelineActions.getExpandedTrackHeight,
    getRenderedTrackBaseHeight,
    isExporting,
    isTrackExpandedForRender,
    keyframeLayoutInputs,
    propertiesSelection,
    scrollWrapperRef,
    selectedClipIds,
    setTimelineSplitRatio: timelineActions.setTimelineSplitRatio,
    setTrackFocusMode: timelineActions.setTrackFocusMode,
    timelineBodyRef,
    timelineRef,
    timelineSplitRatio,
    timelineViewTrackMap,
    timelineViewTracks,
    trackFocusMode,
    trackHeaderWidth,
    trackMap,
    tracks,
  });
  const {
    videoTracks,
    audioTracks,
    anyViewVideoSolo,
    anyViewAudioSolo,
    isVideoTrackVisible,
    isAudioTrackMuted,
    timelineViewVideoTracks,
    timelineViewAudioTracks,
    displayedVideoTracks,
    displayedAudioTracks,
    audioScrollY,
    isSectionCollapsed,
    getFocusContextTrackHeight,
    getSectionTrackBaseHeight,
    getSectionTrackHeight,
    expandedVideoSectionContentHeight,
    audioNewTrackPreviewHeight,
    videoSectionHeight,
    audioSectionHeight,
    clipDragNewTrackType,
    contentHeight,
    forceVideoBottomScroll,
    trackSnapPositions,
    viewportHeight,
    timelineViewportWidth,
    videoScrollY,
    videoSectionViewportRef,
    audioSectionViewportRef,
    activeTrackResizeId,
    handleTrackResizeStart,
    splitDragVideoHeight,
    splitDragSmoothing,
    splitDragPinVideoBottom,
    handleTrackFocusStep,
    handleSplitDividerMouseDown,
    scrollY,
    setScrollY,
    handleSectionWheel,
    handleTrackHeightWheel,
  } = timelineTrackStack;

  const {
    globalCurveEditor,
    openTimelineGraphForProperty,
    timelineCurveMode,
    toggleTimelineCurveMode,
  } = useTimelineGraphHostController({
    rootState: timelineRootState,
    timelineActions,
    timelineHelpers,
    timelineTrackStack,
  });

  useTimelinePlaybackController({
    activeComposition,
    audioTracks,
    clipDrag,
    clipKeyframes,
    clipMap,
    clips,
    currentlyGeneratingProxyId,
    duration,
    getClipsAtTime,
    getSnapTargetTimes,
    inPoint,
    isAudioTrackMuted,
    isDraggingPlayhead,
    isPlaying,
    isRamPreviewing: effectiveIsRamPreviewing,
    isVideoTrackVisible,
    outPoint,
    pixelToTime,
    playheadPosition,
    proxyEnabled,
    ramPreviewEnabled: effectiveRamPreviewEnabled,
    ramPreviewRange: effectiveRamPreviewRange,
    scrollX,
    selectedClipIds,
    selectedKeyframeIds,
    snappingEnabled,
    timelineActions,
    toggleTimelineCurveMode,
    timelineRef,
    toolMode,
    tracks,
    videoTracks,
    zoom,
  });

  const {
    isTrackHeaderWidthResizing,
    handleTrackHeaderWidthResizeStart,
  } = useTimelineHeaderWidthResize({ trackHeaderWidth, setTrackHeaderWidth: timelineActions.setTrackHeaderWidth });

  // Zoom handling - extracted to hook
  const { handleSetZoom, handleFitToWindow } = useTimelineZoom({
    timelineBodyRef: timelineBodyRef,
    zoom,
    scrollX,
    scrollY,
    duration,
    playheadPosition,
    contentHeight,
    viewportHeight,
    trackSnapPositions,
    setZoom: timelineActions.setZoom,
    setScrollX: timelineActions.setScrollX,
    setScrollY,
  });

  const {
    auxiliaryLayerProps,
    contextMenu,
    setContextMenu,
    setEmptyContextMenu,
    setInOutContextMenu,
    setMarkerContextMenu,
    setTrackContextMenu,
    handleClipContextMenu,
    handleEmptyTimelineContextMenu,
    handleEmptyTimelineMouseDown,
    handleInOutMarkerContextMenu,
    handleTimelineClipMouseDown,
    handleTimelineMarkerContextMenu,
    pickWhipContextValue,
    handleTrackPickWhipDragEnd,
    handleTrackPickWhipDragStart,
  } = useTimelineAuxiliaryInteractionController({
    cancelRamPreview: timelineActions.cancelRamPreview,
    clipMap,
    clips,
    clipStemSeparationJobs,
    convertSolidToMotionShape: timelineActions.convertSolidToMotionShape,
    copyClipColor: timelineActions.copyClipColor,
    copyClipEffects: timelineActions.copyClipEffects,
    deleteAllGaps: timelineActions.deleteAllGaps,
    deleteClipSelection: timelineActions.deleteClipSelection,
    deleteGapAtTime: timelineActions.deleteGapAtTime,
    duration,
    generateSpectrogramForClip: timelineActions.generateSpectrogramForClip,
    generateWaveformForClip: timelineActions.generateWaveformForClip,
    handleClipMouseDown,
    handleFitToWindow,
    hasClipboardColor: timelineActions.hasClipboardColor,
    hasClipboardEffects: timelineActions.hasClipboardEffects,
    isClipLocked,
    isExporting,
    isPlaying,
    isRamPreviewing: effectiveIsRamPreviewing,
    linkClips: timelineActions.linkClips,
    markers,
    pause: timelineActions.pause,
    pasteClipColor: timelineActions.pasteClipColor,
    pasteClipEffects: timelineActions.pasteClipEffects,
    pixelToTime,
    removeClip: timelineActions.removeClip,
    removeMarker: timelineActions.removeMarker,
    rippleDeleteSelection: timelineActions.rippleDeleteSelection,
    scrollX,
    selectClip: timelineActions.selectClip,
    selectedClipIds,
    setAudioDisplayMode: timelineActions.setAudioDisplayMode,
    setClipParent: timelineActions.setClipParent,
    setDraggingPlayhead: timelineActions.setDraggingPlayhead,
    setInPoint: timelineActions.setInPoint,
    setOutPoint: timelineActions.setOutPoint,
    setPlayheadPosition: timelineActions.setPlayheadPosition,
    setTrackParent: timelineActions.setTrackParent,
    tracks,
    showInExplorer,
    splitClipAtPlayhead: timelineActions.splitClipAtPlayhead,
    startClipStemSeparation: timelineActions.startClipStemSeparation,
    syncClipsViaAudio: timelineActions.syncClipsViaAudio,
    thumbnailsEnabled,
    timelineRef,
    toggleClipReverse: timelineActions.toggleClipReverse,
    toggleThumbnailsEnabled: timelineActions.toggleThumbnailsEnabled,
    toggleWaveformsEnabled: timelineActions.toggleWaveformsEnabled,
    unlinkClips: timelineActions.unlinkClips,
    unlinkGroup: timelineActions.unlinkGroup,
    updateMarker: timelineActions.updateMarker,
    waveformsEnabled,
    audioDisplayMode,
  });

  const {
    handleToggleSlotGrid,
    navigatorChromeProps,
    rootShellProps,
    slotGridChromeProps,
  } = useTimelineRootChromeController({
    activeTrackResizeId,
    audioDisplayMode,
    audioFocusMode,
    clipInteractionActive: Boolean(clipDrag || clipTrim),
    duration,
    effectiveAudioLayerAdvancedMode,
    isHeaderWidthResizing: isTrackHeaderWidthResizing,
    onScrollChange: timelineActions.setScrollX,
    onZoomChange: handleSetZoom,
    openCompositionCount: openCompositions.length,
    scrollX,
    slotGridProgress,
    splitDragSmoothing,
    splitDragVideoHeight,
    timelineBodyRef,
    trackFocusMode,
    trackHeaderWidth,
    zoom,
  });

  const {
    timelineControlsProps,
    timelineToolbarProps,
  } = useTimelineToolbarHostController({
    formatTime,
    frameRate: compositionFrameRate,
    handleFitToWindow,
    handleSetZoom,
    handleToggleSlotGrid,
    parseTime,
    rootState: timelineRootState,
    timelineActions,
    timelineCurveMode,
    toggleTimelineCurveMode,
  });

  const bodySurfaceProps = useTimelineSurfaceController({
    activeJunction,
    activeTimelineToolId,
    activeTrackResizeId,
    addKeyframe: timelineActions.addKeyframe,
    anyViewAudioSolo,
    anyViewVideoSolo,
    applyTimelineEditOperation: timelineActions.applyTimelineEditOperation,
    audioDisplayMode,
    audioLayerAdvancedMode: effectiveAudioLayerAdvancedMode,
    audioNewTrackPreviewHeight,
    audioRegionGainPreview,
    audioRegionSelection,
    audioScrollY,
    audioSectionHeight,
    audioSectionViewportRef,
    audioSpectralRegionSelection,
    aiAnimatedMarkers,
    clipAnimationPhase,
    clipDrag,
    clipDragNewTrackType,
    clipDragPreview,
    clipFade,
    clipKeyframes,
    clipMap,
    clips,
    clipStemSeparationJobs,
    clipTrim,
    compositionSwitchDirection,
    contextMenu,
    displayedAudioTracks,
    displayedVideoTracks,
    duration,
    expandedCurveProperties,
    expandedVideoSectionContentHeight,
    exportProgress,
    exportRange,
    externalDrag,
    forceVideoBottomScroll,
    formatTime,
    frameRate: compositionFrameRate,
    getCachedRanges: timelineActions.getCachedRanges,
    getClipKeyframes: timelineActions.getClipKeyframes,
    getExpandedTrackHeight: timelineActions.getExpandedTrackHeight,
    getFocusContextTrackHeight,
    getInterpolatedEffects: timelineActions.getInterpolatedEffects,
    getInterpolatedTransform: timelineActions.getInterpolatedTransform,
    getProxyCachedRanges: timelineActions.getProxyCachedRanges,
    getScrubCachedRanges: timelineActions.getScrubCachedRanges,
    getSectionTrackBaseHeight,
    getSectionTrackHeight,
    globalMarkerDrag: markerDrag,
    gridPlan,
    gridSize,
    inOutMarkerContextMenu: handleInOutMarkerContextMenu,
    inOutMarkerMouseDown: handleMarkerMouseDown,
    inPoint,
    isCompositionTrackMorphing,
    isDraggingPlayhead,
    isExporting,
    isPlaying,
    isRamPreviewing: effectiveIsRamPreviewing,
    isSectionCollapsed,
    isTrackHeaderWidthResizing,
    isTrackExpandedForRender,
    isTrackExpandedFromState,
    markerCreateDrag,
    markers,
    marquee,
    mediaFiles,
    midiDrawGhost,
    onAddKeyframe: timelineActions.addKeyframe,
    bakeCompositionVideoBakeRegion: timelineActions.bakeCompositionVideoBakeRegion,
    onClipContextMenu: handleClipContextMenu,
    onClipDoubleClick: handleClipDoubleClick,
    onClipMouseDown: handleTimelineClipMouseDown,
    onCombinedDragLeave: handleCombinedDragLeave,
    onCombinedDragOver: handleCombinedDragOver,
    onCombinedDrop: handleCombinedDrop,
    onContainerDragLeave: handleContainerDragLeave,
    onEmptyContextMenu: handleEmptyTimelineContextMenu,
    onEmptyMouseDown: handleEmptyTimelineMouseDown,
    onFadeStart: handleFadeStart,
    onDeleteKeyframes: (keyframeIds) => {
      const transactionId = `context-menu-delete-keyframes:${Date.now()}`;
      timelineActions.applyTimelineEditOperation({
        id: transactionId,
        type: 'keyboard-delete-command',
        transactionId,
        historyBatchId: transactionId,
        source: 'context-menu',
        command: 'delete',
        priority: 'keyframes-only',
        keyframeIds,
        clipIds: [],
        includeLinked: false,
      }, {
        source: 'context-menu',
        historyLabel: keyframeIds.length > 1 ? 'Delete keyframes' : 'Delete keyframe',
      });
    },
    onRulerMouseDown: handleTimelineRulerMouseDown,
    onMoveKeyframe: timelineActions.moveKeyframe,
    onMoveKeyframeGroup: timelineActions.moveKeyframes,
    onNewTrackDragEnter: handleNewTrackDragEnter,
    onNewTrackDragLeave: handleTrackDragLeave,
    onNewTrackDragOver: handleNewTrackDragOver,
    onNewTrackDrop: handleNewTrackDrop,
    onRemoveRegion: timelineActions.removeCompositionVideoBakeRegion,
    onSectionTracksMouseDown: handleSectionTracksMouseDown,
    onSectionWheel: handleSectionWheel,
    onSelectKeyframe: timelineActions.selectKeyframe,
    onSetTrackParent: timelineActions.setTrackParent,
    onSplitDividerMouseDown: handleSplitDividerMouseDown,
    onTimelineMarkerContextMenu: handleTimelineMarkerContextMenu,
    onTimelineMarkerMouseDown: handleTimelineMarkerMouseDown,
    onToggleCurveExpanded: openTimelineGraphForProperty,
    onToggleAudioLayerAdvancedMode: timelineActions.toggleAudioLayerAdvancedMode,
    onTrackDragEnter: handleTrackDragEnter,
    onTrackFocusStep: handleTrackFocusStep,
    onTrackHeaderWidthResizeStart: handleTrackHeaderWidthResizeStart,
    onTrackHeightWheel: handleTrackHeightWheel,
    onTrackPickWhipDragEnd: handleTrackPickWhipDragEnd,
    onTrackPickWhipDragStart: handleTrackPickWhipDragStart,
    onTrackResizeStart: handleTrackResizeStart,
    onTrimStart: handleTrimStart,
    onUnbakeRegion: timelineActions.unbakeCompositionVideoBakeRegion,
    onUpdateKeyframe: timelineActions.updateKeyframe,
    onUpdateBezierHandle: timelineActions.updateBezierHandle,
    outPoint,
    pixelToTime,
    playheadMouseDown: handlePlayheadMouseDown,
    playheadPosition,
    playheadRef,
    proxyEnabled,
    ramPreviewProgress: effectiveRamPreviewProgress,
    scrollWrapperRef,
    scrollX,
    selectedClipIds,
    selectedKeyframeIds,
    setContextMenu,
    setEmptyContextMenu,
    setInOutContextMenu,
    setMarkerContextMenu,
    setPlayheadPosition: timelineActions.setPlayheadPosition,
    setPropertyValue: timelineActions.setPropertyValue,
    setScrollX: timelineActions.setScrollX,
    setTrackContextMenu,
    setZoom: timelineActions.setZoom,
    slotGridProgress,
    splitDragPinVideoBottom,
    splitDragVideoHeight,
    switchMotionClass: timelineSwitchMotionClass,
    timelineBodyRef,
    timelineControlsProps,
    timelineMarkerDrag,
    timelineRangeSelection,
    timelineRef,
    timelineToolPreview,
    timelineToolCursor,
    timelineTrackColorsVisible,
    timelineViewAudioTracks,
    timelineViewTrackMap,
    timelineViewTracks,
    timelineViewVideoTracks,
    timeToPixel,
    toggleTrackExpanded: timelineActions.toggleTrackExpanded,
    trackHasKeyframes: timelineActions.trackHasKeyframes,
    trackFocusMode,
    trackHeaderWidth,
    trackLanesRef,
    trackMap,
    videoBakeRegions,
    videoBakeRegionSelection,
    videoScrollY,
    videoSectionHeight,
    videoSectionViewportRef,
    viewportWidth: timelineViewportWidth,
    waveformsEnabled,
    zoom,
  });

  return (
    <TimelinePickWhipProvider value={pickWhipContextValue}>
      <TimelineRootShell {...rootShellProps}>
        <TimelineToolbarChrome {...timelineToolbarProps} />
        <TimelineSlotGridChrome {...slotGridChromeProps} />
        <TimelineBodySurface
          {...bodySurfaceProps}
          timelineCurveMode={timelineCurveMode}
          globalCurveEditor={globalCurveEditor}
        />

        <TimelineNavigatorChrome {...navigatorChromeProps} />

        <TimelineAuxiliaryLayer {...auxiliaryLayerProps} />
      </TimelineRootShell>
    </TimelinePickWhipProvider>
  );
}
