import crypto from "node:crypto";
import { writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import {
  analysisToolDefinitions,
  captionToolDefinitions,
  clipToolDefinitions,
  effectToolDefinitions,
  keyframeToolDefinitions,
  maskToolDefinitions,
  mediaToolDefinitions,
  motionDesignToolDefinitions,
  playbackToolDefinitions,
  previewToolDefinitions,
  storyboardToolDefinitions,
  textToolDefinitions,
  timelineToolDefinitions,
  trackToolDefinitions,
  transformToolDefinitions,
  transitionToolDefinitions,
} from "../apps/atlas/src/services/aiTools/definitions/index.ts";
import { isKernelEditorToolName } from "../apps/atlas/src/services/aiTools/editorToolCatalog.ts";
import { getToolPolicy } from "../apps/atlas/src/services/aiTools/policy/registry.ts";

type Phase = "core" | "advanced" | "full";
type Risk = "low" | "medium" | "destructive" | "external";

const categoryGroups = [
  ["timeline", "core", timelineToolDefinitions],
  ["clips", "core", clipToolDefinitions],
  ["tracks", "core", trackToolDefinitions],
  ["transform", "core", transformToolDefinitions],
  ["playback", "core", playbackToolDefinitions],
  ["transitions", "core", transitionToolDefinitions],
  ["media", "advanced", mediaToolDefinitions],
  ["effects", "advanced", effectToolDefinitions],
  ["keyframes", "advanced", keyframeToolDefinitions],
  ["text", "advanced", textToolDefinitions],
  ["captions", "advanced", captionToolDefinitions],
  ["masks", "advanced", maskToolDefinitions],
  ["analysis", "full", analysisToolDefinitions],
  ["preview", "full", previewToolDefinitions],
  ["motion", "full", motionDesignToolDefinitions],
  ["storyboard", "full", storyboardToolDefinitions],
] as const;

const categoryLabels: Record<string, string> = {
  timeline: "时间线", clips: "片段", tracks: "轨道", transform: "画面", playback: "播放与标记",
  transitions: "转场", media: "素材", effects: "效果", keyframes: "关键帧", text: "文字",
  captions: "字幕", masks: "蒙版", analysis: "媒体分析", preview: "预览", motion: "动效", storyboard: "故事板",
};

const destructiveNames = /^(delete|remove|archive|commit)/i;
const riskFor = (name: string, policy: NonNullable<ReturnType<typeof getToolPolicy>>): Risk => {
  if (destructiveNames.test(name) || policy.requiresConfirmation || policy.riskLevel === "high") return "destructive";
  return policy.riskLevel === "medium" ? "medium" : "low";
};

const tools = categoryGroups.flatMap(([category, minimumPhase, definitions]) => definitions
  .filter((definition) => isKernelEditorToolName(definition.function.name))
  .flatMap((definition) => {
    const policy = getToolPolicy(definition.function.name);
    if (!policy || policy.readOnly || policy.localFileAccess || policy.sensitiveDataAccess) return [];
    return [{
      name: definition.function.name,
      category,
      categoryLabel: categoryLabels[category],
      minimumPhase: minimumPhase as Phase,
      description: definition.function.description,
      schema: {
        ...definition.function.parameters,
        additionalProperties: false,
      },
      risk: riskFor(definition.function.name, policy),
      requiresConfirmation: true,
      execution: "native" as const,
    }];
  }));

tools.push({
  name: "requestFireflyExport",
  category: "timeline",
  categoryLabel: categoryLabels.timeline,
  minimumPhase: "core",
  description: "Open the Firefly export workflow for the current timeline after explicit user confirmation.",
  schema: {
    type: "object",
    properties: {
      preset: { type: "string", enum: ["mp4_h264_aac_1080p30"] },
      fileName: { type: "string", minLength: 1, maxLength: 180 },
    },
    required: ["preset"],
    additionalProperties: false,
  },
  risk: "external",
  requiresConfirmation: true,
  execution: "firefly",
});

tools.sort((left, right) => left.name.localeCompare(right.name));
const phaseRank: Record<Phase, number> = { core: 0, advanced: 1, full: 2 };
const catalogs = Object.fromEntries((["core", "advanced", "full"] as const).map((phase) => {
  const phaseTools = tools.filter((tool) => phaseRank[tool.minimumPhase] <= phaseRank[phase]);
  const version = `2-${phase}`;
  const digest = crypto.createHash("sha256").update(JSON.stringify({ version, tools: phaseTools })).digest("hex");
  return [phase, { version, digest, tools: phaseTools }];
}));
const source = `/* Generated by scripts/generate-atlas-agent-catalog.ts. Do not edit. */\n`
  + `export const ATLAS_AGENT_CATALOGS = ${JSON.stringify(catalogs, null, 2)} as const;\n`
  + `export const ATLAS_AGENT_CATALOG_VERSION = ATLAS_AGENT_CATALOGS.full.version;\n`
  + `export const ATLAS_AGENT_CATALOG_DIGEST = ATLAS_AGENT_CATALOGS.full.digest;\n`
  + `export const ATLAS_AGENT_GENERATED_TOOLS = ATLAS_AGENT_CATALOGS.full.tools;\n`;

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
await Promise.all([
  writeFile(path.join(root, "server/atlas-agent-catalog.generated.ts"), source, "utf8"),
  writeFile(path.join(root, "apps/atlas/src/firefly/atlas-agent-catalog.generated.ts"), source, "utf8"),
]);
