import type { TransitionDefinition } from '../types';

// Generated flare ghosts and streaks travel across the cut.
export const lensFlare: TransitionDefinition = {
  id: 'lens-flare',
  name: 'Lens Flare',
  category: 'light',
  defaultDuration: 1.15,
  minDuration: 0.1,
  maxDuration: 5,
  description: 'Deterministic lens flare streak and ghosts pass over the cut',
  params: {
    color: {
      type: 'color',
      label: 'Color',
      defaultValue: '#d7f0ff',
    },
  },
  recipe: [
    {
      kind: 'opacity',
      target: 'outgoing',
      from: 1,
      to: 0,
      startProgress: 0.16,
      endProgress: 0.82,
      curve: 'ease-in',
    },
    {
      kind: 'opacity',
      target: 'incoming',
      from: 0,
      to: 1,
      startProgress: 0.18,
      endProgress: 0.86,
      curve: 'ease-out',
    },
    {
      kind: 'overlay',
      overlay: 'lens-flare',
      color: '#d7f0ff',
      colorParam: 'color',
      blendMode: 'normal',
      opacity: { from: 0, to: 0.5 },
      centerX: { from: -0.22, to: 0.62 },
      width: 0.28,
      softness: 0.36,
      angle: -0.04,
      startProgress: 0.02,
      endProgress: 0.58,
      curve: 'ease-out',
    },
    {
      kind: 'overlay',
      overlay: 'lens-flare',
      color: '#d7f0ff',
      colorParam: 'color',
      blendMode: 'normal',
      opacity: { from: 0.36, to: 0 },
      centerX: { from: 0.46, to: 1.18 },
      width: 0.24,
      softness: 0.4,
      angle: -0.04,
      startProgress: 0.42,
      endProgress: 1,
      curve: 'ease-in',
    },
  ],
};
