import type { TransitionDefinition } from '../types';

export const whipPan: TransitionDefinition = {
  id: 'whip-pan',
  name: 'Whip Pan',
  category: 'zoom',
  defaultDuration: 0.8,
  minDuration: 0.1,
  maxDuration: 3,
  description: 'Fast horizontal pan through the cut with motion blur',
  recipe: [
    {
      kind: 'opacity',
      target: 'outgoing',
      from: 1,
      to: 0,
      startProgress: 0.22,
      endProgress: 0.72,
      curve: 'ease-in',
    },
    {
      kind: 'opacity',
      target: 'incoming',
      from: 0,
      to: 1,
      startProgress: 0.28,
      endProgress: 0.82,
      curve: 'ease-out',
    },
    {
      kind: 'transform',
      target: 'outgoing',
      translateX: { from: 0, to: -0.1 },
      scaleX: { from: 1, to: 1.18 },
      scaleY: { from: 1, to: 1.18 },
      startProgress: 0,
      endProgress: 0.68,
      curve: 'ease-in',
    },
    {
      kind: 'transform',
      target: 'incoming',
      translateX: { from: 0.1, to: 0 },
      scaleX: { from: 1.18, to: 1 },
      scaleY: { from: 1.18, to: 1 },
      startProgress: 0.32,
      endProgress: 1,
      curve: 'ease-out',
    },
    {
      kind: 'effect',
      target: 'outgoing',
      effectType: 'motion-blur',
      effectName: 'Motion Blur',
      params: {
        amount: { from: 0, to: 0.16 },
        angle: 0,
        samples: 40,
      },
      startProgress: 0,
      endProgress: 0.68,
      curve: 'ease-in',
    },
    {
      kind: 'effect',
      target: 'incoming',
      effectType: 'motion-blur',
      effectName: 'Motion Blur',
      params: {
        amount: { from: 0.16, to: 0 },
        angle: 0,
        samples: 40,
      },
      startProgress: 0.32,
      endProgress: 1,
      curve: 'ease-out',
    },
  ],
};
