// Voxel Relief - raymarched brightness-driven block extrusion.

import shader from './shader.wgsl?raw';
import type { EffectDefinition } from '../../types';

export const voxelRelief: EffectDefinition = {
  id: 'voxel-relief',
  name: 'Voxel Relief',
  category: 'stylize',

  shader,
  entryPoint: 'voxelReliefFragment',
  uniformSize: 80,
  usesFeedback: true,

  params: {
    columns: {
      type: 'number',
      label: 'Columns',
      default: 96,
      min: 12,
      max: 180,
      step: 1,
      animatable: true,
    },
    height: {
      type: 'number',
      label: 'Height',
      default: 0.36,
      min: 0,
      max: 1.2,
      step: 0.01,
      animatable: true,
    },
    baseHeight: {
      type: 'number',
      label: 'Base',
      default: 0.015,
      min: 0,
      max: 0.2,
      step: 0.005,
      animatable: true,
    },
    gap: {
      type: 'number',
      label: 'Gap',
      default: 0.06,
      min: 0,
      max: 0.36,
      step: 0.01,
      animatable: true,
    },
    tilt: {
      type: 'number',
      label: 'Tilt',
      default: 87,
      min: 20,
      max: 88,
      step: 1,
      animatable: true,
    },
    yaw: {
      type: 'number',
      label: 'Yaw',
      default: 0,
      min: -45,
      max: 45,
      step: 1,
      animatable: true,
    },
    perspective: {
      type: 'number',
      label: 'Perspective',
      default: 0.22,
      min: 0.15,
      max: 1.6,
      step: 0.01,
      animatable: true,
    },
    heightContrast: {
      type: 'number',
      label: 'Height Contrast',
      default: 1.08,
      min: 0.2,
      max: 3,
      step: 0.01,
      animatable: true,
    },
    ambient: {
      type: 'number',
      label: 'Ambient',
      default: 0.58,
      min: 0,
      max: 1,
      step: 0.01,
      animatable: true,
    },
    lightStrength: {
      type: 'number',
      label: 'Light',
      default: 0.48,
      min: 0,
      max: 2,
      step: 0.01,
      animatable: true,
    },
    colorMix: {
      type: 'number',
      label: 'Color',
      default: 0.95,
      min: 0,
      max: 1,
      step: 0.01,
      animatable: true,
    },
    temporalBlend: {
      type: 'number',
      label: 'Smoothing',
      default: 0.08,
      min: 0,
      max: 0.9,
      step: 0.01,
      animatable: true,
    },
    lightAngle: {
      type: 'number',
      label: 'Light Angle',
      default: 310,
      min: 0,
      max: 360,
      step: 1,
      animatable: true,
    },
    lightElevation: {
      type: 'number',
      label: 'Light Elevation',
      default: 45,
      min: 5,
      max: 85,
      step: 1,
      animatable: true,
    },
    floorBrightness: {
      type: 'number',
      label: 'Gaps',
      default: 0.1,
      min: 0,
      max: 1,
      step: 0.01,
      animatable: true,
    },
    edgeDarkness: {
      type: 'number',
      label: 'Edges',
      default: 0.68,
      min: 0,
      max: 1,
      step: 0.01,
      animatable: true,
    },
    maxSteps: {
      type: 'number',
      label: 'Ray Steps',
      default: 72,
      min: 24,
      max: 144,
      step: 1,
      animatable: false,
      quality: true,
    },
    reset: {
      type: 'boolean',
      label: 'Reset Smoothing',
      default: false,
      animatable: false,
    },
  },

  packUniforms: (params, width, height) => {
    const reset = params.reset === true ? 1 : 0;

    return new Float32Array([
      Number(params.columns ?? 96),
      Number(params.height ?? 0.36),
      Number(params.baseHeight ?? 0.015),
      Number(params.gap ?? 0.06),
      Number(params.tilt ?? 87),
      Number(params.yaw ?? 0),
      Number(params.perspective ?? 0.22),
      Number(params.heightContrast ?? 1.08),
      Number(params.ambient ?? 0.58),
      Number(params.lightStrength ?? 0.48),
      Number(params.temporalBlend ?? 0.08),
      Number(params.colorMix ?? 0.95),
      width,
      height,
      Number(params.maxSteps ?? 72),
      reset,
      Number(params.lightAngle ?? 310),
      Number(params.lightElevation ?? 45),
      Number(params.floorBrightness ?? 0.1),
      Number(params.edgeDarkness ?? 0.68),
    ]);
  },
};
